# Generated by Django 5.1.4 on 2026-10-03 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0005_mapa_de_conhecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_nome', models.CharField(max_length=80)),
                ('site_id', models.CharField(max_length=64)),
                ('site_host', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(choices=[('material', 'Material comercial'), ('depoimento', 'Depoimento')], default='material', max_length=20)),
                ('produto', models.CharField(blank=True, default='', max_length=255)),
                ('oferta', models.CharField(blank=True, default='', max_length=255)),
                ('utilizavel', models.BooleanField(default=False)),
                ('marcado_por', models.CharField(blank=True, default='', max_length=200)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agentes_materialcomercial',
                'constraints': [models.UniqueConstraint(fields=('documento_nome', 'site_id'), name='uma_marca_comercial_por_documento_e_site')],
            },
        ),
        migrations.CreateModel(
            name='TrechoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('site_host', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(max_length=20)),
                ('ref', models.CharField(max_length=255)),
                ('produto_ref', models.CharField(blank=True, default='', max_length=64)),
                ('produto_nome', models.CharField(blank=True, default='', max_length=255)),
                ('oferta_ref', models.CharField(blank=True, default='', max_length=255)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('texto_normal', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('publico', models.BooleanField(default=True)),
                ('endereco', models.CharField(blank=True, default='', max_length=300)),
                ('vigente_desde', models.DateTimeField(blank=True, null=True)),
                ('conferido_em', models.DateTimeField()),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos_comerciais', to='agentes.fontedoconhecimento')),
            ],
            options={
                'db_table': 'agentes_trechocomercial',
                'ordering': ['fonte_id', 'ordem'],
                'indexes': [models.Index(fields=['site_id', 'tipo'], name='trecho_comercial_site_tipo')],
            },
        ),
    ]
