# Generated by Django 5.1.4 on 2026-10-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0007_super_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='tipo',
            field=models.CharField(choices=[('conversa', 'Resposta na conversa'), ('panorama_semanal', 'Panorama semanal'), ('conferencia_quiz', 'Conferência dos links do quiz'), ('leitura_quiz', 'Leitura dos números do quiz'), ('conhecimento', 'Leitura dos documentos para o mapa de conhecimento'), ('satisfacao', 'Cuidado com a satisfação dos alunos'), ('super_equipe', 'Equipe de especialistas técnicos')], max_length=30),
        ),
        migrations.CreateModel(
            name='AnaliseSatisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('aluno_id', models.CharField(max_length=200)),
                ('avaliacao_id', models.CharField(max_length=100)),
                ('tarefa_id', models.IntegerField(null=True)),
                ('assinatura', models.CharField(default='', max_length=64)),
                ('contexto', models.JSONField(default=dict)),
                ('resultado', models.JSONField(default=dict)),
                ('analisada_em', models.DateTimeField(null=True)),
                ('entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentes.entrega')),
                ('execucao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentes.execucao')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'aluno_id', 'avaliacao_id'), name='satisfacao_um_caso')],
            },
        ),
    ]
