# Generated by Django 5.1.4 on 2026-10-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0009_satisfacao_independente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelhoriaSuperEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=64)),
                ('titulo', models.CharField(max_length=300)),
                ('prioridade', models.PositiveSmallIntegerField(default=2)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente de execução'), ('executando', 'Em execução'), ('publicando', 'Acompanhando publicação'), ('mantenedor', 'Precisa do mantenedor'), ('resolvida', 'Resolvida e conferida')], default='pendente', max_length=20)),
                ('evidencia', models.JSONField(default=dict)),
                ('resultado', models.TextField(blank=True, default='')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('observada_em', models.DateTimeField()),
                ('resolvida_em', models.DateTimeField(null=True)),
                ('posse', models.CharField(blank=True, default='', max_length=36)),
                ('ocupada_ate', models.DateTimeField(null=True)),
                ('entrega', models.CharField(blank=True, default='', max_length=12)),
                ('custo_externo_usd', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('trabalho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentes.execucao')),
            ],
            options={
                'ordering': ['prioridade', 'criada_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventoSuperEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(max_length=20)),
                ('texto', models.TextField()),
                ('melhoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='agentes.melhoriasuperequipe')),
            ],
            options={
                'ordering': ['momento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RotinaSuperEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, unique=True)),
                ('site_id', models.CharField(blank=True, default='', max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('proxima_em', models.DateTimeField(null=True)),
                ('observada_em', models.DateTimeField(null=True)),
                ('posse', models.CharField(blank=True, default='', max_length=36)),
                ('ocupada_ate', models.DateTimeField(null=True)),
                ('assinatura', models.CharField(blank=True, default='', max_length=64)),
                ('ultimo_erro', models.CharField(blank=True, default='', max_length=300)),
                ('executor_em', models.DateTimeField(null=True)),
                ('ultimo_trabalho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentes.execucao')),
            ],
        ),
        migrations.AddField(
            model_name='melhoriasuperequipe',
            name='rotina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='melhorias', to='agentes.rotinasuperequipe'),
        ),
        migrations.AddConstraint(
            model_name='melhoriasuperequipe',
            constraint=models.UniqueConstraint(fields=('rotina', 'chave'), name='super_equipe_uma_melhoria'),
        ),
    ]
