# Generated by Django 5.1.4 on 2026-08-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContadorDeNaoLidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                ("destinatario_id", models.CharField(max_length=64)),
                ("nao_lidos", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_id", "destinatario_id"),
                        name="contador_um_por_pessoa",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                ("destinatario_id", models.CharField(max_length=64)),
                ("ator_id", models.CharField(blank=True, max_length=64, null=True)),
                ("assunto", models.CharField(max_length=64)),
                ("parametros", models.JSONField()),
                ("origem_event_id", models.UUIDField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("lido_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site_id", "destinatario_id", "-criado_em"],
                        name="notif_caixa_da_pessoa",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificacaoArquivada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                ("destinatario_id", models.CharField(max_length=64)),
                ("ator_id", models.CharField(blank=True, max_length=64, null=True)),
                ("assunto", models.CharField(max_length=64)),
                ("parametros", models.JSONField()),
                ("origem_event_id", models.UUIDField()),
                ("criado_em", models.DateTimeField()),
                ("lido_em", models.DateTimeField()),
                ("arquivada_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site_id", "destinatario_id", "-criado_em"],
                        name="notif_arquivo_da_pessoa",
                    )
                ],
            },
        ),
    ]
