# Generated by Django 5.1.4 on 2026-08-27 15:48
#
# Fase 4 do sininho (`contracts/notificacoes.openapi.yaml`, Rito de Contrato de
# 27/08/2026): as três rotas novas (`/resumo`, `/avisos`, `/marcar-lidas`) só
# recebem `destinatario_id` — nunca `site_id`. Os três índices que a gênese
# apostou, liderados por `site_id`, não casam com nenhuma consulta real que
# esta célula faz; os que entram aqui lideram por `destinatario_id` (e, no
# caso de `ContadorDeNaoLidos`, é um índice NOVO — o `UniqueConstraint` da
# gênese não usa `destinatario_id` como coluna líder). Motivo completo nos
# comentários de `apps/notificacoes/models.py` e em `LICOES.md` desta célula.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notificacao",
            name="notif_caixa_da_pessoa",
        ),
        migrations.RemoveIndex(
            model_name="notificacaoarquivada",
            name="notif_arquivo_da_pessoa",
        ),
        migrations.AddIndex(
            model_name="contadordenaolidos",
            index=models.Index(fields=["destinatario_id"], name="contador_por_pessoa"),
        ),
        migrations.AddIndex(
            model_name="notificacao",
            index=models.Index(
                fields=["destinatario_id", "-criado_em"], name="notif_caixa_da_pessoa"
            ),
        ),
        migrations.AddIndex(
            model_name="notificacaoarquivada",
            index=models.Index(
                fields=["destinatario_id", "-criado_em"], name="notif_arquivo_da_pessoa"
            ),
        ),
    ]
