# Generated by Django 5.1.4 on 2026-08-27 16:48
#
# Emenda de 27/08/2026 ao contrato da Fase 4 (PR #282): `site_id` virou
# obrigatório nas três rotas (decisão do mantenedor, CONSTITUICAO.md Lei 9 —
# "cada site mostra só os avisos que vieram dele"). A migração 0002 apostou
# errado (liderou os índices só por `destinatario_id`, e ainda ACRESCENTOU um
# índice extra em `ContadorDeNaoLidos`) porque foi escrita ANTES dessa emenda.
#
# Medido com `EXPLAIN ANALYZE`, não suposto (`tests/test_indices_da_porta_de_
# consulta.py` reproduz a mesma medição):
#   - `Notificacao`/`NotificacaoArquivada`: o índice da 0002 (só
#     `destinatario_id`) obrigava o Postgres a ler TODAS as linhas da pessoa
#     em QUALQUER site e descartar o resto com um `Filter` pós-índice — com
#     uma pessoa em 5 sites (1500 linhas, 300 no site pedido), "Rows Removed
#     by Filter: 1200". Os dois índices agora lideram por
#     `(site_id, destinatario_id)`, e o Postgres usa `Index Cond` para as
#     duas colunas — zero linha descartada.
#   - `ContadorDeNaoLidos`: o `UniqueConstraint contador_um_por_pessoa`
#     (`site_id`, `destinatario_id`) já era, sozinho, o índice ideal para essa
#     mesma pergunta — o índice extra que a 0002 acrescentou
#     (`contador_por_pessoa`, só `destinatario_id`) nunca precisou existir;
#     ele só custava escrita e nunca era escolhido pelo planejador assim que
#     a query passou a filtrar as duas colunas. Removido aqui.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0002_indices_da_porta_de_consulta"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contadordenaolidos",
            name="contador_por_pessoa",
        ),
        migrations.RemoveIndex(
            model_name="notificacao",
            name="notif_caixa_da_pessoa",
        ),
        migrations.RemoveIndex(
            model_name="notificacaoarquivada",
            name="notif_arquivo_da_pessoa",
        ),
        migrations.AddIndex(
            model_name="notificacao",
            index=models.Index(
                fields=["site_id", "destinatario_id", "-criado_em"],
                name="notif_caixa_da_pessoa",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacaoarquivada",
            index=models.Index(
                fields=["site_id", "destinatario_id", "-criado_em"],
                name="notif_arquivo_da_pessoa",
            ),
        ),
    ]
