# Generated by Django 5.1.4 on 2026-08-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0002_marcar_lidas_as_cartas_do_backfill_da_sugestoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscricaoPush",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                ("destinatario_id", models.CharField(max_length=64)),
                ("endpoint", models.CharField(max_length=2048, unique=True)),
                ("p256dh", models.CharField(max_length=256)),
                ("auth", models.CharField(max_length=64)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("visto_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site_id", "destinatario_id"],
                        name="notif_aparelhos_da_pessoa",
                    )
                ],
            },
        ),
    ]
