# Generated by Django 5.0.14 on 2026-08-18 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("host", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("theme", models.JSONField(blank=True, default=dict)),
                (
                    "default_offer_slug",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
        ),
    ]
# golpe4: comentario trivial e reversivel para teste de orcamento
