# Generated by Django 5.0.9 on 2026-08-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="default_language",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="site",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
