# Generated by Django 5.1.4 on 2026-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_idioma_do_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="menu",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
