# Generated by Django 5.1.4 on 2026-08-30 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id_da_plataforma",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nome_exibido", models.CharField(blank=True, max_length=120)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("vista_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "pessoas",
            },
        ),
        migrations.CreateModel(
            name="ConquistaDefinicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60)),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("medalha", "Medalha (andaime)"),
                            ("marco", "Marco real (espinha)"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "familia",
                    models.CharField(
                        choices=[
                            ("oficio", "Ofício"),
                            ("comunidade", "Comunidade"),
                            ("epoca", "Época"),
                            ("secreta", "Secreta"),
                            ("carreira", "Carreira"),
                            ("espelho", "Espelho (a própria evolução)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("criterio", models.JSONField(blank=True, default=dict)),
                (
                    "faixa_etaria",
                    models.CharField(
                        choices=[
                            ("todas", "Todas as idades"),
                            ("13mais", "13 anos ou mais"),
                        ],
                        default="todas",
                        max_length=6,
                    ),
                ),
                ("envolve_dinheiro", models.BooleanField(default=False)),
                ("exige_validador_adulto", models.BooleanField(default=False)),
                ("secreta", models.BooleanField(default=False)),
                ("pontos", models.PositiveIntegerField(default=0)),
                ("cristais", models.PositiveIntegerField(default=0)),
                ("ativa", models.BooleanField(default=False)),
                ("versao", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["site_id", "slug"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_id", "slug"),
                        name="uma_conquista_por_slug_por_site",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("classe", "marco"), _negated=True),
                            ("pontos", 0),
                            _connector="OR",
                        ),
                        name="marco_real_rende_zero_xp",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("envolve_dinheiro", True), _negated=True),
                            models.Q(
                                ("exige_validador_adulto", True),
                                ("faixa_etaria", "13mais"),
                            ),
                            _connector="OR",
                        ),
                        name="marco_de_dinheiro_e_13mais_e_so_adulto_valida",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemCosmetico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60)),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("titulo", "Título exibido ao lado do nome"),
                            ("moldura", "Moldura do retrato"),
                            ("tema", "Tema visual da página de conquistas"),
                            ("decoracao_estudio", "Decoração do Meu Estúdio"),
                        ],
                        max_length=32,
                    ),
                ),
                ("custo_em_cristais", models.PositiveIntegerField(default=0)),
                ("sazonal", models.BooleanField(default=False)),
                ("ativa", models.BooleanField(default=False)),
                ("versao", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["site_id", "slug"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_id", "slug"),
                        name="um_cosmetico_por_slug_por_site",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "tipo__in",
                                ["titulo", "moldura", "tema", "decoracao_estudio"],
                            )
                        ),
                        name="tipo_de_cosmetico_e_so_estetica",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LigaDefinicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60)),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("prata", "Prata"),
                            ("ouro", "Ouro"),
                            ("platina", "Platina"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("limiar_de_promocao", models.PositiveIntegerField(default=0)),
                ("tamanho_do_grupo", models.PositiveSmallIntegerField(default=15)),
                ("ativa", models.BooleanField(default=False)),
                ("versao", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["site_id", "ordem"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_id", "slug"), name="uma_liga_por_slug_por_site"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tier__in", ["bronze", "prata", "ouro", "platina"])
                        ),
                        name="tier_de_liga_e_um_dos_quatro",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GrupoDaSemana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("semana", models.DateField()),
                ("codigo", models.CharField(max_length=32)),
                (
                    "liga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grupos",
                        to="gamificacao.ligadefinicao",
                    ),
                ),
            ],
            options={
                "ordering": ["-semana"],
            },
        ),
        migrations.CreateModel(
            name="MissaoDefinicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60)),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                (
                    "cadencia",
                    models.CharField(
                        choices=[
                            ("diaria", "Diária"),
                            ("semanal", "Semanal"),
                            ("dupla", "De dupla"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("criar", "Criar alguma coisa"),
                            ("aprender", "Aprender alguma coisa"),
                            ("ajudar", "Ajudar alguém"),
                            ("polir", "Melhorar uma obra que já existe"),
                            ("mostrar", "Mostrar o trabalho para alguém"),
                        ],
                        max_length=8,
                    ),
                ),
                ("meta", models.PositiveIntegerField(default=1)),
                ("pontos", models.PositiveIntegerField(default=0)),
                ("cristais", models.PositiveIntegerField(default=0)),
                ("ativa", models.BooleanField(default=False)),
                ("versao", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["site_id", "slug"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_id", "slug"), name="uma_missao_por_slug_por_site"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("meta__gte", 1)),
                        name="missao_pede_ao_menos_um_passo",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NivelDefinicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.PositiveSmallIntegerField()),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("xp_necessario", models.PositiveIntegerField()),
                ("titulo", models.CharField(max_length=60)),
                (
                    "titulo_feminino",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("ativa", models.BooleanField(default=False)),
                ("versao", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["site_id", "nivel"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_id", "nivel"), name="um_nivel_por_numero_por_site"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("nivel__gte", 1)),
                        name="nivel_definido_comeca_em_um",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("event", models.CharField(max_length=100)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("payload", models.JSONField()),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("envelope_extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["published_at"], name="gamificacao_publish_8a65ce_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerfilJogador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("xp_total", models.PositiveIntegerField(default=0)),
                ("nivel", models.PositiveSmallIntegerField(default=1)),
                ("cristais_saldo", models.PositiveIntegerField(default=0)),
                (
                    "modo",
                    models.CharField(
                        choices=[
                            ("junior", "Júnior (abaixo de 13 anos)"),
                            ("teen", "13 anos ou mais"),
                        ],
                        default="junior",
                        max_length=6,
                    ),
                ),
                ("modo_foco", models.BooleanField(default=False)),
                ("participa_de_ligas", models.BooleanField(default=False)),
                ("celebracoes_pendentes", models.JSONField(blank=True, default=list)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perfis",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoDeValidacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("marco", "Marco de carreira"),
                            ("obra", "Obra para a galeria"),
                            ("ajuda", "Ajuda prestada a um colega"),
                        ],
                        max_length=5,
                    ),
                ),
                ("evidencia", models.TextField(blank=True)),
                ("evidencia_privada", models.BooleanField(default=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("em_analise", "Em análise"),
                            ("aceito", "Aceito"),
                            ("devolvido", "Devolvido com o que falta"),
                        ],
                        default="em_analise",
                        max_length=10,
                    ),
                ),
                ("prazo_ate", models.DateTimeField(blank=True, null=True)),
                (
                    "atribuido_a",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "motivo_da_devolucao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("falta_evidencia", "Falta a evidência"),
                            ("evidencia_ilegivel", "A evidência não dá para ler"),
                            ("fora_do_criterio", "Ainda não cumpre o critério"),
                            ("precisa_de_adulto", "Precisa de um adulto da equipe"),
                        ],
                        default="",
                        max_length=18,
                    ),
                ),
                ("devolucoes", models.PositiveSmallIntegerField(default=0)),
                ("escalado_para_adulto", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("respondido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "conquista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="gamificacao.conquistadefinicao",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["prazo_ate", "criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ParticipacaoNaLiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("pontos_da_semana", models.PositiveIntegerField(default=0)),
                ("promovido", models.BooleanField(default=False)),
                ("inscrita_em", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participacoes",
                        to="gamificacao.grupodasemana",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participacoes",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-pontos_da_semana"],
            },
        ),
        migrations.CreateModel(
            name="MovimentoDeCristais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("delta", models.IntegerField()),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("conquista", "Medalha ou marco concedido"),
                            ("missao", "Missão cumprida"),
                            ("sequencia", "Semana de sequência fechada"),
                            ("ajuda_validada", "Ajuda validada pela comunidade"),
                            ("correcao_da_equipe", "Correção de um adulto da equipe"),
                            ("compra_na_loja", "Gasto na loja de cosméticos"),
                        ],
                        max_length=32,
                    ),
                ),
                ("referencia", models.CharField(max_length=120)),
                ("occurred_at", models.DateTimeField()),
                ("dia_local", models.DateField(db_index=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentos",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="LancamentoDeXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("pontos", models.IntegerField()),
                ("origem_event_id", models.CharField(max_length=64)),
                ("regra_slug", models.SlugField(max_length=60)),
                ("regra_versao", models.PositiveIntegerField(default=1)),
                ("occurred_at", models.DateTimeField()),
                ("dia_local", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Em quarentena"),
                            ("definitivo", "Definitivo"),
                            ("estornado", "Estornado"),
                        ],
                        default="definitivo",
                        max_length=10,
                    ),
                ),
                ("liberado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoDeSequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("semana", models.DateField()),
                ("dias_ativos", models.PositiveSmallIntegerField(default=0)),
                ("meta_dias", models.PositiveSmallIntegerField(default=3)),
                (
                    "desfecho",
                    models.CharField(
                        choices=[
                            ("cumprida", "Meta cumprida"),
                            ("protegida", "Falhou, mas o escudo segurou"),
                            ("regrediu", "Falhou e regrediu um degrau"),
                            ("ferias", "Modo férias"),
                        ],
                        max_length=9,
                    ),
                ),
                ("semanas_apos", models.PositiveIntegerField(default=0)),
                ("fechada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_de_sequencia",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-semana"],
            },
        ),
        migrations.CreateModel(
            name="Forja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("desafio_ref", models.CharField(max_length=64)),
                ("medidor", models.PositiveIntegerField(default=0)),
                ("teto", models.PositiveIntegerField(default=99)),
                ("selada_em", models.DateTimeField(blank=True, null=True)),
                ("selo", models.CharField(blank=True, default="", max_length=120)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forjas",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfiancaDaComunidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("peso", models.IntegerField(default=0)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confianca",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Concessao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("concedida_em", models.DateTimeField(auto_now_add=True)),
                (
                    "origem_event_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "validador_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "validador_papel",
                    models.CharField(
                        choices=[
                            ("professor", "Professor"),
                            ("monitor", "Monitor"),
                            ("par", "Um colega"),
                            ("sistema", "O sistema (conta automática)"),
                        ],
                        default="sistema",
                        max_length=9,
                    ),
                ),
                (
                    "consentimento",
                    models.CharField(
                        choices=[
                            ("privado", "Só a pessoa vê"),
                            ("turma", "A turma vê"),
                            ("publico", "Aparece no Meu Estúdio público"),
                        ],
                        default="privado",
                        max_length=7,
                    ),
                ),
                (
                    "conquista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concessoes",
                        to="gamificacao.conquistadefinicao",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concessoes",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-concedida_em"],
            },
        ),
        migrations.CreateModel(
            name="Aquisicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("equipado", models.BooleanField(default=False)),
                ("adquirida_em", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquisicoes",
                        to="gamificacao.itemcosmetico",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquisicoes",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-adquirida_em"],
            },
        ),
        migrations.CreateModel(
            name="ProgressoDeMissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("janela", models.DateField()),
                ("progresso", models.PositiveIntegerField(default=0)),
                ("cumprida_em", models.DateTimeField(blank=True, null=True)),
                (
                    "missao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progressos",
                        to="gamificacao.missaodefinicao",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progressos",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-janela"],
            },
        ),
        migrations.CreateModel(
            name="RegraDePontuacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60)),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("evento_gatilho", models.CharField(max_length=100)),
                (
                    "beneficiario",
                    models.CharField(
                        choices=[
                            ("ator", "Quem fez a ação"),
                            (
                                "autor_do_alvo",
                                "Quem escreveu o que foi votado ou aceito",
                            ),
                        ],
                        default="ator",
                        max_length=13,
                    ),
                ),
                ("pontos", models.PositiveIntegerField(default=0)),
                ("cristais", models.PositiveIntegerField(default=0)),
                ("acoes_cheias_por_dia", models.PositiveSmallIntegerField(default=0)),
                ("quarentena_horas", models.PositiveSmallIntegerField(default=0)),
                ("ativa", models.BooleanField(default=False)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["site_id", "slug"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_id", "slug"), name="uma_regra_por_slug_por_site"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Sequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                (
                    "ritmo",
                    models.CharField(
                        choices=[
                            ("leve", "Leve (3 dias por semana)"),
                            ("normal", "Normal (5 dias por semana)"),
                            ("intensa", "Intensa (7 dias por semana)"),
                        ],
                        default="leve",
                        max_length=7,
                    ),
                ),
                ("meta_dias", models.PositiveSmallIntegerField(default=3)),
                ("dias_ativos_na_semana", models.PositiveSmallIntegerField(default=0)),
                ("semana_corrente", models.DateField()),
                ("semanas_atuais", models.PositiveIntegerField(default=0)),
                ("recorde_semanas", models.PositiveIntegerField(default=0)),
                ("dias_totais", models.PositiveIntegerField(default=0)),
                ("escudos", models.PositiveSmallIntegerField(default=0)),
                ("modo_ferias", models.BooleanField(default=False)),
                ("ferias_ate", models.DateField(blank=True, null=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sequencias",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsoDeEscudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("semana", models.DateField()),
                ("usado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escudos_usados",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-semana"],
            },
        ),
        migrations.AddConstraint(
            model_name="grupodasemana",
            constraint=models.UniqueConstraint(
                fields=("site_id", "liga", "semana", "codigo"),
                name="um_grupo_por_codigo_por_semana",
            ),
        ),
        migrations.AddConstraint(
            model_name="perfiljogador",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "site_id"), name="um_perfil_por_pessoa_por_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="perfiljogador",
            constraint=models.CheckConstraint(
                condition=models.Q(("nivel__gte", 1)), name="nivel_comeca_em_um"
            ),
        ),
        migrations.AddIndex(
            model_name="pedidodevalidacao",
            index=models.Index(
                fields=["site_id", "estado", "prazo_ate"],
                name="gamificacao_site_id_ec4cb3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pedidodevalidacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "devolvido"), _negated=True),
                    models.Q(("motivo_da_devolucao", ""), _negated=True),
                    _connector="OR",
                ),
                name="motivo_da_devolucao_e_obrigatorio",
            ),
        ),
        migrations.AddConstraint(
            model_name="participacaonaliga",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "grupo"), name="uma_participacao_por_grupo"
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentodecristais",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "site_id", "referencia"),
                name="um_movimento_de_cristal_por_referencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentodecristais",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "origem__in",
                        [
                            "conquista",
                            "missao",
                            "sequencia",
                            "ajuda_validada",
                            "correcao_da_equipe",
                            "compra_na_loja",
                        ],
                    )
                ),
                name="origem_de_cristal_no_vocabulario_fechado",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentodecristais",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("delta__gt", 0), _negated=True),
                    models.Q(("origem", "compra_na_loja"), _negated=True),
                    _connector="OR",
                ),
                name="cristal_positivo_nunca_vem_de_compra",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentodecristais",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("delta__lt", 0), _negated=True),
                    models.Q(
                        ("origem", "compra_na_loja"),
                        ("referencia__startswith", "compra:"),
                    ),
                    _connector="OR",
                ),
                name="cristal_negativo_so_com_referencia_de_compra",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentodecristais",
            constraint=models.CheckConstraint(
                condition=models.Q(("delta", 0), _negated=True),
                name="movimento_de_cristal_nunca_e_zero",
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentodexp",
            index=models.Index(
                fields=["pessoa", "site_id", "dia_local"],
                name="gamificacao_pessoa__b1d97f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentodexp",
            index=models.Index(
                fields=["status", "liberado_em"], name="gamificacao_status_f13e98_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentodexp",
            constraint=models.UniqueConstraint(
                fields=("origem_event_id", "regra_slug", "pessoa"),
                name="um_lancamento_por_evento_por_regra_por_pessoa",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentodexp",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "pendente"), _negated=True),
                    ("liberado_em__isnull", False),
                    _connector="OR",
                ),
                name="quarentena_tem_data_para_acabar",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicodesequencia",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "site_id", "semana"),
                name="uma_linha_de_historico_por_semana",
            ),
        ),
        migrations.AddConstraint(
            model_name="forja",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "site_id", "desafio_ref"),
                name="uma_forja_por_desafio_por_pessoa",
            ),
        ),
        migrations.AddConstraint(
            model_name="forja",
            constraint=models.CheckConstraint(
                condition=models.Q(("medidor__lte", models.F("teto"))),
                name="o_medidor_da_forja_respeita_o_teto",
            ),
        ),
        migrations.AddConstraint(
            model_name="confiancadacomunidade",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "site_id"), name="uma_confianca_por_pessoa_por_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="concessao",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "conquista"), name="uma_concessao_por_pessoa"
            ),
        ),
        migrations.AddConstraint(
            model_name="concessao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("validador_papel", "sistema"),
                    models.Q(("validador_id", ""), _negated=True),
                    _connector="OR",
                ),
                name="concessao_humana_diz_quem_validou",
            ),
        ),
        migrations.AddConstraint(
            model_name="aquisicao",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "item"), name="uma_aquisicao_por_item_por_pessoa"
            ),
        ),
        migrations.AddConstraint(
            model_name="progressodemissao",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "missao", "janela"),
                name="um_progresso_por_missao_por_janela",
            ),
        ),
        migrations.AddConstraint(
            model_name="sequencia",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "site_id"), name="uma_sequencia_por_pessoa_por_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="sequencia",
            constraint=models.CheckConstraint(
                condition=models.Q(("meta_dias__gte", 1), ("meta_dias__lte", 7)),
                name="meta_da_semana_cabe_numa_semana",
            ),
        ),
        migrations.AddConstraint(
            model_name="sequencia",
            constraint=models.CheckConstraint(
                condition=models.Q(("dias_ativos_na_semana__lte", 7)),
                name="a_semana_tem_sete_dias",
            ),
        ),
        migrations.AddConstraint(
            model_name="sequencia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recorde_semanas__gte", models.F("semanas_atuais"))
                ),
                name="o_recorde_nunca_e_menor_que_a_sequencia_atual",
            ),
        ),
        migrations.AddConstraint(
            model_name="usodeescudo",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "site_id", "semana"),
                name="um_escudo_por_semana_por_pessoa",
            ),
        ),
    ]
