"""A tabela da ajuda aceita: o fato que a medalha "Mao amiga" conta.

Acompanha o degrau 17 (a gamificacao passar a escutar o forum). E tabela propria,
e nao uma contagem do ledger de XP, por uma razao de produto: reconhecimento e
uma coisa, pagamento e outra. Contar pelo ledger amarraria a medalha a regra de
pontuacao estar LIGADA, e o mantenedor desligaria a regra por uma semana com a
medalha sumindo junto, sem ninguem entender por que.

A unicidade e pela MENSAGEM, nao pelo evento: marcar, desmarcar e remarcar a
mesma resposta conta UMA vez. Com a chave no event_id, dois amigos alternando a
marca fabricariam a medalha em minutos.
"""

# Generated by Django 5.1.4 on 2026-09-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamificacao", "0004_qualificador_de_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AjudaAceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("mensagem_id", models.CharField(max_length=64)),
                ("topico_id", models.CharField(max_length=64)),
                ("marcada_por", models.CharField(max_length=16)),
                (
                    "quem_marcou",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("occurred_at", models.DateTimeField()),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ajudas",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pessoa", "site_id", "mensagem_id"),
                        name="uma_ajuda_por_mensagem_por_pessoa",
                    )
                ],
            },
        ),
    ]
