"""A tabela que diz de QUEM e cada discussao do forum.

Fundacao do degrau 19 (a Galeria e os Destaques da semana). Ate aqui o evento
`forum.topico-criado.v1` chegava, virava XP e o `ator_id` dele era jogado fora.
Quem escolhe um trabalho para destacar ve a conversa pelo forum, que devolve o
titulo e o NOME DE EXIBICAO do autor, e nome de exibicao nao endereca carta
nenhuma. O id opaco de quem abriu so existe no evento.

Ela grava mesmo com a economia DESLIGADA, e essa e a razao de ser tabela propria
em vez de uma leitura do livro-razao de XP: hoje nenhuma regra de pontuacao esta
ligada nesta escola, e amarrar o registro ao credito faria o Destaque nascer
morto. E a mesma lei de `AjudaAceita`, na migracao 0005.

A unicidade e pelo par (site, topico), nao pelo evento: uma discussao e aberta
uma vez, por uma pessoa. Com a chave no `event_id`, uma reentrega do relay
mostraria a mesma conversa duas vezes na tela de escolher o destaque.

LIMITE HONESTO: so conversas abertas DEPOIS desta migracao aparecem aqui. As
anteriores esta celula nao conhece e nao ha como recuperar: o evento ja passou,
e com a economia desligada nem o livro-razao guardou rastro delas.
"""

# Generated by Django 5.1.4 on 2026-09-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamificacao", "0005_a_ajuda_aceita"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversaAberta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("topico_id", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversas_abertas",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_id", "topico_id"),
                        name="uma_conversa_por_topico_por_site",
                    )
                ],
            },
        ),
    ]
