"""Os dois reconhecimentos da Comunidade: a tabela que conta entregas, e as duas medalhas.

A PRIMEIRA OPERAÇÃO cria `EntregaAceita`, que é o que a medalha "Primeiro ciclo
concluído" conta. Ela grava com a economia DESLIGADA, pela mesma lei de
`AjudaAceita` (0005) e `ConversaAberta` (0006): reconhecer não depende de pagar.
E guarda o fato, nunca a aula: o invariante 3 da economia proíbe esta célula de
nomear conteúdo educacional.

A SEGUNDA OPERAÇÃO leva as duas medalhas ao banco de produção, e ela existe
porque o semeador NÃO roda no deploy: o contêiner só roda `migrate`, e
`semear_economia` só roda quando alguém dispara `semear-economia.yml`. Sem ela,
as duas medalhas existiriam no código e `/admin/economia/` continuaria sem elas.

Ela só alcança escola JÁ SEMEADA (que tem alguma conquista), e isso é o que a
faz não colidir com a suíte: o banco de teste nasce vazio, então nada é criado
nele. `get_or_create` pelo par (site, slug), sem atualizar o que existe: nome,
número ou interruptor que o mantenedor mudou continua como ele deixou. Nasce
tudo DESLIGADO; ligar é gesto dele, em `/admin/economia/`.

Os valores são os de `semear_economia.CONQUISTAS`, copiados e não importados:
migração é história, e importar o semeador faria esta migração mudar sozinha no
dia em que alguém editasse o semeador. Quem impede os dois de divergirem hoje é
`tests/test_reconhecimentos_da_comunidade.py`.

A volta atrás apaga só as duas medalhas que ninguém ganhou ainda. Concessão é
história de alguém, e a chave `PROTECT` recusaria apagar a medalha dela.
"""

# Generated by Django 5.1.4 on 2026-09-27 05:17

import django.db.models.deletion
from django.db import migrations, models


RECONHECIMENTOS = [
    {
        "slug": "primeiro-ciclo",
        "nome": "Primeiro ciclo concluído",
        "descricao": "A sua primeira aula concluída, com a entrega aceita pela escola.",
        "criterio": {"tipo": "entregas_aceitas", "alvo": 1},
    },
    {
        "slug": "primeira-ajuda",
        "nome": "Primeira ajuda aceita",
        "descricao": "Uma resposta sua destravou alguém no fórum pela primeira vez.",
        "criterio": {"tipo": "respostas_aceitas", "alvo": 1},
    },
]


def levar_os_reconhecimentos(apps, schema_editor):
    Conquista = apps.get_model("gamificacao", "ConquistaDefinicao")
    escolas = Conquista.objects.values_list("site_id", flat=True).distinct()
    for site_id in list(escolas):
        for medalha in RECONHECIMENTOS:
            Conquista.objects.get_or_create(
                site_id=site_id,
                slug=medalha["slug"],
                defaults={
                    "nome": medalha["nome"],
                    "descricao": medalha["descricao"],
                    "classe": "medalha",
                    "familia": "comunidade",
                    "criterio": medalha["criterio"],
                    "pontos": 0,
                    "cristais": 0,
                    "ativa": False,
                    "versao": 1,
                },
            )


def recolher_os_reconhecimentos(apps, schema_editor):
    Conquista = apps.get_model("gamificacao", "ConquistaDefinicao")
    Conquista.objects.filter(
        slug__in=[medalha["slug"] for medalha in RECONHECIMENTOS],
        concessoes__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("gamificacao", "0006_de_quem_e_cada_conversa"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntregaAceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("origem_event_id", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entregas_aceitas",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("origem_event_id",),
                        name="uma_entrega_aceita_por_evento",
                    )
                ],
            },
        ),
        migrations.RunPython(levar_os_reconhecimentos, recolher_os_reconhecimentos),
    ]
