"""O quadro de contribuições: as três tabelas do ciclo, e a medalha que o reconhece.

A PRIMEIRA PARTE cria o ciclo do dossiê da Comunidade (§6). `TarefaComunitaria`
é o que a escola publica, com os cinco campos que o membro lê antes de assumir.
`CompromissoDeContribuicao` é a pessoa assumindo, com um compromisso ativo por
pessoa e tarefa garantido no banco (a desistência libera), e a devolução que o
banco recusa sem motivo e orientação. `ContribuicaoAceita` é o fato, um por
compromisso, que a medalha conta: molde de `EntregaAceita` (0007).

A SEGUNDA PARTE leva a medalha "Primeira contribuição aceita" a toda escola JÁ
SEMEADA, pelo mesmo motivo e do mesmo jeito da 0007: o semeador não roda no
deploy. `get_or_create` pelo par (site, slug), sem pisar no que o mantenedor
editou; nasce desligada, e ligar é gesto dele em `/admin/economia/`. Os valores
são os de `semear_economia.CONQUISTAS`, copiados e não importados, e
`tests/test_quadro_de_contribuicoes.py` impede os dois de divergirem.

A volta atrás apaga só a medalha que ninguém ganhou ainda.
"""

# Generated by Django 5.1.4 on 2026-09-27 10:54

import django.db.models.deletion
from django.db import migrations, models

MEDALHA = {
    "slug": "primeira-contribuicao",
    "nome": "Primeira contribuição aceita",
    "descricao": (
        "Uma tarefa do quadro de contribuições, feita por você e aceita pela equipe."
    ),
    "criterio": {"tipo": "contribuicoes_aceitas", "alvo": 1},
}


def levar_a_medalha(apps, schema_editor):
    Conquista = apps.get_model("gamificacao", "ConquistaDefinicao")
    escolas = Conquista.objects.values_list("site_id", flat=True).distinct()
    for site_id in list(escolas):
        Conquista.objects.get_or_create(
            site_id=site_id,
            slug=MEDALHA["slug"],
            defaults={
                "nome": MEDALHA["nome"],
                "descricao": MEDALHA["descricao"],
                "classe": "medalha",
                "familia": "comunidade",
                "criterio": MEDALHA["criterio"],
                "pontos": 0,
                "cristais": 0,
                "ativa": False,
                "versao": 1,
            },
        )


def recolher_a_medalha(apps, schema_editor):
    Conquista = apps.get_model("gamificacao", "ConquistaDefinicao")
    Conquista.objects.filter(slug=MEDALHA["slug"], concessoes__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("gamificacao", "0007_reconhecimentos_da_comunidade"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompromissoDeContribuicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("assumida", "Assumida"),
                            ("enviada", "Enviada, em avaliação"),
                            ("devolvida", "Devolvida para ajuste"),
                            ("aceita", "Aceita"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="assumida",
                        max_length=9,
                    ),
                ),
                ("link", models.URLField(blank=True, max_length=500)),
                ("assumida_em", models.DateTimeField(auto_now_add=True)),
                ("enviada_em", models.DateTimeField(blank=True, null=True)),
                ("prazo_ate", models.DateTimeField(blank=True, null=True)),
                (
                    "motivo_da_devolucao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("link_nao_abre", "O link não abre para a escola"),
                            (
                                "fora_do_entregavel",
                                "Não é o que a tarefa pede para entregar",
                            ),
                            ("fora_do_criterio", "Ainda não cumpre um dos critérios"),
                        ],
                        default="",
                        max_length=18,
                    ),
                ),
                ("orientacao", models.TextField(blank=True)),
                (
                    "decidida_por",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("decidida_em", models.DateTimeField(blank=True, null=True)),
                ("cancelada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compromissos",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["prazo_ate", "assumida_em"],
            },
        ),
        migrations.CreateModel(
            name="ContribuicaoAceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("aceita_por", models.CharField(max_length=64)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "compromisso",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aceite",
                        to="gamificacao.compromissodecontribuicao",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribuicoes_aceitas",
                        to="gamificacao.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-criada_em"],
            },
        ),
        migrations.CreateModel(
            name="TarefaComunitaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("titulo", models.CharField(max_length=120)),
                ("o_que_entregar", models.TextField()),
                ("quem_pode", models.TextField()),
                ("criterios", models.JSONField(default=list)),
                ("responsavel_id", models.CharField(max_length=64)),
                ("responsavel_nome", models.CharField(max_length=120)),
                ("vagas", models.PositiveSmallIntegerField()),
                ("aberta", models.BooleanField(default=True)),
                ("autor_id", models.CharField(max_length=64)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "medalha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tarefas",
                        to="gamificacao.conquistadefinicao",
                    ),
                ),
            ],
            options={
                "ordering": ["-criada_em"],
            },
        ),
        migrations.AddField(
            model_name="compromissodecontribuicao",
            name="tarefa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compromissos",
                to="gamificacao.tarefacomunitaria",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarefacomunitaria",
            constraint=models.CheckConstraint(
                condition=models.Q(("vagas__gte", 1)),
                name="tarefa_tem_ao_menos_uma_vaga",
            ),
        ),
        migrations.AddIndex(
            model_name="compromissodecontribuicao",
            index=models.Index(
                fields=["site_id", "estado", "prazo_ate"],
                name="gamificacao_site_id_05f852_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="compromissodecontribuicao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "cancelada"), _negated=True),
                fields=("tarefa", "pessoa"),
                name="um_compromisso_ativo_por_tarefa",
            ),
        ),
        migrations.AddConstraint(
            model_name="compromissodecontribuicao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "devolvida"), _negated=True),
                    models.Q(
                        models.Q(("motivo_da_devolucao", ""), _negated=True),
                        models.Q(("orientacao", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="devolucao_diz_motivo_e_orientacao",
            ),
        ),
        migrations.RunPython(levar_a_medalha, recolher_a_medalha),
    ]
