"""O rastro de cada reconhecimento: a regra do dia, o estado e a história.

A PRIMEIRA PARTE dá à concessão a versão, a cópia e a frase do critério com que
foi dada, e o estado (concedida, corrigida ou revogada). Concessões anteriores
ficam com a regra vazia: a regra daquele dia não foi guardada, e preenchê-la
com a de hoje seria inventar o passado.

A SEGUNDA PARTE cria `HistoricoDaConcessao` e dá a cada concessão que já existe
a primeira linha dela (`concedida`), com a data, o validador e a origem que a
própria concessão guarda. Re-executável: só ganha linha quem ainda não tem.

A TERCEIRA PARTE são três gatilhos do PostgreSQL, no molde da 0002 de
`services/metricas`: o histórico não se edita nem se apaga, a concessão não se
apaga, e a versão de uma conquista sobe sozinha quando o critério muda, por
qualquer caminho (`save()`, `update()` ou SQL solto).

A volta atrás tira os gatilhos e a tabela; as colunas novas da concessão saem
com ela.
"""

# Generated by Django 5.1.4 on 2026-09-27 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

TRAVAS = """
CREATE OR REPLACE FUNCTION gamificacao_historico_imutavel() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'o historico da concessao e append-only: nada se edita nem se apaga. '
        'Revogar, corrigir e restaurar sao linhas novas (validacao.py).';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER historico_da_concessao_sem_update
    BEFORE UPDATE ON gamificacao_historicodaconcessao
    FOR EACH ROW EXECUTE FUNCTION gamificacao_historico_imutavel();

CREATE TRIGGER historico_da_concessao_sem_delete
    BEFORE DELETE ON gamificacao_historicodaconcessao
    FOR EACH ROW EXECUTE FUNCTION gamificacao_historico_imutavel();

CREATE OR REPLACE FUNCTION gamificacao_concessao_fica() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'uma concessao nunca e apagada: retirar e revogar, com motivo, '
        'e a linha fica para contar que existiu (validacao.revogar).';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER concessao_sem_delete
    BEFORE DELETE ON gamificacao_concessao
    FOR EACH ROW EXECUTE FUNCTION gamificacao_concessao_fica();

CREATE OR REPLACE FUNCTION gamificacao_versao_do_criterio() RETURNS trigger AS $$
BEGIN
    IF NEW.criterio IS DISTINCT FROM OLD.criterio AND NEW.versao = OLD.versao THEN
        NEW.versao := OLD.versao + 1;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER conquista_versao_sobe_com_o_criterio
    BEFORE UPDATE ON gamificacao_conquistadefinicao
    FOR EACH ROW EXECUTE FUNCTION gamificacao_versao_do_criterio();
"""

DESFAZ = """
DROP TRIGGER IF EXISTS conquista_versao_sobe_com_o_criterio
    ON gamificacao_conquistadefinicao;
DROP FUNCTION IF EXISTS gamificacao_versao_do_criterio();
DROP TRIGGER IF EXISTS concessao_sem_delete ON gamificacao_concessao;
DROP FUNCTION IF EXISTS gamificacao_concessao_fica();
DROP TRIGGER IF EXISTS historico_da_concessao_sem_delete
    ON gamificacao_historicodaconcessao;
DROP TRIGGER IF EXISTS historico_da_concessao_sem_update
    ON gamificacao_historicodaconcessao;
DROP FUNCTION IF EXISTS gamificacao_historico_imutavel();
"""


def dar_historia_ao_que_ja_existia(apps, schema_editor):
    Concessao = apps.get_model("gamificacao", "Concessao")
    Historico = apps.get_model("gamificacao", "HistoricoDaConcessao")
    for concessao in Concessao.objects.filter(historico__isnull=True):
        Historico.objects.create(
            concessao=concessao,
            site_id=concessao.site_id,
            gesto="concedida",
            estado_novo="concedida",
            quem_id=concessao.validador_id,
            origem_nova=concessao.origem_event_id,
            registrado_em=concessao.concedida_em,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("gamificacao", "0008_quadro_de_contribuicoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="concessao",
            name="criterio",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="concessao",
            name="criterio_em_texto",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="concessao",
            name="criterio_versao",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="concessao",
            name="estado",
            field=models.CharField(
                choices=[
                    ("concedida", "Concedida"),
                    ("corrigida", "Concedida, com registro corrigido"),
                    ("revogada", "Retirada pela equipe"),
                ],
                default="concedida",
                max_length=9,
            ),
        ),
        migrations.CreateModel(
            name="HistoricoDaConcessao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                (
                    "gesto",
                    models.CharField(
                        choices=[
                            ("concedida", "Concedida"),
                            ("corrigida", "Registro corrigido"),
                            ("revogada", "Retirada"),
                            ("restaurada", "Devolvida"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("concedida", "Concedida"),
                            ("corrigida", "Concedida, com registro corrigido"),
                            ("revogada", "Retirada pela equipe"),
                        ],
                        default="",
                        max_length=9,
                    ),
                ),
                (
                    "estado_novo",
                    models.CharField(
                        choices=[
                            ("concedida", "Concedida"),
                            ("corrigida", "Concedida, com registro corrigido"),
                            ("revogada", "Retirada pela equipe"),
                        ],
                        max_length=9,
                    ),
                ),
                ("quem_id", models.CharField(blank=True, default="", max_length=64)),
                ("motivo", models.TextField(blank=True, default="")),
                (
                    "origem_anterior",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "origem_nova",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "registrado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "concessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico",
                        to="gamificacao.concessao",
                    ),
                ),
            ],
            options={
                "ordering": ["registrado_em", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("gesto", "concedida"),
                            models.Q(
                                models.Q(("quem_id", ""), _negated=True),
                                models.Q(("motivo", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="gesto_da_equipe_diz_quem_e_por_que",
                    )
                ],
            },
        ),
        migrations.RunPython(dar_historia_ao_que_ja_existia, migrations.RunPython.noop),
        migrations.RunSQL(TRAVAS, DESFAZ),
    ]
