# Generated by Django 5.1.4 on 2026-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamificacao", "0009_rastro_do_reconhecimento"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="historicodaconcessao",
            name="gesto_da_equipe_diz_quem_e_por_que",
        ),
        migrations.AddConstraint(
            model_name="historicodaconcessao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gesto", "concedida"),
                    models.Q(("quem_id", ""), _negated=True),
                    _connector="OR",
                ),
                name="gesto_da_equipe_diz_quem",
            ),
        ),
    ]
