# Generated by Django 5.1.4 on 2026-10-09 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0011_desativar_marcos_forja_contribuicoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaDoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('alcancada', 'Alcançada'), ('revertida', 'Revertida')], max_length=10)),
                ('origem', models.CharField(max_length=20)),
                ('alcancada_em', models.DateTimeField()),
                ('event_id', models.CharField(blank=True, default='', max_length=64)),
                ('historico', models.BooleanField(default=False)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faixas', to='gamificacao.pessoa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pessoa', 'site_id', 'ordem'), name='uma_faixa_por_ordem_por_pessoa'), models.CheckConstraint(condition=models.Q(('ordem__gte', 1), ('ordem__lte', 13)), name='faixa_ordem_de_1_a_13')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoDaFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=10)),
                ('estado_novo', models.CharField(max_length=10)),
                ('origem', models.CharField(max_length=20)),
                ('event_id', models.CharField(blank=True, default='', max_length=64)),
                ('historico', models.BooleanField(default=False)),
                ('ocorrido_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_de_faixas', to='gamificacao.pessoa')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['pessoa', 'site_id', 'ordem'], name='gamificacao_pessoa__b7319f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RendimentoRealLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('event_id', models.CharField(max_length=64)),
                ('rendimento_id', models.CharField(max_length=64)),
                ('valor_cents', models.IntegerField()),
                ('ciclo', models.PositiveIntegerField(default=1)),
                ('ocorrido_em', models.DateTimeField()),
                ('historico', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendimentos_reais', to='gamificacao.pessoa')),
            ],
            options={
                'indexes': [models.Index(fields=['pessoa', 'site_id'], name='gamificacao_pessoa__395e41_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_id',), name='um_rendimento_real_por_evento'), models.CheckConstraint(condition=models.Q(('valor_cents', 0), _negated=True), name='rendimento_real_nao_zero')],
            },
        ),
    ]
