# Generated by Django 5.1.4 on 2026-10-09 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0012_faixas_do_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDaJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('acao', models.CharField(max_length=20)),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamificacao.pessoa')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JornadaPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('meta_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('proposito', models.CharField(blank=True, default='', max_length=280)),
                ('apoio', models.CharField(default='guiado', max_length=12)),
                ('declaracoes', models.JSONField(default=dict)),
                ('revisao', models.PositiveIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamificacao.pessoa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pessoa', 'site_id'), name='uma_jornada_pessoal_por_site')],
            },
        ),
        migrations.CreateModel(
            name='RecebimentoDeclarado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('chave', models.UUIDField(default=uuid.uuid4)),
                ('valor_cents', models.PositiveIntegerField()),
                ('origem', models.CharField(max_length=8)),
                ('recebido_em', models.DateField()),
                ('revisao', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamificacao.pessoa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pessoa', 'site_id', 'chave'), name='um_recebimento_declarado_por_chave')],
            },
        ),
    ]
