# Generated by Django 5.1.4 on 2026-10-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0013_jornada_pessoal_cinco_faixas'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadapessoal',
            name='celebracao_pendente',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recebimentodeclarado',
            name='analisada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recebimentodeclarado',
            name='analise_iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recebimentodeclarado',
            name='estado',
            field=models.CharField(default='pendente', max_length=14),
        ),
        migrations.AddField(
            model_name='recebimentodeclarado',
            name='leitura',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recebimentodeclarado',
            name='moeda_original',
            field=models.CharField(default='BRL', max_length=3),
        ),
        migrations.AddField(
            model_name='recebimentodeclarado',
            name='print_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recebimentodeclarado',
            name='print_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='recebimentodeclarado',
            name='tentar_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recebimentodeclarado',
            name='tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recebimentodeclarado',
            name='valor_original_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VersaoDoRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('revisao', models.PositiveIntegerField()),
                ('print_bytes', models.BinaryField()),
                ('print_sha256', models.CharField(max_length=64)),
                ('dados', models.JSONField(default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamificacao.pessoa')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamificacao.recebimentodeclarado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recebimento', 'revisao'), name='uma_versao_por_recebimento')],
            },
        ),
    ]
