# Generated by Django 5.1.4 on 2026-10-10 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0014_sete_faixas_prints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoDaJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('passo', models.PositiveSmallIntegerField()),
                ('nome', models.CharField(max_length=180)),
                ('conteudo', models.BinaryField()),
                ('tamanho', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamificacao.pessoa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pessoa', 'site_id', 'passo', 'sha256'), name='anexo_jornada_unico')],
            },
        ),
    ]
