# Generated by Django 5.0.9 on 2026-08-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                ("order_id", models.CharField(max_length=128, unique=True)),
                ("product_id", models.CharField(blank=True, default="", max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "ativa"),
                            ("suspensa", "suspensa"),
                            ("reembolsada", "reembolsada"),
                        ],
                        default="ativa",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="matriculas__email_213407_idx")
                ],
            },
        ),
    ]
