# Generated by Django 5.1.4 on 2026-08-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matriculas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="comprou_em",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matricula",
            name="decidido_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matricula",
            name="decidido_por",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="matricula",
            name="motivo_recusa",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="matricula",
            name="turma",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="matricula",
            name="whatsapp",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativa", "ativa"),
                    ("suspensa", "suspensa"),
                    ("reembolsada", "reembolsada"),
                    ("aguardando", "aguardando"),
                    ("recusada", "recusada"),
                ],
                default="ativa",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="matricula",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("aguardando", "recusada"))),
                fields=("site_id", "email"),
                name="matricula_unica_na_fila_por_site_e_email",
            ),
        ),
    ]
