# Generated by Django 5.1.4 on 2026-08-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matriculas", "0002_fila_de_liberacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matricula",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativa", "ativa"),
                    ("suspensa", "suspensa"),
                    ("reembolsada", "reembolsada"),
                    ("aguardando", "aguardando"),
                    ("recusada", "recusada"),
                    ("encerrada", "encerrada"),
                ],
                default="ativa",
                max_length=20,
            ),
        ),
    ]
