# Generated by Django 5.0.9 on 2026-09-21 03:58
#
# [ESTORNO] O par que liga a matricula ao pagamento que a pagou, para que
# `pagamento.estornado.v2` (que nao carrega `order_id`) encontre a pessoa cujo
# acesso fecha. Ver o comentario do par em `apps/matriculas/models.py`.
#
# SEM BACKFILL, e a ausencia dele e a decisao: as linhas de antes de 20/09/2026
# ficam com o par VAZIO porque ninguem sabe qual pagamento as pagou. O evento de
# aprovacao que as criou nao guardou a referencia do provedor em lugar nenhum, e
# inventar um valor aqui seria fabricar justamente o casamento pelo qual o
# estorno corta acesso. Elas ficam fora do alcance do estorno, que e a verdade.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matriculas", "0004_caixa_de_saida"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="provider",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="matricula",
            name="provider_reference_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddIndex(
            model_name="matricula",
            index=models.Index(
                fields=["provider", "provider_reference_id"],
                name="matriculas__provide_8e5b73_idx",
            ),
        ),
    ]
