# Generated by Django 5.0.9 on 2026-09-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matriculas", "0005_pagamento_que_pagou_a_matricula"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                ("provider", models.CharField(max_length=32)),
                ("provider_reference_id", models.CharField(max_length=128)),
                ("estornado", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name="pagamento",
            constraint=models.UniqueConstraint(
                fields=("site_id", "provider", "provider_reference_id"),
                name="pagamento_unico_por_site_provedor_referencia",
            ),
        ),
    ]
