# Generated by Django 5.1.4 on 2026-10-08 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100, unique=True)),
                ('horario', models.CharField(blank=True, max_length=200)),
                ('mensagem', models.TextField(default='Sua dúvida ficou registrada para a equipe. Você pode continuar por aqui; a resposta aparecerá nesta conversa.')),
                ('ia_ativa', models.BooleanField(default=True)),
                ('autorizacao_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atendimento_configuracao',
            },
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('modo', models.CharField(choices=[('assistido', 'Assistido'), ('base', 'Automático pela base'), ('encaminhamento', 'Automático com encaminhamento')], default='assistido', max_length=20)),
            ],
            options={
                'db_table': 'atendimento_assunto',
                'constraints': [models.UniqueConstraint(fields=('site_id', 'nome'), name='suporte_assunto_unico')],
            },
        ),
        migrations.CreateModel(
            name='Conhecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=100)),
                ('curso', models.CharField(blank=True, max_length=200)),
                ('pergunta', models.CharField(max_length=500)),
                ('resposta', models.TextField()),
                ('revisao', models.PositiveIntegerField(default=1)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.assunto')),
            ],
            options={
                'db_table': 'atendimento_conhecimento',
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=100)),
                ('pessoa_id', models.CharField(db_index=True, max_length=100)),
                ('nome', models.CharField(blank=True, max_length=160)),
                ('pagina', models.CharField(blank=True, max_length=500)),
                ('curso', models.CharField(blank=True, max_length=200)),
                ('aula', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(default='aguardando', max_length=20)),
                ('atendente_id', models.CharField(blank=True, max_length=100)),
                ('atendente_nome', models.CharField(blank=True, max_length=160)),
                ('encaminhada', models.BooleanField(default=False)),
                ('resolvida_robo', models.BooleanField(default=False)),
                ('avaliacao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rodada', models.PositiveIntegerField(default=1)),
                ('processar', models.BooleanField(default=False)),
                ('trabalhando_ate', models.DateTimeField(blank=True, null=True)),
                ('sugestao', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.assunto')),
            ],
            options={
                'db_table': 'atendimento_conversa',
                'ordering': ['-atualizada_em'],
            },
        ),
        migrations.CreateModel(
            name='PreviaForum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180)),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('area', models.CharField(blank=True, max_length=60)),
                ('topico_existente', models.PositiveIntegerField(blank=True, null=True)),
                ('publicada_url', models.CharField(blank=True, max_length=500)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.conversa')),
            ],
            options={
                'db_table': 'atendimento_previa_forum',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=160)),
                ('telefone', models.CharField(max_length=25)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'atendimento_responsavel',
                'constraints': [models.UniqueConstraint(fields=('site_id', 'telefone'), name='suporte_responsavel_unico')],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=160)),
                ('texto', models.TextField()),
                ('fontes', models.JSONField(blank=True, default=list)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='atendimento.conversa')),
            ],
            options={
                'db_table': 'atendimento_mensagem',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('conversa', 'referencia'), name='suporte_mensagem_unica')],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.PositiveIntegerField()),
                ('estado', models.CharField(default='pendente', max_length=30)),
                ('detalhe', models.CharField(blank=True, max_length=300)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.conversa')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.responsavel')),
            ],
            options={
                'db_table': 'atendimento_aviso',
                'constraints': [models.UniqueConstraint(fields=('conversa', 'responsavel', 'rodada'), name='suporte_aviso_unico')],
            },
        ),
    ]
