"""A Proposta e o Acordo: a negociacao por formulario ganha tabela e travas.

Degrau 2.12 da escada (TAR-134). Produto:
`docs/decisoes/PLANO-AREA-DE-NEGOCIACAO.md` paragrafo 4 (a Proposta e o Acordo),
paragrafo 7 (a protecao do aluno) e paragrafo 8 (os invariantes N1 a N8).

O QUE ENTRA, E POR QUE CADA COISA E DO BANCO E NAO DE UM `if`
--------------------------------------------------------------
1. **A tabela `Proposta`**, o formulario que vai e volta, com seis campos de
   negocio e nenhum a mais. `justificativa` e o unico campo de texto, e o
   limite dele e parametro, nao `max_length`: quem o faz valer e
   `negociacao.propor`. Um campo de texto novo aqui e o [INV-ENC-N1] caindo.

   Tres indices unicos, e cada um responde uma pergunta diferente:

   - `uma_proposta_viva_por_encomenda` (PARCIAL, so `pendente`): nunca duas
     propostas de pe para o mesmo projeto. As mortas se acumulam de proposito,
     porque sao elas o historico que a mediacao vai ler.
   - `uma_proposta_viva_por_aluno` (PARCIAL): o [INV-ENC-N6] somando as duas
     pistas. A coluna `aluno` e denormalizada justamente para isto:
     `UniqueConstraint` nao atravessa chave estrangeira (`armadilhas/274`).
   - `uma_rodada_por_lado_por_projeto` (SEM condicao): o [INV-ENC-N2] no banco.
     O mesmo lado nao escreve duas vezes a mesma rodada, nem por corrida, nem
     por uma tela futura com dois cliques. O TETO e parametro e mora em
     `negociacao.propor`; um `CHECK` com o numero dentro seria a constante
     magica que a lei paragrafo 3.8 proibe.

2. **A tabela `Acordo`**, que guarda o ATO e nao os numeros: quem aceitou,
   quando, e qual formulario virou lei. Os quatro numeros do combinado moram na
   `Proposta` aceita e, congelados, nas colunas `acordo_*` da `Encomenda`; uma
   terceira copia aqui seria a que diverge no primeiro dia de mediacao.
   `acordo_tem_quem_aceitou` e o paragrafo 7 em coluna: aceitacao sem autor nao
   e aceitacao.

3. **`uma_negociacao_viva_por_aluno` na `Encomenda`**, a metade do [INV-ENC-N6]
   que vale ANTES da primeira proposta. Entre o aceite e o primeiro formulario
   nao existe `Proposta` nenhuma, e sem esta linha o aluno acumularia
   negociacoes que nao pode cumprir.

4. **O gatilho `encomendas_o_acordo_e_pedra`**, o [INV-ENC-N3] no banco. Depois
   que `acordado_em` e preenchido, valor, prazo, entregaveis e correcoes nao
   mudam mais: o `UPDATE` e recusado venha ele de uma tela futura, de uma
   migracao de dados ou de um `psql` de madrugada. A UNICA excecao e o estado
   `em_mediacao`, e ela e o "so por mediacao, com autor e motivo registrados"
   do plano deixando de ser uma frase num documento. Quem guarda o autor e o
   motivo e a linha de `MudancaDeStatus` da transicao para `em_mediacao`, que
   ja e append-only por gatilho desde a `0001`.

   ERRCODE 23000 pela mesma razao da `0001`: sem ele o Postgres levanta o
   generico P0001, que o Django traduz em `ProgrammingError` em vez de
   `IntegrityError`, e quem escrever um `except` daqui a meses erraria a classe.

5. **As seis chaves de parametro da negociacao** (`rodadas_de_negociacao`,
   `validade_da_proposta`, `limite_da_justificativa` e os tres
   `piso_por_nivel.*`). O vocabulario e FECHADO no banco, entao chave nova e
   sempre uma troca de CHECK, e sempre um diff visivel. Os VALORES nao moram
   aqui: moram na semente, e os do piso nao existem de proposito (o numero sai
   do piloto de papel, paragrafo 9).

6. **As chaves estrangeiras compostas** (`armadilhas/274`), nas duas tabelas
   novas. Uma `ForeignKey` comum deixaria uma proposta de um site apontar para
   encomenda ou perfil de OUTRO, e `site_id` denormalizado sem esta trava e uma
   coluna que mente.

A MIGRACAO E REVERSIVEL: o `reverse_sql` derruba o gatilho e as quatro chaves
compostas, e todo o resto o Django desfaz sozinho.
"""

# Generated by Django 5.1.4 on 2026-09-07 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


O_ACORDO_E_PEDRA = """
CREATE OR REPLACE FUNCTION encomendas_o_acordo_e_pedra() RETURNS trigger AS $func$
BEGIN
    IF OLD.acordado_em IS NULL THEN
        RETURN NEW;
    END IF;
    IF NEW.status = 'em_mediacao' THEN
        RETURN NEW;
    END IF;
    IF NEW.acordo_valor_cents IS DISTINCT FROM OLD.acordo_valor_cents
        OR NEW.acordo_prazo_dias IS DISTINCT FROM OLD.acordo_prazo_dias
        OR NEW.acordo_entregaveis IS DISTINCT FROM OLD.acordo_entregaveis
        OR NEW.acordo_correcoes_inclusas IS DISTINCT FROM OLD.acordo_correcoes_inclusas
        OR NEW.acordado_em IS DISTINCT FROM OLD.acordado_em THEN
        RAISE EXCEPTION
            'encomendas: o acordo da encomenda % e pedra. Valor, prazo, entregaveis e correcoes so mudam por mediacao, com autor e motivo registrados.',
            OLD.id
            USING ERRCODE = '23000';
    END IF;
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;
"""

GATILHO_DO_ACORDO = """
CREATE TRIGGER encomendas_o_acordo_e_pedra
BEFORE UPDATE ON encomendas_encomenda
FOR EACH ROW EXECUTE FUNCTION encomendas_o_acordo_e_pedra();
"""

FKS_COMPOSTAS_DA_NEGOCIACAO = [
    """
    ALTER TABLE encomendas_proposta
        ADD CONSTRAINT proposta_e_encomenda_do_mesmo_site
        FOREIGN KEY (encomenda_id, site_id)
        REFERENCES encomendas_encomenda (id, site_id);
    """,
    """
    ALTER TABLE encomendas_proposta
        ADD CONSTRAINT proposta_e_aluno_do_mesmo_site
        FOREIGN KEY (aluno_id, site_id)
        REFERENCES encomendas_perfilprofissional (id, site_id);
    """,
    """
    ALTER TABLE encomendas_acordo
        ADD CONSTRAINT acordo_e_encomenda_do_mesmo_site
        FOREIGN KEY (encomenda_id, site_id)
        REFERENCES encomendas_encomenda (id, site_id);
    """,
    """
    ALTER TABLE encomendas_acordo
        ADD CONSTRAINT acordo_e_proposta_do_mesmo_site
        FOREIGN KEY (proposta_id, site_id)
        REFERENCES encomendas_proposta (id, site_id);
    """,
]

DESFAZER = [
    "DROP TRIGGER IF EXISTS encomendas_o_acordo_e_pedra ON encomendas_encomenda;",
    "DROP FUNCTION IF EXISTS encomendas_o_acordo_e_pedra();",
    "ALTER TABLE encomendas_acordo "
    "DROP CONSTRAINT IF EXISTS acordo_e_proposta_do_mesmo_site;",
    "ALTER TABLE encomendas_acordo "
    "DROP CONSTRAINT IF EXISTS acordo_e_encomenda_do_mesmo_site;",
    "ALTER TABLE encomendas_proposta "
    "DROP CONSTRAINT IF EXISTS proposta_e_aluno_do_mesmo_site;",
    "ALTER TABLE encomendas_proposta "
    "DROP CONSTRAINT IF EXISTS proposta_e_encomenda_do_mesmo_site;",
]


class Migration(migrations.Migration):

    dependencies = [
        ("encomendas", "0003_o_mural_a_segunda_pista"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acordo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                (
                    "de_quem",
                    models.CharField(
                        choices=[
                            ("aluno", "O aluno, que vai fazer o trabalho"),
                            ("cliente", "O cliente, que pediu o trabalho"),
                        ],
                        max_length=7,
                    ),
                ),
                ("aceito_por", models.CharField(blank=True, default="", max_length=64)),
                ("aceito_em", models.DateTimeField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "acordo",
                "verbose_name_plural": "acordos",
                "ordering": ["-aceito_em"],
            },
        ),
        migrations.CreateModel(
            name="Proposta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                (
                    "de_quem",
                    models.CharField(
                        choices=[
                            ("aluno", "O aluno, que vai fazer o trabalho"),
                            ("cliente", "O cliente, que pediu o trabalho"),
                        ],
                        max_length=7,
                    ),
                ),
                ("rodada", models.PositiveSmallIntegerField(default=1)),
                ("valor_cents", models.PositiveIntegerField()),
                ("prazo_dias", models.PositiveSmallIntegerField()),
                ("entregaveis", models.JSONField(blank=True, default=list)),
                ("correcoes_inclusas", models.PositiveSmallIntegerField()),
                ("justificativa", models.TextField(blank=True, default="")),
                ("valida_ate", models.DateTimeField()),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("pendente", "De pé, esperando o outro lado"),
                            ("aceita", "O outro lado aceitou, e nasceu o Acordo"),
                            (
                                "superada",
                                "O outro lado respondeu com uma contraproposta",
                            ),
                            (
                                "recusada",
                                "Recusada sem contraproposta: as rodadas acabaram",
                            ),
                            ("expirou", "A validade venceu sem resposta"),
                            ("retirada", "Quem propôs desistiu antes da resposta"),
                        ],
                        default="pendente",
                        max_length=8,
                    ),
                ),
                ("respondida_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "proposta",
                "verbose_name_plural": "propostas",
                "ordering": ["encomenda", "criada_em"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="parametro",
            name="chave_de_parametro_no_vocabulario_fechado",
        ),
        migrations.AddConstraint(
            model_name="encomenda",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "em_negociacao")),
                fields=("aluno",),
                name="uma_negociacao_viva_por_aluno",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametro",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "chave__in",
                        [
                            "amostragem_de_revisao",
                            "aprovacao_tacita",
                            "correcoes_incluidas",
                            "dias_de_revisao_no_prazo_prometido",
                            "encomendas_simultaneas_por_aluno",
                            "entregas_para_nivel_avancado",
                            "entregas_para_nivel_intermediario",
                            "extensao_horas",
                            "extensao_pedida_ate_horas_antes",
                            "extensoes_por_encomenda",
                            "horas_para_virar_aberta",
                            "janela_dos_passes",
                            "janela_fim",
                            "janela_inicio",
                            "janela_sem_abandono",
                            "limite_da_justificativa",
                            "meta_aprovacao_cliente_novo",
                            "passes_nao_pronto_para_aviso",
                            "passes_nao_pronto_para_reclassificar",
                            "pausa_por_segundo_abandono",
                            "piso_por_nivel.avancado",
                            "piso_por_nivel.iniciante",
                            "piso_por_nivel.intermediario",
                            "prazo_da_correcao",
                            "prazo_producao.personagem",
                            "prazo_producao.simples",
                            "prazo_producao.vestivel_veiculo",
                            "relogio_da_oferta",
                            "relogio_da_reserva_no_mural",
                            "repasse_apos_aprovacao",
                            "rodadas_de_negociacao",
                            "silencios_para_pausa",
                            "sla_do_revisor",
                            "validade_da_proposta",
                        ],
                    )
                ),
                name="chave_de_parametro_no_vocabulario_fechado",
            ),
        ),
        migrations.AddField(
            model_name="acordo",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acordos",
                to="encomendas.perfilprofissional",
            ),
        ),
        migrations.AddField(
            model_name="acordo",
            name="encomenda",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acordo",
                to="encomendas.encomenda",
            ),
        ),
        migrations.AddField(
            model_name="proposta",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="propostas",
                to="encomendas.perfilprofissional",
            ),
        ),
        migrations.AddField(
            model_name="proposta",
            name="encomenda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="propostas",
                to="encomendas.encomenda",
            ),
        ),
        migrations.AddField(
            model_name="acordo",
            name="proposta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acordo",
                to="encomendas.proposta",
            ),
        ),
        migrations.AddIndex(
            model_name="proposta",
            index=models.Index(
                fields=["resultado", "valida_ate"], name="enc_propostas_a_expirar"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposta",
            constraint=models.UniqueConstraint(
                fields=("id", "site_id"), name="uniq_proposta_id_com_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposta",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resultado", "pendente")),
                fields=("encomenda",),
                name="uma_proposta_viva_por_encomenda",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposta",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resultado", "pendente")),
                fields=("aluno",),
                name="uma_proposta_viva_por_aluno",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposta",
            constraint=models.UniqueConstraint(
                fields=("encomenda", "de_quem", "rodada"),
                name="uma_rodada_por_lado_por_projeto",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposta",
            constraint=models.CheckConstraint(
                condition=models.Q(("de_quem__in", ["aluno", "cliente"])),
                name="lado_da_proposta_no_vocabulario_fechado",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposta",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "resultado__in",
                        [
                            "pendente",
                            "aceita",
                            "superada",
                            "recusada",
                            "expirou",
                            "retirada",
                        ],
                    )
                ),
                name="resultado_de_proposta_no_vocabulario_fechado",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposta",
            constraint=models.CheckConstraint(
                condition=models.Q(("rodada__gte", 1)), name="rodada_comeca_em_um"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposta",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_cents__gt", 0)), name="proposta_tem_valor"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposta",
            constraint=models.CheckConstraint(
                condition=models.Q(("prazo_dias__gte", 1)), name="proposta_tem_prazo"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposta",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("respondida_em", None), ("resultado", "pendente")),
                    models.Q(
                        models.Q(("resultado", "pendente"), _negated=True),
                        ("respondida_em__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="proposta_respondida_tem_data",
            ),
        ),
        migrations.AddConstraint(
            model_name="acordo",
            constraint=models.CheckConstraint(
                condition=models.Q(("de_quem__in", ["aluno", "cliente"])),
                name="lado_do_acordo_no_vocabulario_fechado",
            ),
        ),
        migrations.AddConstraint(
            model_name="acordo",
            constraint=models.CheckConstraint(
                condition=models.Q(("aceito_por", ""), _negated=True),
                name="acordo_tem_quem_aceitou",
            ),
        ),
        migrations.RunSQL(
            sql=[*FKS_COMPOSTAS_DA_NEGOCIACAO, O_ACORDO_E_PEDRA, GATILHO_DO_ACORDO],
            reverse_sql=DESFAZER,
        ),
    ]
