# Generated by Django 5.1.4 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encomendas", "0005_a_janela_do_ritmo_da_espera"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="parametro",
            name="chave_de_parametro_no_vocabulario_fechado",
        ),
        migrations.AddConstraint(
            model_name="parametro",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "chave__in",
                        [
                            "amostragem_de_revisao",
                            "aprovacao_tacita",
                            "correcoes_incluidas",
                            "dias_de_revisao_no_prazo_prometido",
                            "encomendas_simultaneas_por_aluno",
                            "entregas_para_nivel_avancado",
                            "entregas_para_nivel_intermediario",
                            "extensao_horas",
                            "extensao_pedida_ate_horas_antes",
                            "extensoes_por_encomenda",
                            "horas_para_escalar_chamada_aberta",
                            "horas_para_virar_aberta",
                            "janela_do_ritmo_da_espera",
                            "janela_dos_passes",
                            "janela_fim",
                            "janela_inicio",
                            "janela_sem_abandono",
                            "limite_da_justificativa",
                            "meta_aprovacao_cliente_novo",
                            "passes_nao_pronto_para_aviso",
                            "passes_nao_pronto_para_reclassificar",
                            "pausa_por_segundo_abandono",
                            "piso_por_nivel.avancado",
                            "piso_por_nivel.iniciante",
                            "piso_por_nivel.intermediario",
                            "prazo_da_correcao",
                            "prazo_producao.personagem",
                            "prazo_producao.simples",
                            "prazo_producao.vestivel_veiculo",
                            "relogio_da_oferta",
                            "relogio_da_reserva_no_mural",
                            "repasse_apos_aprovacao",
                            "rodadas_de_negociacao",
                            "silencios_para_pausa",
                            "sla_do_revisor",
                            "validade_da_proposta",
                        ],
                    )
                ),
                name="chave_de_parametro_no_vocabulario_fechado",
            ),
        ),
    ]
