# Generated by Django 5.1.4 on 2026-10-04 21:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0008_motivo_opcional_do_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaMarketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('versao', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aprovada_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacaoMarketplaceCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('cliente_id', models.CharField(max_length=64)),
                ('ativa', models.BooleanField(default=False)),
                ('autorizada_por', models.CharField(blank=True, default='', max_length=64)),
                ('autorizada_em', models.DateTimeField(blank=True, null=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'cliente_id'), name='mp_cliente_site_unico')],
            },
        ),
        migrations.CreateModel(
            name='FaseMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('alunos_liberados', models.BooleanField(default=False)),
                ('clientes_liberados', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id',), name='mp_fase_site_unica')],
            },
        ),
        migrations.CreateModel(
            name='PedidoMarketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('cliente_id', models.CharField(max_length=64)),
                ('cartao', models.CharField(blank=True, choices=[('item_simples', 'Item simples'), ('vestivel_ou_veiculo', 'Vestível ou veículo'), ('personagem', 'Personagem')], max_length=20)),
                ('nivel', models.CharField(blank=True, choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=14)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('briefing', models.JSONField(blank=True, default=dict)),
                ('valor_cents', models.PositiveIntegerField(default=0)),
                ('moeda', models.CharField(default='BRL', max_length=3)),
                ('prazo_quantidade', models.PositiveSmallIntegerField(default=0)),
                ('prazo_unidade', models.CharField(blank=True, choices=[('dias_corridos', 'Dias corridos'), ('dias_uteis', 'Dias úteis')], max_length=14)),
                ('ajustes_inclusos', models.PositiveSmallIntegerField(default=0)),
                ('ambiente', models.CharField(default='sandbox', max_length=16)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_pagamento', 'Aguardando pagamento'), ('na_fila', 'Na fila'), ('oferecido', 'Oferecido'), ('em_producao', 'Em produção'), ('entregue', 'Entregue'), ('em_ajuste', 'Em ajuste'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('mediacao', 'Mediação')], default='rascunho', max_length=24)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('pagamento_referencia', models.CharField(blank=True, default='', max_length=160)),
                ('pagamento_confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('producao_iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('producao_prazo_ate', models.DateTimeField(blank=True, null=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_marketplace', to='encomendas.perfilprofissional')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaMarketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('versao_pedido', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('passou', 'Passou'), ('expirou', 'Expirou'), ('cancelada', 'Cancelada')], default='pendente', max_length=12)),
                ('motivo', models.CharField(blank=True, max_length=160)),
                ('oferecida_em', models.DateTimeField()),
                ('expira_em', models.DateTimeField()),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_marketplace', to='encomendas.perfilprofissional')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='encomendas.pedidomarketplace')),
            ],
        ),
        migrations.CreateModel(
            name='MensagemMarketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('ator_id', models.CharField(max_length=64)),
                ('papel', models.CharField(max_length=12)),
                ('texto', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encomendas.entregamarketplace')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='encomendas.pedidomarketplace')),
            ],
        ),
        migrations.CreateModel(
            name='EventoMarketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('chave', models.CharField(max_length=160, unique=True)),
                ('tipo', models.CharField(max_length=80)),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='encomendas.pedidomarketplace')),
            ],
        ),
        migrations.AddField(
            model_name='entregamarketplace',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='encomendas.pedidomarketplace'),
        ),
        migrations.CreateModel(
            name='ArquivoMarketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('ator_id', models.CharField(max_length=64)),
                ('papel', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=255)),
                ('chave', models.CharField(max_length=400)),
                ('legenda', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='encomendas.entregamarketplace')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='encomendas.pedidomarketplace')),
            ],
        ),
        migrations.CreateModel(
            name='AjusteMarketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('texto', models.TextField()),
                ('pedido_em', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encomendas.entregamarketplace')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='encomendas.pedidomarketplace')),
            ],
        ),
        migrations.CreateModel(
            name='AcordoMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('versao_pedido', models.PositiveIntegerField()),
                ('termos', models.JSONField(default=dict)),
                ('aceito_em', models.DateTimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encomendas.perfilprofissional')),
                ('oferta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='encomendas.ofertamarketplace')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acordo', to='encomendas.pedidomarketplace')),
            ],
        ),
        migrations.CreateModel(
            name='RecebivelMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_processamento', 'Em processamento'), ('recebido', 'Recebido'), ('excecao', 'Exceção')], default='pendente', max_length=20)),
                ('valor_liquido_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia_repasse', models.CharField(blank=True, max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encomendas.perfilprofissional')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recebivel', to='encomendas.pedidomarketplace')),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacaoMarketplaceAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('ativa', models.BooleanField(default=False)),
                ('autorizada_por', models.CharField(blank=True, default='', max_length=64)),
                ('autorizada_em', models.DateTimeField(blank=True, null=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encomendas.pessoa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'pessoa'), name='mp_aluno_site_unico')],
            },
        ),
        migrations.AddIndex(
            model_name='pedidomarketplace',
            index=models.Index(fields=['site_id', 'status', 'criado_em'], name='mp_pedidos_por_estado'),
        ),
        migrations.AddIndex(
            model_name='pedidomarketplace',
            index=models.Index(fields=['site_id', 'cliente_id'], name='mp_pedidos_por_cliente'),
        ),
        migrations.AddIndex(
            model_name='ofertamarketplace',
            index=models.Index(fields=['site_id', 'status', 'expira_em'], name='mp_ofertas_a_expirar'),
        ),
        migrations.AddConstraint(
            model_name='ofertamarketplace',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pendente')), fields=('pedido',), name='mp_pedido_oferta_pendente'),
        ),
        migrations.AddConstraint(
            model_name='ofertamarketplace',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pendente')), fields=('aluno',), name='mp_aluno_oferta_pendente'),
        ),
        migrations.AddConstraint(
            model_name='ofertamarketplace',
            constraint=models.UniqueConstraint(fields=('pedido', 'aluno'), name='mp_aluno_ve_pedido_uma_vez'),
        ),
        migrations.AddConstraint(
            model_name='entregamarketplace',
            constraint=models.UniqueConstraint(fields=('pedido', 'versao'), name='mp_versao_entrega_unica'),
        ),
        migrations.AddConstraint(
            model_name='arquivomarketplace',
            constraint=models.UniqueConstraint(fields=('site_id', 'chave'), name='mp_arquivo_chave_unica'),
        ),
        migrations.AddConstraint(
            model_name='ajustemarketplace',
            constraint=models.UniqueConstraint(fields=('entrega',), name='mp_ajuste_por_entrega'),
        ),
    ]
