# Generated by Django 5.1.4 on 2026-10-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0009_entregamarketplace_autorizacaomarketplacecliente_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedidomarketplace',
            constraint=models.UniqueConstraint(condition=models.Q(('pagamento_referencia', ''), _negated=True), fields=('pagamento_referencia',), name='mp_pagamento_referencia_unica'),
        ),
    ]
