# Generated by Django 5.1.4 on 2026-10-04 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0010_pedidomarketplace_mp_pagamento_referencia_unica'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('event_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event', models.CharField(max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('envelope_extra', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='encomendas.eventomarketplace')),
            ],
            options={
                'indexes': [models.Index(fields=['published_at'], name='mp_outbox_pendente')],
            },
        ),
    ]
