# Generated by Django 5.1.4 on 2026-10-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0011_outboxmarketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivomarketplace',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='arquivomarketplace',
            name='tamanho_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivomarketplace',
            name='tipo_mime',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='arquivomarketplace',
            name='versao_exportacao',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
