# Generated by Django 5.1.4 on 2026-10-06 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0012_arquivomarketplace_sha256_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecargaMarketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('cliente_id', models.CharField(max_length=64)),
                ('valor_cents', models.PositiveIntegerField()),
                ('charge_id', models.CharField(blank=True, max_length=160)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'cliente_id', '-criada_em'], name='mp_recarga_cliente')],
            },
        ),
    ]
