# Generated by Django 5.1.4 on 2026-10-06 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0012_arquivomarketplace_sha256_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacaoSandbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('pessoa_id', models.CharField(db_index=True, max_length=64)),
                ('termos', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('em_producao', 'Em produção'), ('entregue', 'Entregue'), ('em_ajuste', 'Em ajuste'), ('aprovado', 'Aprovado')], default='em_producao', max_length=20)),
                ('aceite_em', models.DateTimeField()),
                ('prazo_ate', models.DateTimeField()),
                ('atraso_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'encomendas_participacaosandbox',
            },
        ),
        migrations.CreateModel(
            name='MensagemSandbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ator_id', models.CharField(max_length=64)),
                ('papel', models.CharField(choices=[('aluno', 'Aluno'), ('equipe', 'Equipe'), ('ia', 'IA')], max_length=8)),
                ('texto', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='encomendas.participacaosandbox')),
            ],
            options={
                'db_table': 'encomendas_mensagemsandbox',
            },
        ),
        migrations.CreateModel(
            name='EntregaSandbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versao', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aprovada_em', models.DateTimeField(blank=True, null=True)),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='encomendas.participacaosandbox')),
            ],
            options={
                'db_table': 'encomendas_entregasandbox',
            },
        ),
        migrations.CreateModel(
            name='ArquivoSandbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('chave', models.CharField(max_length=400)),
                ('sha256', models.CharField(max_length=64)),
                ('tamanho', models.PositiveBigIntegerField()),
                ('mime', models.CharField(max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='encomendas.entregasandbox')),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='encomendas.participacaosandbox')),
            ],
            options={
                'db_table': 'encomendas_arquivosandbox',
            },
        ),
        migrations.CreateModel(
            name='AjusteSandbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('autor_id', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='encomendas.entregasandbox')),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='encomendas.participacaosandbox')),
            ],
            options={
                'db_table': 'encomendas_ajustesandbox',
            },
        ),
        migrations.CreateModel(
            name='ProjetoSandbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('briefing', models.TextField()),
                ('referencias', models.JSONField(default=list)),
                ('entregaveis', models.JSONField(default=list)),
                ('criterios', models.TextField()),
                ('prazo_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('ajustes_previstos', models.PositiveIntegerField(blank=True, null=True)),
                ('recompensa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'encomendas_projetosandbox',
                'constraints': [models.UniqueConstraint(fields=('site_id', 'slug'), name='sb_projeto_slug_site'), models.CheckConstraint(condition=models.Q(('recompensa__gte', 0), ('recompensa__isnull', True), _connector='OR'), name='sb_recompensa_nao_negativa')],
            },
        ),
        migrations.AddField(
            model_name='participacaosandbox',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to='encomendas.projetosandbox'),
        ),
        migrations.CreateModel(
            name='MovimentoMeshcoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pessoa_id', models.CharField(db_index=True, max_length=64)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aprovador_id', models.CharField(max_length=64)),
                ('participacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='movimento_meshcoin', to='encomendas.participacaosandbox')),
            ],
            options={
                'db_table': 'encomendas_movimentomeshcoin',
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='sb_movimento_nao_negativo')],
            },
        ),
        migrations.AddConstraint(
            model_name='entregasandbox',
            constraint=models.UniqueConstraint(fields=('participacao', 'versao'), name='sb_entrega_versao_unica'),
        ),
        migrations.AddConstraint(
            model_name='arquivosandbox',
            constraint=models.UniqueConstraint(fields=('participacao', 'chave'), name='sb_arquivo_chave_unica'),
        ),
        migrations.AddConstraint(
            model_name='participacaosandbox',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['em_producao', 'entregue', 'em_ajuste'])), fields=('site_id', 'pessoa_id'), name='sb_uma_participacao_ativa'),
        ),
    ]
