# Generated by Django 5.1.4 on 2026-10-06 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0013_recarga_marketplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaqueMarketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('aluno_id', models.CharField(max_length=64)),
                ('valor_cents', models.PositiveIntegerField()),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_no_ledger', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'aluno_id', '-solicitado_em'], name='mp_saque_aluno')],
            },
        ),
    ]
