# Generated by Django 5.1.4 on 2026-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0015_evento_recarga_sem_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebivelmarketplace',
            name='creditado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
