# Generated by Django 5.1.4 on 2026-10-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0016_saque_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomarketplace',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='encomendas.pedidomarketplace'),
        ),
    ]
