# Generated by Django 5.1.4 on 2026-10-08 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0020_recompensa_experiencia_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoConversaFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encomendas.pedidomarketplace')),
                ('pergunta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='caso_fila', to='encomendas.mensagemmarketplace')),
                ('resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_resolvidos', to='encomendas.mensagemmarketplace')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=40)),
                ('nome', models.CharField(max_length=120)),
                ('pessoa_id', models.CharField(blank=True, max_length=64)),
                ('ativo', models.BooleanField(default=True)),
                ('creditos_cents', models.BigIntegerField(default=500000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'slug'), name='fila_cliente_site_slug'), models.UniqueConstraint(condition=models.Q(('pessoa_id', ''), _negated=True), fields=('site_id', 'pessoa_id'), name='fila_cliente_conta_unica'), models.CheckConstraint(condition=models.Q(('creditos_cents__gte', 0)), name='fila_creditos_nao_negativos')],
            },
        ),
        migrations.CreateModel(
            name='MovimentoOrcamentoFila',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(max_length=24)),
                ('valor_cents', models.BigIntegerField()),
                ('saldo_apos_cents', models.BigIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='encomendas.clientefila')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encomendas.pedidomarketplace')),
            ],
        ),
        migrations.CreateModel(
            name='OrientacaoPrivadaFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_id', models.CharField(db_index=True, max_length=64)),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientacoes_privadas', to='encomendas.pedidomarketplace')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoClienteFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservado_cents', models.PositiveIntegerField(default=0)),
                ('consumido_em', models.DateTimeField(blank=True, null=True)),
                ('charge_id', models.CharField(blank=True, max_length=160)),
                ('pagamento_real_confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('referencia_provedor', models.CharField(blank=True, max_length=160)),
                ('termos_aceitos', models.JSONField(default=dict)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='encomendas.clientefila')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fila_cliente', to='encomendas.pedidomarketplace')),
            ],
        ),
    ]
