# Generated by Django 5.1.4 on 2026-10-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0021_clientes_fila_real'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casoconversafila',
            table='encomendas_casoconversafila',
        ),
        migrations.AlterModelTable(
            name='clientefila',
            table='encomendas_clientefila',
        ),
        migrations.AlterModelTable(
            name='movimentoorcamentofila',
            table='encomendas_movimentoorcamentofila',
        ),
        migrations.AlterModelTable(
            name='orientacaoprivadafila',
            table='encomendas_orientacaoprivadafila',
        ),
        migrations.AlterModelTable(
            name='pedidoclientefila',
            table='encomendas_pedidoclientefila',
        ),
    ]
