# Generated by Django 5.1.4 on 2026-10-08 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0022_tabelas_clientes_fila'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaqueManualFila',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('chave_idempotencia', models.UUIDField(unique=True)),
                ('valor_cents', models.PositiveBigIntegerField()),
                ('chave_pix_cifrada', models.TextField()),
                ('nome_recebedor', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('pago', 'Pago')], default='solicitado', max_length=16)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('referencia_pix', models.CharField(blank=True, max_length=160)),
                ('pagador_nome', models.CharField(blank=True, max_length=160)),
                ('pagador_cpf_cifrado', models.TextField(blank=True)),
                ('pagador_email', models.EmailField(blank=True, max_length=254)),
                ('confirmado_por', models.CharField(blank=True, max_length=64)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saques_manuais_fila', to='encomendas.perfilprofissional')),
            ],
            options={
                'db_table': 'encomendas_saquemanualfila',
            },
        ),
        migrations.CreateModel(
            name='ParcelaSaqueFila',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_cents', models.PositiveBigIntegerField()),
                ('recebivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_saques_fila', to='encomendas.recebivelmarketplace')),
                ('saque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='encomendas.saquemanualfila')),
            ],
            options={
                'db_table': 'encomendas_parcelasaquefila',
            },
        ),
        migrations.AddConstraint(
            model_name='saquemanualfila',
            constraint=models.CheckConstraint(condition=models.Q(('valor_cents__gte', 5000)), name='fila_saque_minimo_50'),
        ),
        migrations.AddConstraint(
            model_name='saquemanualfila',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_pix', ''), _negated=True), fields=('referencia_pix',), name='fila_pix_saque_referencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='parcelasaquefila',
            constraint=models.UniqueConstraint(fields=('saque', 'recebivel'), name='fila_saque_recebivel_unico'),
        ),
        migrations.AddConstraint(
            model_name='parcelasaquefila',
            constraint=models.CheckConstraint(condition=models.Q(('valor_cents__gt', 0)), name='fila_parcela_positiva'),
        ),
    ]
