# Generated by Django 5.0.14 on 2026-08-18 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Chave interna para seed/cadastro idempotente — não faz parte do contrato.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price_cents", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
