# Generated by Django 5.1.4 on 2026-10-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetornoDeModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=200, unique=True)),
                ('estado', models.CharField(max_length=20)),
                ('erro_codigo', models.CharField(blank=True, max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvioDeModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('chave_idempotencia', models.CharField(max_length=200)),
                ('origem', models.CharField(max_length=40)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('modelo_nome', models.CharField(max_length=512)),
                ('idioma', models.CharField(max_length=20)),
                ('destinatario', models.CharField(blank=True, max_length=20)),
                ('variaveis', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('reservado', 'reservado'), ('aceito', 'aceito'), ('enviado', 'enviado'), ('entregue', 'entregue'), ('lido', 'lido'), ('falhou', 'falhou'), ('desconhecido', 'desconhecido')], default='reservado', max_length=20)),
                ('provider_id', models.CharField(blank=True, max_length=200)),
                ('erro', models.CharField(blank=True, max_length=300)),
                ('erro_codigo', models.CharField(blank=True, max_length=20)),
                ('retomavel', models.BooleanField(default=False)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', '-id'], name='wa_envio_modelo_site_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'chave_idempotencia'), name='uniq_wa_envio_modelo_chave'), models.UniqueConstraint(condition=models.Q(('provider_id', ''), _negated=True), fields=('provider_id',), name='uniq_wa_envio_modelo_provider')],
            },
        ),
        migrations.CreateModel(
            name='ModeloWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.CharField(max_length=64)),
                ('modelo_id', models.CharField(blank=True, max_length=64)),
                ('nome', models.CharField(max_length=512)),
                ('idioma', models.CharField(max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('aprovado', 'aprovado'), ('pendente', 'pendente'), ('rejeitado', 'rejeitado'), ('pausado', 'pausado'), ('desativado', 'desativado'), ('outro', 'outro')], default='outro', max_length=20)),
                ('estado_no_provedor', models.CharField(blank=True, max_length=40)),
                ('formato_parametros', models.CharField(default='positional', max_length=12)),
                ('corpo', models.TextField(blank=True)),
                ('componentes', models.JSONField(blank=True, default=list)),
                ('variaveis', models.JSONField(blank=True, default=list)),
                ('mapeamento', models.JSONField(blank=True, default=dict)),
                ('suportado', models.BooleanField(default=True)),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('presente_no_provedor', models.BooleanField(default=True)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conta', 'nome', 'idioma'), name='uniq_wa_modelo_conta_nome_idioma')],
            },
        ),
    ]
