# Generated by Django 5.1.4 on 2026-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventoProcessado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
