# Generated by Django 5.1.4 on 2026-08-24 10:25

import apps.sugestoes.models
import django.db.models.deletion
from django.db import migrations, models

# [INV-SUG02] O degrau final do append-only de HistoricoStatus (Lei 1: empurrar
# a regra escada acima até a impossibilidade física). O guarda em Python
# (`HistoricoStatus.save`/`delete` + `AppendOnlyQuerySet`) protege quem passa
# pelo ORM; este trigger protege contra `cursor.execute` cru, `psql`, o
# collector de CASCADE do Django e qualquer código futuro que não conheça a
# classe. Sem ele, "append-only" seria uma convenção — com ele, é o banco.
#
# `RunSQL` recebe uma LISTA de propósito, e não uma string única: string única
# passa por `prepare_sql_script`, que fatia o SQL em `;` usando o `sqlparse`. O
# `sqlparse` 0.6.0 entende corpo dollar-quoted (`$$ ... ; ... $$`) e devolve o
# CREATE FUNCTION inteiro — conferido — mas isso é comportamento de uma
# dependência transitiva do Django, não contrato do Django. Com lista, cada
# elemento vai direto ao cursor e o fatiamento nunca acontece.
CRIAR_FUNCAO = """
CREATE OR REPLACE FUNCTION sugestoes_historico_append_only()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'INV-SUG02: HistoricoStatus e append-only; UPDATE e DELETE sao recusados pelo banco';
END;
$$ LANGUAGE plpgsql;
"""

CRIAR_TRIGGER = """
CREATE TRIGGER sugestoes_historico_append_only
BEFORE UPDATE OR DELETE ON sugestoes_historicostatus
FOR EACH ROW EXECUTE FUNCTION sugestoes_historico_append_only();
"""

APAGAR_TRIGGER = (
    "DROP TRIGGER IF EXISTS sugestoes_historico_append_only "
    "ON sugestoes_historicostatus;"
)
APAGAR_FUNCAO = "DROP FUNCTION IF EXISTS sugestoes_historico_append_only();"


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Identidade",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.sugestoes.models.cunhar_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("provedor", models.CharField(default="google", max_length=20)),
                ("nome_exibido", models.CharField(blank=True, max_length=120)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quadro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                ("produto_id", models.CharField(blank=True, max_length=64, null=True)),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site_id"], name="sugestoes_q_site_id_ab485c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("nome", models.CharField(max_length=80)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "quadro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="sugestoes.quadro",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "slug"],
            },
        ),
        migrations.CreateModel(
            name="Sugestao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=140)),
                ("problema", models.TextField()),
                ("solucao_proposta", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_analise", "Em análise"),
                            ("planejado", "Planejado"),
                            ("em_desenvolvimento", "Em desenvolvimento"),
                            ("implementado", "Implementado"),
                            ("nao_planejado", "Não planejado"),
                            ("mesclado", "Mesclado"),
                        ],
                        default="em_analise",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sugestoes",
                        to="sugestoes.identidade",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sugestoes",
                        to="sugestoes.categoria",
                    ),
                ),
                (
                    "quadro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sugestoes",
                        to="sugestoes.quadro",
                    ),
                ),
                (
                    "sugestao_canonica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mescladas",
                        to="sugestoes.sugestao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("em_analise", "Em análise"),
                            ("planejado", "Planejado"),
                            ("em_desenvolvimento", "Em desenvolvimento"),
                            ("implementado", "Implementado"),
                            ("nao_planejado", "Não planejado"),
                            ("mesclado", "Mesclado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        choices=[
                            ("em_analise", "Em análise"),
                            ("planejado", "Planejado"),
                            ("em_desenvolvimento", "Em desenvolvimento"),
                            ("implementado", "Implementado"),
                            ("nao_planejado", "Não planejado"),
                            ("mesclado", "Mesclado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nota", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alteracoes_de_status",
                        to="sugestoes.identidade",
                    ),
                ),
                (
                    "sugestao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico",
                        to="sugestoes.sugestao",
                    ),
                ),
            ],
            options={
                "ordering": ["criado_em", "id"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comentarios",
                        to="sugestoes.identidade",
                    ),
                ),
                (
                    "sugestao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="sugestoes.sugestao",
                    ),
                ),
            ],
            options={
                "ordering": ["criado_em"],
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoInterna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impacto_educacional", models.PositiveSmallIntegerField(default=0)),
                ("impacto_comercial", models.PositiveSmallIntegerField(default=0)),
                ("esforco_tecnico", models.PositiveSmallIntegerField(default=0)),
                ("notas", models.TextField(blank=True)),
                ("decisao_produto", models.TextField(blank=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "avaliado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliacoes",
                        to="sugestoes.identidade",
                    ),
                ),
                (
                    "sugestao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="sugestoes.sugestao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votos",
                        to="sugestoes.identidade",
                    ),
                ),
                (
                    "sugestao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="sugestoes.sugestao",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="categoria",
            constraint=models.UniqueConstraint(
                fields=("quadro", "slug"), name="categoria_quadro_slug_unica"
            ),
        ),
        migrations.AddIndex(
            model_name="sugestao",
            index=models.Index(
                fields=["quadro", "status"], name="sugestoes_s_quadro__810cfe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voto",
            constraint=models.UniqueConstraint(
                fields=("sugestao", "autor"), name="voto_unico_por_ator_e_sugestao"
            ),
        ),
        migrations.RunSQL(
            sql=[CRIAR_FUNCAO, CRIAR_TRIGGER],
            reverse_sql=[APAGAR_TRIGGER, APAGAR_FUNCAO],
        ),
    ]
