# Generated by Django 5.1.4 on 2026-08-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sugestoes", "0002_outboxevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("em_analise", "Em análise"),
                            ("planejado", "Planejado"),
                            ("em_desenvolvimento", "Em desenvolvimento"),
                            ("implementado", "Implementado"),
                            ("nao_planejado", "Não planejado"),
                            ("mesclado", "Mesclado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        choices=[
                            ("em_analise", "Em análise"),
                            ("planejado", "Planejado"),
                            ("em_desenvolvimento", "Em desenvolvimento"),
                            ("implementado", "Implementado"),
                            ("nao_planejado", "Não planejado"),
                            ("mesclado", "Mesclado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nota", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("lido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avisos",
                        to="sugestoes.identidade",
                    ),
                ),
                (
                    "sugestao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avisos",
                        to="sugestoes.sugestao",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
                "indexes": [
                    models.Index(
                        fields=["destinatario", "lido_em"],
                        name="sugestoes_a_destina_ed6d19_idx",
                    )
                ],
            },
        ),
    ]
