# Generated by Django 5.1.4 on 2026-08-25 18:58
#
# EVO-40 — o corredor do ChangeSpec, com os DOIS triggers que o sustentam.
#
# 1. `sugestoes_changespec_append_only` — o terceiro degrau da imutabilidade do
#    registro, na forma exata do trigger que a `0001_initial` criou para o
#    `HistoricoStatus`. Sem ele, "append-only" seria convenção: o collector do
#    CASCADE do Django e qualquer `UPDATE` cru passariam por baixo dos degraus
#    Python (`armadilhas/079`).
#
# 2. `sugestoes_exige_changespec` — **a trava**, no degrau mais fundo que ela
#    alcança. A `ESPECIFICACAO-CELULA.md` §8 pede validação "no `save()` ou no
#    serializer"; a Escada da Imposição desta casa manda empurrar a regra até
#    onde ela fisicamente puder ir, e aqui ela vai até o Postgres — porque as
#    duas tabelas moram no MESMO banco e o `EXISTS` é uma consulta local.
#    Consequência prática: nem `QuerySet.update(status=...)`, nem `psql`, nem
#    um `manage.py` escrito daqui a seis meses movem uma sugestão de
#    `planejado` para `em_desenvolvimento` sem o corredor existir primeiro.
#
# `BEFORE UPDATE OF status`: o trigger nem é chamado quando a coluna não está
# na lista do UPDATE. O caminho normal desta célula é
# `save(update_fields=["status"])`, que atualiza só ela.
#
# `RunSQL` recebe uma LISTA de propósito, e não uma string única — string única
# passa por `prepare_sql_script`, que fatia o SQL em `;` com o `sqlparse`. Com
# lista, cada elemento vai direto ao cursor e o fatiamento nunca acontece.
# (Mesma decisão, com o mesmo motivo, da `0001_initial`.)

import django.db.models.deletion
from django.db import migrations, models

CRIAR_FUNCAO_APPEND_ONLY = """
CREATE OR REPLACE FUNCTION sugestoes_changespec_append_only()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'INV-SUG10: ChangeSpecAprovado e append-only; UPDATE e DELETE sao recusados pelo banco';
END;
$$ LANGUAGE plpgsql;
"""

CRIAR_TRIGGER_APPEND_ONLY = """
CREATE TRIGGER sugestoes_changespec_append_only
BEFORE UPDATE OR DELETE ON sugestoes_changespecaprovado
FOR EACH ROW EXECUTE FUNCTION sugestoes_changespec_append_only();
"""

CRIAR_FUNCAO_DA_TRAVA = """
CREATE OR REPLACE FUNCTION sugestoes_exige_changespec()
RETURNS trigger AS $$
BEGIN
    IF OLD.status = 'planejado'
       AND NEW.status = 'em_desenvolvimento'
       AND NOT EXISTS (
           SELECT 1 FROM sugestoes_changespecaprovado c
           WHERE c.sugestao_id = NEW.id
       )
    THEN
        RAISE EXCEPTION 'INV-SUG10: sugestao % nao tem ChangeSpec aprovado registrado; planejado -> em_desenvolvimento e recusado', NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

CRIAR_TRIGGER_DA_TRAVA = """
CREATE TRIGGER sugestoes_exige_changespec
BEFORE UPDATE OF status ON sugestoes_sugestao
FOR EACH ROW EXECUTE FUNCTION sugestoes_exige_changespec();
"""

APAGAR_TRIGGER_APPEND_ONLY = (
    "DROP TRIGGER IF EXISTS sugestoes_changespec_append_only "
    "ON sugestoes_changespecaprovado;"
)
APAGAR_FUNCAO_APPEND_ONLY = (
    "DROP FUNCTION IF EXISTS sugestoes_changespec_append_only();"
)
APAGAR_TRIGGER_DA_TRAVA = (
    "DROP TRIGGER IF EXISTS sugestoes_exige_changespec ON sugestoes_sugestao;"
)
APAGAR_FUNCAO_DA_TRAVA = "DROP FUNCTION IF EXISTS sugestoes_exige_changespec();"


class Migration(migrations.Migration):

    dependencies = [
        ("sugestoes", "0003_aviso"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeSpecAprovado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_id", models.CharField(max_length=60)),
                ("documento", models.CharField(max_length=300)),
                ("aprovado_por", models.CharField(max_length=120)),
                ("aprovado_em", models.DateField()),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changespecs_registrados",
                        to="sugestoes.identidade",
                    ),
                ),
                (
                    "sugestao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changespecs",
                        to="sugestoes.sugestao",
                    ),
                ),
            ],
            options={
                "ordering": ["-registrado_em", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sugestao", "change_id"),
                        name="changespec_unico_por_sugestao",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("aprovado_por", ""), _negated=True),
                        name="changespec_tem_quem_aprovou",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("documento", ""), _negated=True),
                        name="changespec_tem_documento",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=[
                CRIAR_FUNCAO_APPEND_ONLY,
                CRIAR_TRIGGER_APPEND_ONLY,
                CRIAR_FUNCAO_DA_TRAVA,
                CRIAR_TRIGGER_DA_TRAVA,
            ],
            reverse_sql=[
                APAGAR_TRIGGER_DA_TRAVA,
                APAGAR_FUNCAO_DA_TRAVA,
                APAGAR_TRIGGER_APPEND_ONLY,
                APAGAR_FUNCAO_APPEND_ONLY,
            ],
        ),
    ]
