# Generated by Django 5.1.4 on 2026-08-25 20:04
"""EVO-42 — o `Aviso` passa a dizer POR QUE esta pessoa está recebendo.

`default="autor"` preenche as linhas que já existem, e não é um chute: até este
despacho a única linha que a Caixa sabia escrever era a do autor (EVO-21), então
`autor` é a verdade sobre 100% do que está no banco. Uma migração de dados aqui
seria cerimônia para reafirmar o mesmo valor.

Sem trigger e sem constraint nova: o `Aviso` **não** é append-only (o `lido_em` é
escrito depois, por desenho). Append-only nesta célula são `HistoricoStatus` e
`ChangeSpecAprovado`, e os triggers deles moram nas migrações `0001` e `0004`.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sugestoes", "0004_changespec_aprovado"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviso",
            name="vinculo",
            field=models.CharField(
                choices=[
                    ("autor", "Sua ideia"),
                    ("comentario", "Ideia em que você comentou"),
                    ("voto", "Ideia em que você votou"),
                ],
                default="autor",
                max_length=20,
            ),
        ),
    ]
