# Generated by Django 5.1.4 on 2026-08-25 23:26
"""Fase 1 do `docs/notificacoes/PLANO-MESTRE.md` — o id que ATRAVESSA.

A `Identidade` local passa a guardar, ao lado do id opaco que ESTA célula cunha,
o id da mesma pessoa na célula `identidade` — o único identificador que qualquer
célula da plataforma entende. O dado já chegava a cada entrada (`SessionFull.id`,
contrato congelado) e era descartado na porta.

**Sem migração de dados, e isso é o desenho, não uma sobra.** Não existe, do lado
de cá, de onde derivar o id da plataforma de uma linha antiga: a única ponte é o
e-mail, e perguntá-la à `identidade` seria esta célula pedindo a lista de gente da
outra. As linhas nascem `NULL` e são preenchidas **na reentrada** de cada pessoa
(`apps/core/sessao.py`); quantas faltam é o que
`manage.py relatorio_id_da_plataforma` responde.

**Por que `null=True` e não `default=""`:** no Postgres o índice único trata cada
`NULL` como distinto — mil linhas antigas sem o dado convivem sem colidir. Com
string vazia este `AddField` estouraria na SEGUNDA linha existente
(`duplicate key value violates unique constraint`). O `CheckConstraint` fecha o
outro lado: `''` deixa de ser um valor possível, para que "não sei" tenha uma
forma só.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sugestoes", "0005_aviso_vinculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="identidade",
            name="id_da_plataforma",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="identidade",
            constraint=models.CheckConstraint(
                condition=models.Q(("id_da_plataforma", ""), _negated=True),
                name="identidade_id_da_plataforma_nunca_vazio",
            ),
        ),
    ]
