# Generated by hand, no formato dos que a assinam nesta pasta.
"""O arquivamento de ideias — `docs/decisoes/DECISAO-arquivar-ideia.md`.

Três colunas novas em `Sugestao`, todas opcionais e todas com `NULL`/`""` como
o estado "nunca arquivada" — nenhuma linha existente muda de significado com
esta migração. `arquivada_em` é o carimbo que `SugestaoQuerySet.visiveis()`
lê; `arquivada_por` é `PROTECT`, como toda referência a `Identidade` nesta
célula, para que apagar uma identidade não pudesse apagar em silêncio quem
arquivou o quê.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sugestoes", "0008_backfill_cartas_dos_avisos_existentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="sugestao",
            name="arquivada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sugestao",
            name="motivo_do_arquivamento",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sugestao",
            name="arquivada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ideias_arquivadas",
                to="sugestoes.identidade",
            ),
        ),
    ]
