# Generated by Django 5.1.4 on 2026-08-31 21:46
#
# O QUE ESTAVA ESCRITO ANTES DA CORREÇÃO — e o trigger que impede alguém de
# reescrever essa resposta (`DECISAO-corrigir-o-texto-de-uma-ideia.md`).
#
# `sugestoes_correcao_append_only` é a TERCEIRA tabela append-only desta célula,
# com o trigger na forma exata dos outros dois (`0001_initial` para o
# `HistoricoStatus`, `0004` para o `ChangeSpecAprovado`). O motivo aqui é o mais
# direto dos três: esta tabela é a ÚNICA cópia do texto que o aluno escreveu.
# Com os degraus só em Python, um `QuerySet.update()` ou um `psql` apagaria a
# prova do que ele tinha dito, e a correção "calada" que o mantenedor pediu
# viraria correção sem rastro nenhum, que é outra coisa (`armadilhas/079`: o
# collector do CASCADE passa por baixo dos dois primeiros degraus).
#
# `RunSQL` recebe uma LISTA, e não uma string única, pelo mesmo motivo da `0004`:
# string única passa por `prepare_sql_script`, que fatia o SQL em `;` com o
# `sqlparse`. Com lista, cada elemento vai direto ao cursor.

import django.db.models.deletion
from django.db import migrations, models

CRIAR_FUNCAO_APPEND_ONLY = """
CREATE OR REPLACE FUNCTION sugestoes_correcao_append_only()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'CorrecaoDeTexto e append-only; UPDATE e DELETE sao recusados pelo banco. Correcao errada se conserta com outra correcao.';
END;
$$ LANGUAGE plpgsql;
"""

CRIAR_TRIGGER_APPEND_ONLY = """
CREATE TRIGGER sugestoes_correcao_append_only
BEFORE UPDATE OR DELETE ON sugestoes_correcaodetexto
FOR EACH ROW EXECUTE FUNCTION sugestoes_correcao_append_only();
"""

APAGAR_TRIGGER_APPEND_ONLY = (
    "DROP TRIGGER IF EXISTS sugestoes_correcao_append_only "
    "ON sugestoes_correcaodetexto;"
)
APAGAR_FUNCAO_APPEND_ONLY = "DROP FUNCTION IF EXISTS sugestoes_correcao_append_only();"


class Migration(migrations.Migration):

    dependencies = [
        ("sugestoes", "0011_travessao_fora_do_comentario_de_demonstracao"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrecaoDeTexto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campo",
                    models.CharField(
                        choices=[
                            ("titulo", "Título"),
                            ("problema", "Problema"),
                            ("solucao_proposta", "Solução proposta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("antes", models.TextField(blank=True)),
                ("depois", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "corrigido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcoes_de_texto",
                        to="sugestoes.identidade",
                    ),
                ),
                (
                    "sugestao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcoes",
                        to="sugestoes.sugestao",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("antes", models.F("depois")), _negated=True
                        ),
                        name="correcao_muda_alguma_coisa",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql=[CRIAR_FUNCAO_APPEND_ONLY, CRIAR_TRIGGER_APPEND_ONLY],
            reverse_sql=[APAGAR_TRIGGER_APPEND_ONLY, APAGAR_FUNCAO_APPEND_ONLY],
        ),
    ]
