# Generated by Django 5.1.4 on 2026-09-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sugestoes", "0012_correcao_de_texto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fusao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.TextField(blank=True, default="")),
                ("feita_em", models.DateTimeField(auto_now_add=True)),
                ("desfeita_em", models.DateTimeField(blank=True, null=True)),
                (
                    "canonica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fusoes",
                        to="sugestoes.sugestao",
                    ),
                ),
                (
                    "desfeita_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fusoes_desfeitas",
                        to="sugestoes.identidade",
                    ),
                ),
                (
                    "feita_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fusoes_feitas",
                        to="sugestoes.identidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdeiaAbsorvida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_anterior", models.CharField(max_length=20)),
                ("votos_movidos", models.JSONField(blank=True, default=list)),
                ("votos_descartados", models.JSONField(blank=True, default=list)),
                ("comentarios_movidos", models.JSONField(blank=True, default=list)),
                (
                    "fusao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absorvidas",
                        to="sugestoes.fusao",
                    ),
                ),
                (
                    "sugestao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absorcoes",
                        to="sugestoes.sugestao",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="fusao",
            index=models.Index(
                fields=["canonica", "desfeita_em"],
                name="sugestoes_f_canonic_a4eada_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ideiaabsorvida",
            constraint=models.UniqueConstraint(
                fields=("fusao", "sugestao"), name="uma_ideia_uma_vez_por_fusao"
            ),
        ),
    ]
