# Generated by Django 5.1.4 on 2026-09-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_roteiro_da_prancheta"),
    ]

    operations = [
        migrations.AddField(
            model_name="peca",
            name="conferido_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peca",
            name="estado_do_link",
            field=models.CharField(
                choices=[
                    ("respondendo", "O endereço abriu na última conferência"),
                    ("quebrado", "O endereço parou de abrir"),
                    ("nao_conferido", "A escola ainda não conseguiu conferir"),
                ],
                default="nao_conferido",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="peca",
            name="quebrado_desde",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="peca",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estado_do_link__in", ["respondendo", "quebrado", "nao_conferido"])
                ),
                name="o_estado_do_link_e_um_dos_tres",
            ),
        ),
        migrations.AddConstraint(
            model_name="peca",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("estado_do_link", "quebrado"),
                        ("quebrado_desde__isnull", False),
                    ),
                    models.Q(
                        models.Q(("estado_do_link", "quebrado"), _negated=True),
                        ("quebrado_desde__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="a_quebra_e_a_data_dela_andam_juntas",
            ),
        ),
    ]
