# Generated by Django 5.1.4 on 2026-09-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_o_estado_do_link_da_peca"),
    ]

    operations = [
        migrations.AddField(
            model_name="peca",
            name="acabamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_poly", "High poly, mais detalhada"),
                    ("mais_simples", "Uma variação mais simples"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="peca",
            name="parecida_com_a_aula",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nao", "Não se parece com o modelo da aula"),
                    ("sim", "Se parece com o modelo da aula"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="peca",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("armas", "Armas"),
                    ("carros", "Carros"),
                    ("cabelos", "Cabelos"),
                    ("acessorios", "Acessórios"),
                    ("animais", "Animais"),
                    ("outro", "Outro tipo que o curso ensina"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="peca",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tipo__in",
                        [
                            "",
                            "armas",
                            "carros",
                            "cabelos",
                            "acessorios",
                            "animais",
                            "outro",
                        ],
                    )
                ),
                name="o_tipo_da_peca_e_um_dos_da_escola",
            ),
        ),
        migrations.AddConstraint(
            model_name="peca",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("acabamento__in", ["", "high_poly", "mais_simples"])
                ),
                name="o_acabamento_da_peca_e_um_dos_dois",
            ),
        ),
        migrations.AddConstraint(
            model_name="peca",
            constraint=models.CheckConstraint(
                condition=models.Q(("parecida_com_a_aula__in", ["", "nao", "sim"])),
                name="a_semelhanca_com_a_aula_e_sim_ou_nao",
            ),
        ),
    ]
