# Generated by Django 5.1.4 on 2026-09-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_as_respostas_objetivas_da_peca"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoDeConferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("em_analise", "A escola está olhando o seu portfólio"),
                            ("aceito", "A escola conferiu o seu portfólio"),
                            ("devolvido", "A escola devolveu com o que falta"),
                        ],
                        default="em_analise",
                        max_length=10,
                    ),
                ),
                ("prazo_ate", models.DateTimeField()),
                (
                    "motivo_da_devolucao",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "poucos_tipos",
                                "Faltam tipos de modelo: a escola pede pelo menos 3 tipos diferentes entre os que o curso ensina.",
                            ),
                            (
                                "poucas_pecas",
                                "Faltam peças: a escola pede pelo menos 3 de cada tipo que você escolheu, o que dá 9 no mínimo.",
                            ),
                            (
                                "pouco_high_poly",
                                "A maioria das peças ainda não está em high poly, que é o que a escola pede para impressionar o cliente.",
                            ),
                            (
                                "parecida_com_a_aula",
                                "Há peças parecidas demais com o modelo feito na aula. Troque por criações suas.",
                            ),
                            (
                                "peca_que_nao_abre",
                                "A escola não conseguiu abrir o endereço de alguma peça. Guarde a peça de novo com o endereço atual dela.",
                            ),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("respondido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "respondido_por",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_de_conferencia",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido de conferência",
                "verbose_name_plural": "pedidos de conferência",
                "ordering": ["prazo_ate", "criado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "em_analise")),
                        fields=("portfolio",),
                        name="um_pedido_de_conferencia_em_analise_por_portfolio",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("estado__in", ["em_analise", "aceito", "devolvido"])
                        ),
                        name="o_estado_do_pedido_e_um_dos_tres",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("estado", "devolvido"),
                                models.Q(("motivo_da_devolucao", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(("estado", "devolvido"), _negated=True),
                                ("motivo_da_devolucao", ""),
                            ),
                            _connector="OR",
                        ),
                        name="a_devolucao_tem_motivo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "motivo_da_devolucao__in",
                                [
                                    "",
                                    "poucos_tipos",
                                    "poucas_pecas",
                                    "pouco_high_poly",
                                    "parecida_com_a_aula",
                                    "peca_que_nao_abre",
                                ],
                            )
                        ),
                        name="o_motivo_da_devolucao_e_um_dos_da_escola",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("estado", "em_analise"),
                                ("respondido_em__isnull", True),
                                ("respondido_por", ""),
                            ),
                            models.Q(
                                models.Q(("estado", "em_analise"), _negated=True),
                                ("respondido_em__isnull", False),
                                models.Q(("respondido_por", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="a_resposta_tem_data_e_quem_respondeu",
                    ),
                ],
            },
        ),
    ]
