# Generated by Django 5.1.4 on 2026-09-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_a_outbox_do_selo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidodeconferencia",
            name="assumido_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedidodeconferencia",
            name="assumido_por",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="pedidodeconferencia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("assumido_em__isnull", True), ("assumido_por", "")),
                    models.Q(
                        models.Q(("assumido_por", ""), _negated=True),
                        ("assumido_em__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="quem_assumiu_tem_data",
            ),
        ),
    ]
