# Generated by Django 5.1.4 on 2026-10-04 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_galeria_e_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAosColegas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('pergunta', models.TextField(blank=True, default='')),
                ('materiais', models.JSONField(default=dict)),
                ('encerrado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_aos_colegas', to='portfolio.portfolio')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.projetoautoral')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaDoColega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.CharField(max_length=64)),
                ('nome', models.CharField(blank=True, default='', max_length=200)),
                ('pontos_fortes', models.TextField(blank=True, default='')),
                ('melhorar', models.TextField(blank=True, default='')),
                ('proxima_tentativa', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='portfolio.pedidoaoscolegas')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
