# Generated by Django 5.1.4 on 2026-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("tipo", models.CharField(max_length=120)),
                ("versao", models.PositiveIntegerField()),
                ("celula", models.CharField(max_length=60)),
                ("site_id", models.CharField(max_length=60)),
                ("ocorrido_em", models.DateTimeField()),
                ("recebido_em", models.DateTimeField(auto_now_add=True)),
                ("dia", models.DateField()),
                ("dados", models.JSONField()),
            ],
            options={
                "ordering": ["-ocorrido_em"],
                "indexes": [
                    models.Index(
                        fields=["tipo", "dia"], name="fatos_event_tipo_fe77b6_idx"
                    ),
                    models.Index(fields=["dia"], name="fatos_event_dia_e8c0d6_idx"),
                    models.Index(
                        fields=["celula", "recebido_em"],
                        name="fatos_event_celula_7b126f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventoMorto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corpo", models.TextField()),
                ("motivo", models.TextField()),
                ("tipo_declarado", models.CharField(blank=True, max_length=120)),
                ("event_id_declarado", models.CharField(blank=True, max_length=80)),
                ("recebido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("reprocessado", "Reprocessado"),
                            ("descartado", "Descartado"),
                        ],
                        default="novo",
                        max_length=20,
                    ),
                ),
                ("decidido_em", models.DateTimeField(blank=True, null=True)),
                ("decidido_por", models.CharField(blank=True, max_length=80)),
                ("motivo_da_decisao", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-recebido_em"],
                "indexes": [
                    models.Index(
                        fields=["estado", "recebido_em"],
                        name="fatos_event_estado_6b99e3_idx",
                    )
                ],
            },
        ),
    ]
