# Generated by Django 5.1.4 on 2026-09-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatos", "0002_a_trava_do_banco"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="ator_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.CreateModel(
            name="Marco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sujeito_tipo",
                    models.CharField(
                        choices=[("pessoa", "Pessoa"), ("matricula", "Matrícula")],
                        max_length=20,
                    ),
                ),
                ("sujeito_id", models.CharField(max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrou-no-site", "Entrou no site"),
                            ("pediu-entrada", "Pediu entrada na escola"),
                            ("virou-aluno-comprando", "Virou aluno comprando"),
                            ("virou-aluno-liberado", "Virou aluno por liberação"),
                            ("escreveu-no-forum", "Escreveu no fórum"),
                            ("ajudou-alguem", "Ajudou alguém no fórum"),
                        ],
                        max_length=40,
                    ),
                ),
                ("dia", models.DateField()),
                ("event_id", models.UUIDField()),
                (
                    "procedencia",
                    models.CharField(
                        choices=[
                            ("automatico", "Automático"),
                            ("assinado", "Assinado"),
                        ],
                        default="automatico",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["dia", "tipo"],
                "indexes": [
                    models.Index(
                        fields=["tipo", "dia"], name="fatos_marco_tipo_4861f4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sujeito_tipo", "sujeito_id", "tipo"),
                        name="um_marco_por_sujeito_por_tipo",
                    )
                ],
            },
        ),
    ]
