# Generated by Django 5.1.4 on 2026-10-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatos', '0006_fatos_do_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatoLinkAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('site_id', models.CharField(max_length=100)),
                ('link_id', models.UUIDField(db_index=True)),
                ('destino_id', models.CharField(blank=True, default='', max_length=60)),
                ('versao', models.IntegerField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, default='', max_length=20)),
                ('campanha', models.CharField(blank=True, default='', max_length=100)),
                ('mensagem_id', models.CharField(blank=True, default='', max_length=60)),
                ('passo_id', models.CharField(blank=True, default='', max_length=60)),
                ('classificacao', models.CharField(blank=True, default='', max_length=16)),
                ('metodo', models.CharField(blank=True, default='', max_length=8)),
                ('ocorrido_em', models.DateTimeField()),
            ],
            options={
                'ordering': ['ocorrido_em'],
                'indexes': [models.Index(fields=['site_id', 'ocorrido_em'], name='fatos_fatol_site_id_f826d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FatoLinkEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('site_id', models.CharField(max_length=100)),
                ('link_id', models.UUIDField(unique=True)),
                ('token', models.CharField(blank=True, default='', max_length=10)),
                ('destino_id', models.CharField(blank=True, default='', max_length=60)),
                ('destino_nome', models.CharField(blank=True, default='', max_length=200)),
                ('versao', models.IntegerField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, default='', max_length=20)),
                ('campanha', models.CharField(blank=True, default='', max_length=100)),
                ('mensagem_id', models.CharField(blank=True, default='', max_length=60)),
                ('passo_id', models.CharField(blank=True, default='', max_length=60)),
                ('enviado_em', models.DateTimeField()),
            ],
            options={
                'ordering': ['enviado_em'],
                'indexes': [models.Index(fields=['site_id', 'enviado_em'], name='fatos_fatol_site_id_6cef18_idx'), models.Index(fields=['site_id', 'destino_id'], name='fatos_fatol_site_id_d00f7f_idx'), models.Index(fields=['site_id', 'campanha'], name='fatos_fatol_site_id_f5a5c5_idx')],
            },
        ),
    ]
