# Generated by Django 5.1.4 on 2026-08-28 21:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id_da_plataforma",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nome_exibido", models.CharField(blank=True, max_length=120)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("vista_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "pessoas",
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "visibilidade",
                    models.CharField(
                        choices=[
                            ("publica", "Pública — qualquer um lê"),
                            ("alunos", "Alunos — só quem comprou"),
                            ("turma", "Turma — só quem está no curso"),
                        ],
                        default="alunos",
                        max_length=10,
                    ),
                ),
                (
                    "quem_escreve",
                    models.CharField(
                        choices=[
                            ("aluno", "Alunos e acima"),
                            ("equipe", "Só professor ou administrador"),
                            ("cadastrado", "Qualquer pessoa com login"),
                        ],
                        default="aluno",
                        max_length=12,
                    ),
                ),
                ("curso_id", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "ordering": ["ordem", "nome"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("visibilidade", "turma"), _negated=True),
                            models.Q(("curso_id", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="area_de_turma_exige_curso",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("editado_em", models.DateTimeField(blank=True, null=True)),
                ("removida_em", models.DateTimeField(blank=True, null=True)),
                (
                    "busca",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensagens",
                        to="forum.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Topico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=180)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ultima_atividade_em",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("publicado", "Publicado"),
                            ("esperando", "Esperando aprovação"),
                            ("removido", "Removido pela moderação"),
                        ],
                        default="publicado",
                        max_length=10,
                    ),
                ),
                ("fixado", models.BooleanField(default=False)),
                ("trancado", models.BooleanField(default=False)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topicos",
                        to="forum.area",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topicos",
                        to="forum.pessoa",
                    ),
                ),
                (
                    "resposta_aceita",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aceita_em",
                        to="forum.mensagem",
                    ),
                ),
            ],
            options={
                "ordering": ["-fixado", "-ultima_atividade_em"],
            },
        ),
        migrations.AddField(
            model_name="mensagem",
            name="topico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensagens",
                to="forum.topico",
            ),
        ),
        migrations.CreateModel(
            name="TopicoLido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lido_em", models.DateTimeField()),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lidos",
                        to="forum.pessoa",
                    ),
                ),
                (
                    "topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lidos",
                        to="forum.topico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarcaDeLeitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lido_ate", models.DateTimeField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marcas",
                        to="forum.area",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marcas",
                        to="forum.pessoa",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pessoa", "area"), name="uma_marca_por_pessoa_por_area"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="topico",
            index=models.Index(
                fields=["area", "estado", "-fixado", "-ultima_atividade_em"],
                name="forum_topic_area_id_2b253d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["busca"], name="forum_mensagem_busca_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=models.Index(
                fields=["topico", "criado_em"], name="forum_mensa_topico__deb651_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="topicolido",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "topico"), name="uma_leitura_por_pessoa_por_topico"
            ),
        ),
    ]
