"""A caixa de saida do forum: a tabela por onde ele passa a FALAR.

Acompanha o degrau 17 da escada da gamificacao. Ate aqui o forum era mudo, e a
medalha "Mao amiga" nao tinha como cair porque ninguem contava as respostas
aceitas.

VEM JUNTO UMA DIVIDA ANTIGA, e ela e declarada em vez de escondida: o
`AlterField` de `Area.visibilidade` NAO e desta entrega. Os rotulos das escolhas
mudaram no modelo em algum momento sem migracao, e o `makemigrations` os propoe
desde entao. Alterar `choices` nao toca o banco (e metadado do Django), entao
carregar isto aqui e barato e para de propor a mesma coisa em toda migracao
futura desta celula.
"""

# Generated by Django 5.1.4 on 2026-09-01 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0006_reindexar_a_busca_com_a_config_ativa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="visibilidade",
            field=models.CharField(
                choices=[
                    ("publica", "Pública: qualquer um lê"),
                    ("alunos", "Alunos: só quem comprou"),
                    ("turma", "Turma: só quem está no curso"),
                ],
                default="alunos",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("event", models.CharField(max_length=100)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("payload", models.JSONField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("envelope_extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["published_at", "id"],
                        name="forum_outbo_publish_7fba56_idx",
                    )
                ],
            },
        ),
    ]
