# Generated by Django 5.1.4 on 2026-09-18 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0007_a_voz_do_forum"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentimentoDaGaleria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                ("host_publico", models.CharField(max_length=120)),
                ("referencia_url", models.URLField(max_length=400)),
                ("concedido_em", models.DateTimeField()),
                ("revogado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "concedido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consentimentos_da_galeria",
                        to="forum.pessoa",
                    ),
                ),
                (
                    "topico",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consentimento_da_galeria",
                        to="forum.topico",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "consentimentos da galeria",
                "indexes": [
                    models.Index(
                        fields=["site_id", "revogado_em", "-concedido_em"],
                        name="forum_conse_site_id_a6e126_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("site_id", ""), _negated=True),
                            models.Q(("host_publico", ""), _negated=True),
                            ("referencia_url__startswith", "https://"),
                        ),
                        name="consentimento_com_escola_e_endereco_seguro",
                    )
                ],
            },
        ),
    ]
