# Generated by Django 5.1.4 on 2026-09-27 05:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0008_consentimento_da_galeria"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos_sob_responsabilidade",
                to="forum.pessoa",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="vagas",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MembroDoGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.CharField(max_length=200)),
                ("desde", models.DateTimeField(default=django.utils.timezone.now)),
                ("ate", models.DateTimeField(blank=True, null=True)),
                (
                    "adicionado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="forum.pessoa",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membros",
                        to="forum.area",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passagens_por_grupos",
                        to="forum.pessoa",
                    ),
                ),
                (
                    "removido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="forum.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["desde"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ate__isnull", True)),
                        fields=("pessoa", "grupo"),
                        name="um_vinculo_ativo_por_pessoa_e_grupo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ate__isnull", True), ("removido_por__isnull", True)
                            ),
                            models.Q(
                                ("ate__isnull", False), ("removido_por__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="saida_do_grupo_tem_quem_removeu",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ate__isnull", True),
                            ("ate__gte", models.F("desde")),
                            _connector="OR",
                        ),
                        name="saida_do_grupo_depois_da_entrada",
                    ),
                ],
            },
        ),
    ]
