# Generated by Django 5.1.4 on 2026-09-27 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

# O REGISTRO SÓ ACRESCENTA (TAR-847). O gatilho recusa UPDATE e DELETE linha a
# linha, venha de onde vier: `save()`, `update()`, `delete()` ou `psql`. Criar
# função em plpgsql pede o mesmo poder que criar tabela no esquema, que o papel
# da célula já usa em toda migração; não exige superusuário.
SO_ACRESCENTA = [
    """
    CREATE FUNCTION forum_registro_de_moderacao_so_acrescenta() RETURNS trigger AS $$
    BEGIN
        RAISE EXCEPTION 'o registro de moderação só aceita linha nova (% recusado)', TG_OP;
    END;
    $$ LANGUAGE plpgsql
    """,
    """
    CREATE TRIGGER registro_de_moderacao_so_acrescenta
        BEFORE UPDATE OR DELETE ON forum_registrodemoderacao
        FOR EACH ROW EXECUTE FUNCTION forum_registro_de_moderacao_so_acrescenta()
    """,
]

DESFAZ_O_GATILHO = [
    "DROP TRIGGER registro_de_moderacao_so_acrescenta ON forum_registrodemoderacao",
    "DROP FUNCTION forum_registro_de_moderacao_so_acrescenta()",
]


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0009_grupo_de_pratica"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroDeModeracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("fixar", "fixou a conversa"),
                            ("desafixar", "desafixou a conversa"),
                            ("trancar", "trancou a conversa"),
                            ("destrancar", "destrancou a conversa"),
                            ("tirar_do_ar", "tirou a conversa do ar"),
                            ("restaurar", "devolveu a conversa ao ar"),
                            ("mover", "mudou a conversa de área"),
                            ("editar_topico", "editou o título da conversa"),
                            ("editar_mensagem", "editou uma mensagem"),
                            ("tirar_mensagem_do_ar", "tirou uma mensagem do ar"),
                            ("restaurar_mensagem", "devolveu uma mensagem ao ar"),
                            ("apontar_resposta", "apontou a resposta certa"),
                            ("desmarcar_resposta", "tirou o selo de resolvido"),
                            ("trocar_responsavel", "trocou o responsável do grupo"),
                            ("mudar_vagas", "mudou as vagas do grupo"),
                            ("adicionar_membro", "pôs no grupo"),
                            ("remover_membro", "tirou do grupo"),
                            ("trocar_de_grupo", "trocou de grupo"),
                        ],
                        max_length=24,
                    ),
                ),
                ("detalhe", models.CharField(blank=True, max_length=400)),
                ("motivo", models.CharField(blank=True, max_length=200)),
                ("quando", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="forum.area",
                    ),
                ),
                (
                    "area_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="forum.area",
                    ),
                ),
                (
                    "ator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="forum.pessoa",
                    ),
                ),
                (
                    "mensagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="forum.mensagem",
                    ),
                ),
                (
                    "topico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="forum.topico",
                    ),
                ),
                (
                    "vinculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="forum.membrodogrupo",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["area", "-quando"],
                        name="forum_regis_area_id_32a1fc_idx",
                    ),
                    models.Index(
                        fields=["area_destino", "-quando"],
                        name="forum_regis_area_de_e79cf4_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "acao__in",
                                [
                                    "fixar",
                                    "desafixar",
                                    "trancar",
                                    "destrancar",
                                    "tirar_do_ar",
                                    "restaurar",
                                    "mover",
                                    "editar_topico",
                                    "editar_mensagem",
                                    "tirar_mensagem_do_ar",
                                    "restaurar_mensagem",
                                    "apontar_resposta",
                                    "desmarcar_resposta",
                                    "trocar_responsavel",
                                    "mudar_vagas",
                                    "adicionar_membro",
                                    "remover_membro",
                                    "trocar_de_grupo",
                                ],
                            )
                        ),
                        name="registro_de_moderacao_vocabulario_fechado",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "acao__in",
                                    (
                                        "tirar_do_ar",
                                        "restaurar",
                                        "mover",
                                        "tirar_mensagem_do_ar",
                                        "restaurar_mensagem",
                                        "trocar_responsavel",
                                        "adicionar_membro",
                                        "remover_membro",
                                        "trocar_de_grupo",
                                    ),
                                ),
                                _negated=True,
                            ),
                            models.Q(("motivo", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="registro_de_moderacao_motivo_obrigatorio",
                    ),
                ],
            },
        ),
        migrations.RunSQL(SO_ACRESCENTA, DESFAZ_O_GATILHO),
    ]
