# Generated by Django 5.1.4 on 2026-09-27 12:02

from django.db import migrations, models

# OS GESTOS SOBRE A ÁREA INTEIRA (TAR-867). As duas restrições só crescem: o
# vocabulário novo contém o antigo e o motivo continua exigido onde já era, então
# nenhuma linha gravada até aqui fica em desacordo e o `migrate` do boot não
# encontra o que recusar (lição 5 de `services/forum/LICOES.md`). O gatilho que
# recusa UPDATE e DELETE (migração 0010) não é tocado.


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0010_registro_de_moderacao"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registrodemoderacao",
            name="registro_de_moderacao_vocabulario_fechado",
        ),
        migrations.RemoveConstraint(
            model_name="registrodemoderacao",
            name="registro_de_moderacao_motivo_obrigatorio",
        ),
        migrations.AlterField(
            model_name="registrodemoderacao",
            name="acao",
            field=models.CharField(
                choices=[
                    ("fixar", "fixou a conversa"),
                    ("desafixar", "desafixou a conversa"),
                    ("trancar", "trancou a conversa"),
                    ("destrancar", "destrancou a conversa"),
                    ("tirar_do_ar", "tirou a conversa do ar"),
                    ("restaurar", "devolveu a conversa ao ar"),
                    ("mover", "mudou a conversa de área"),
                    ("editar_topico", "editou o título da conversa"),
                    ("editar_mensagem", "editou uma mensagem"),
                    ("tirar_mensagem_do_ar", "tirou uma mensagem do ar"),
                    ("restaurar_mensagem", "devolveu uma mensagem ao ar"),
                    ("apontar_resposta", "apontou a resposta certa"),
                    ("desmarcar_resposta", "tirou o selo de resolvido"),
                    ("trocar_responsavel", "trocou o responsável do grupo"),
                    ("mudar_vagas", "mudou as vagas do grupo"),
                    ("adicionar_membro", "pôs no grupo"),
                    ("remover_membro", "tirou do grupo"),
                    ("trocar_de_grupo", "trocou de grupo"),
                    ("arquivar_area", "arquivou a área"),
                    ("reabrir_area", "reabriu a área"),
                    ("renomear_area", "renomeou a área"),
                    ("mudar_acesso_da_area", "mudou quem enxerga ou escreve na área"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="registrodemoderacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "acao__in",
                        [
                            "fixar",
                            "desafixar",
                            "trancar",
                            "destrancar",
                            "tirar_do_ar",
                            "restaurar",
                            "mover",
                            "editar_topico",
                            "editar_mensagem",
                            "tirar_mensagem_do_ar",
                            "restaurar_mensagem",
                            "apontar_resposta",
                            "desmarcar_resposta",
                            "trocar_responsavel",
                            "mudar_vagas",
                            "adicionar_membro",
                            "remover_membro",
                            "trocar_de_grupo",
                            "arquivar_area",
                            "reabrir_area",
                            "renomear_area",
                            "mudar_acesso_da_area",
                        ],
                    )
                ),
                name="registro_de_moderacao_vocabulario_fechado",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrodemoderacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "acao__in",
                            (
                                "tirar_do_ar",
                                "restaurar",
                                "mover",
                                "tirar_mensagem_do_ar",
                                "restaurar_mensagem",
                                "trocar_responsavel",
                                "adicionar_membro",
                                "remover_membro",
                                "trocar_de_grupo",
                                "arquivar_area",
                                "reabrir_area",
                                "mudar_acesso_da_area",
                            ),
                        ),
                        _negated=True,
                    ),
                    models.Q(("motivo", ""), _negated=True),
                    _connector="OR",
                ),
                name="registro_de_moderacao_motivo_obrigatorio",
            ),
        ),
    ]
