# Generated by Django 5.0.9 on 2026-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0002_semear_pagina_de_oferta_teste"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="tipo",
            field=models.CharField(
                choices=[("oferta", "Oferta"), ("flp", "FLP")],
                default="oferta",
                db_default="oferta",
                max_length=6,
            ),
        ),
    ]
