# Generated by Django 5.0.9 on 2026-09-26 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0003_page_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experimento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secao", models.CharField(max_length=32)),
                ("slot", models.CharField(max_length=32)),
                ("hipotese", models.TextField()),
                ("metrica_principal", models.CharField(max_length=100)),
                ("taxa_base", models.FloatField()),
                ("mde", models.FloatField()),
                ("n_por_braco_planejado", models.PositiveIntegerField()),
                ("dias_planejados", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("ativo", "Ativo"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="rascunho",
                        max_length=9,
                    ),
                ),
                (
                    "decisao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("promover", "Promover"),
                            ("reverter", "Reverter"),
                            ("encerrar", "Encerrar"),
                        ],
                        max_length=8,
                    ),
                ),
                ("vencedora", models.CharField(blank=True, max_length=32)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("iniciado_em", models.DateTimeField(blank=True, null=True)),
                ("encerrado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experimentos",
                        to="paginas.page",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Variante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("variante_id", models.CharField(max_length=32)),
                ("peso", models.PositiveIntegerField()),
                ("valor", models.TextField()),
                (
                    "experimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="paginas.experimento",
                    ),
                ),
            ],
            options={
                "ordering": ["variante_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="experimento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "ativo")),
                fields=("page",),
                name="um_experimento_ativo_por_pagina",
            ),
        ),
        migrations.AddConstraint(
            model_name="variante",
            constraint=models.UniqueConstraint(
                fields=("experimento", "variante_id"),
                name="variante_unica_por_experimento",
            ),
        ),
    ]
