# Generated by Django 5.1.4 on 2026-10-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoDeVoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('transcricao', 'Transcrição'), ('sintese', 'Resposta em voz')], max_length=20)),
                ('site_id', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=160)),
                ('conversa_ref', models.CharField(blank=True, default='', max_length=160)),
                ('consumo_id', models.BigIntegerField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, default='', max_length=60)),
                ('segundos', models.FloatField(blank=True, null=True)),
                ('caracteres', models.PositiveIntegerField(default=0)),
                ('custo_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('texto', models.TextField(blank=True, default='')),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('situacao', models.CharField(choices=[('feito', 'Feito'), ('entregue', 'Entregue à mensageria'), ('falhou', 'Falhou')], default='feito', max_length=20)),
                ('detalhe', models.CharField(blank=True, default='', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'site_id', 'referencia'), name='uniq_voz_tipo_site_ref')],
            },
        ),
    ]
