# Generated by Django 5.1.4 on 2026-09-05 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id_da_plataforma",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "nome_exibido",
                    models.CharField(blank=True, default="", max_length=120),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Progresso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("trancada", "Trancada"),
                            ("disponivel", "Disponível"),
                            ("em_producao", "Em produção"),
                            ("enviada", "Enviada"),
                            ("devolvida", "Devolvida"),
                            ("concluida", "Concluída"),
                        ],
                        default="trancada",
                        max_length=12,
                    ),
                ),
                ("autoavaliacao", models.JSONField(blank=True, default=dict)),
                ("data_de_retorno", models.DateField(blank=True, null=True)),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                ("cerimonia_pendente", models.BooleanField(default=False)),
                ("laudo_lido", models.BooleanField(default=False)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progressos",
                        to="cursos.aula",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progressos",
                        to="cursos.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["pessoa", "aula"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pessoa", "aula"),
                        name="um_progresso_por_pessoa_por_aula",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "estado__in",
                                [
                                    "trancada",
                                    "disponivel",
                                    "em_producao",
                                    "enviada",
                                    "devolvida",
                                    "concluida",
                                ],
                            )
                        ),
                        name="estado_de_progresso_no_vocabulario_fechado",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("concluida_em__isnull", False), ("estado", "concluida")
                            ),
                            models.Q(
                                ("concluida_em__isnull", True),
                                models.Q(("estado", "concluida"), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="concluida_em_so_quando_concluida",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroDePausa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respostas", models.JSONField(blank=True, default=dict)),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pausa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="cursos.pausa",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_de_pausa",
                        to="cursos.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["pessoa", "pausa"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pessoa", "pausa"),
                        name="um_registro_por_pessoa_por_pausa",
                    )
                ],
            },
        ),
    ]
