# Generated by Django 5.1.4 on 2026-09-05 13:26

import datetime
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_pessoa_progresso_e_registro_de_pausa"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("event", models.CharField(max_length=100)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("payload", models.JSONField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("envelope_extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["published_at"], name="cursos_outb_publish_09b226_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Envio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                ("links", models.JSONField(default=list)),
                ("readme", models.TextField(blank=True, default="")),
                ("laudo_do_aluno", models.JSONField(blank=True, default=dict)),
                ("enviado_em", models.DateTimeField(editable=False)),
                ("prazo_em", models.DateTimeField(editable=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("em_revisao", "Em revisão"),
                            ("aberto", "Aberto"),
                            ("aberto_com_ajuste", "Aberto com ajuste"),
                            ("devolvido", "Devolvido"),
                        ],
                        default="recebido",
                        max_length=17,
                    ),
                ),
                ("estourado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envios",
                        to="cursos.aula",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envios",
                        to="cursos.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["prazo_em", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pessoa", "aula", "numero"),
                        name="um_envio_por_numero_por_pessoa_por_aula",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("numero__gte", 1)),
                        name="numero_de_envio_comeca_em_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "estado__in",
                                [
                                    "recebido",
                                    "em_revisao",
                                    "aberto",
                                    "aberto_com_ajuste",
                                    "devolvido",
                                ],
                            )
                        ),
                        name="estado_de_envio_no_vocabulario_fechado",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "prazo_em",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("enviado_em"),
                                    "+",
                                    models.Value(datetime.timedelta(days=1)),
                                ),
                            )
                        ),
                        name="prazo_de_envio_e_enviado_em_mais_24_horas",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("estourado_em__isnull", True),
                            ("estourado_em__gte", models.F("prazo_em")),
                            _connector="OR",
                        ),
                        name="estouro_de_envio_so_depois_do_prazo",
                    ),
                ],
            },
        ),
    ]
