# Generated by Django 5.1.4 on 2026-09-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0003_envio_e_outbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="RascunhoDaIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "envio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rascunhos_de_ia",
                        to="cursos.envio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Laudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("professor", "Professor"),
                            ("par", "Par"),
                            ("banca", "Banca"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "instrumento_versao",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notas", models.JSONField(blank=True, default=dict)),
                ("forcas", models.JSONField(blank=True, default=list)),
                ("mudanca", models.JSONField(blank=True, default=dict)),
                ("ajuste_feito", models.TextField(blank=True, default="")),
                (
                    "decisao",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("aberto_com_ajuste", "Aberto com ajuste"),
                            ("devolvido", "Devolvido"),
                        ],
                        max_length=17,
                    ),
                ),
                ("data_de_retorno", models.DateField(blank=True, null=True)),
                ("sabe_o_que_fazer_amanha", models.BooleanField()),
                ("emitido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="laudos_emitidos",
                        to="cursos.pessoa",
                    ),
                ),
                (
                    "envio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="laudo",
                        to="cursos.envio",
                    ),
                ),
                (
                    "rascunho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="laudos",
                        to="cursos.rascunhodaia",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("papel__in", ["professor", "par", "banca"])
                        ),
                        name="papel_de_laudo_no_vocabulario_fechado",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "decisao__in",
                                ["aberto", "aberto_com_ajuste", "devolvido"],
                            )
                        ),
                        name="decisao_de_laudo_no_vocabulario_fechado",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("instrumento_versao__isnull", True),
                            ("instrumento_versao__gte", 1),
                            _connector="OR",
                        ),
                        name="instrumento_versao_de_laudo_comeca_em_1_ou_nula",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("data_de_retorno__isnull", False),
                                ("decisao", "devolvido"),
                            ),
                            models.Q(
                                models.Q(("decisao", "devolvido"), _negated=True),
                                ("data_de_retorno__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="data_de_retorno_so_e_sempre_com_devolvido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sabe_o_que_fazer_amanha", True)),
                        name="pergunta_de_amanha_so_grava_true",
                    ),
                ],
            },
        ),
    ]
