# Generated by Django 5.1.4 on 2026-10-01 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0010_versoes_do_instrumento"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComentarioDeAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corpo", models.TextField(max_length=4000)),
                ("publico", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "moderador_id",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("moderado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comentarios",
                        to="cursos.aula",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comentarios",
                        to="cursos.pessoa",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["aula", "-criado_em"], name="comentario_aula_data_idx"
                    )
                ],
            },
        ),
    ]
