# Generated by Django 5.1.4 on 2026-10-03 23:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_evolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturaParcial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('site_id', models.CharField(max_length=64)),
                ('lead_email', models.EmailField(blank=True, default='', max_length=254)),
                ('lead_name', models.CharField(blank=True, default='', max_length=200)),
                ('lead_phone', models.CharField(blank=True, default='', max_length=32)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('publicacoes', models.PositiveIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas_parciais', to='quiz.quiz')),
                ('submissao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captura_parcial', to='quiz.submission')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas_parciais', to='quiz.quizversion')),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'lead_email'], name='captura_site_email'), models.Index(condition=models.Q(('publicada_em__isnull', True), ('submissao__isnull', True)), fields=['atualizada_em'], name='captura_a_publicar')],
                'constraints': [models.UniqueConstraint(fields=('quiz', 'session_id'), name='captura_quiz_sessao_unica')],
            },
        ),
    ]
