# Generated by Django 5.0.9 on 2026-08-18 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("site_id", models.CharField(max_length=255)),
                ("order_id", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[("pix", "pix"), ("card", "card")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("expired", "expired"),
                            ("refunded", "refunded"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(default="BRL", max_length=3)),
                ("customer", models.JSONField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("pix_qr_code", models.TextField(blank=True, default="")),
                ("pix_qr_code_base64", models.TextField(blank=True, default="")),
                ("pix_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "card_reason_code",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["order_id"], name="core_intent_order_i_13f8e2_idx"
                    )
                ],
            },
        ),
    ]
