# Generated by Django 5.0.9 on 2026-09-20 22:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_outboxevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstalacaoAppmax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=64, unique=True)),
                (
                    "appmax_site_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("alias", models.CharField(max_length=255)),
                ("platform_site_ids", models.JSONField(blank=True, default=list)),
                ("client_secret_recebido", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
