# Generated by Django 5.0.9 on 2026-09-20 23:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_instalacaoappmax"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_site_id", models.CharField(max_length=255)),
                (
                    "provider",
                    models.CharField(
                        choices=[("appmax", "appmax"), ("mercadopago", "mercadopago")],
                        max_length=20,
                    ),
                ),
                (
                    "operation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "provider_reference_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "external_order_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("installments", models.PositiveSmallIntegerField(default=1)),
                ("amount_cents", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("sending", "sending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("failed", "failed"),
                            ("reconciliation_required", "reconciliation_required"),
                        ],
                        default="sending",
                        max_length=30,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tentativas",
                        to="core.intent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider_reference_id"],
                        name="core_paymen_provide_741b7f_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ["sending", "reconciliation_required", "approved"])
                ),
                fields=("intent",),
                name="uma_tentativa_viva_por_intent",
            ),
        ),
    ]
