# Generated by Django 5.0.9 on 2026-09-23 00:21

import django.db.models.deletion
import uuid
from typing import Any
from django.db import migrations, models


def _copiar_valor_base(apps: Any, schema_editor: Any) -> None:
    Tentativa = apps.get_model("core", "PaymentAttempt")
    for tentativa in Tentativa.objects.filter(
        effective_amount_cents__isnull=True
    ).iterator():
        tentativa.effective_amount_cents = tentativa.amount_cents
        tentativa.save(update_fields=["effective_amount_cents"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_paymentattempt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_site_id", models.CharField(max_length=255)),
                (
                    "operation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("customer", "customer"),
                            ("order", "order"),
                            ("payment", "payment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("sending", "sending"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                            ("reconciliation_required", "reconciliation_required"),
                        ],
                        default="sending",
                        max_length=30,
                    ),
                ),
                (
                    "provider_resource_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="paymentattempt",
            name="uma_tentativa_viva_por_intent",
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="effective_amount_cents",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(_copiar_valor_base, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="paymentattempt",
            name="effective_amount_cents",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="previous_intent_status",
            field=models.CharField(default="created", max_length=10),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="state",
            field=models.CharField(
                choices=[
                    ("sending", "sending"),
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                    ("failed", "failed"),
                    ("reconciliation_required", "reconciliation_required"),
                ],
                default="sending",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ["sending", "pending", "reconciliation_required", "approved"],
                    )
                ),
                fields=("intent",),
                name="uma_tentativa_viva_por_intent",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                fields=("intent", "request_hash"),
                name="tentativa_idempotente_por_corpo",
            ),
        ),
        migrations.AddField(
            model_name="paymentoperation",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operacoes",
                to="core.paymentattempt",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentoperation",
            index=models.Index(
                fields=["attempt", "operation_type"],
                name="core_paymen_attempt_aa64bb_idx",
            ),
        ),
    ]
