# Generated by Django 5.0.9 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_appmax_operations"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppmaxWebhookInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=64)),
                ("appmax_site_id", models.CharField(max_length=64)),
                ("platform_site_id", models.CharField(max_length=255)),
                ("event", models.CharField(max_length=100)),
                ("event_type", models.CharField(max_length=50)),
                ("external_order_id", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="appmaxwebhookinbox",
            constraint=models.UniqueConstraint(
                fields=(
                    "app_id",
                    "appmax_site_id",
                    "event",
                    "event_type",
                    "external_order_id",
                ),
                name="appmax_aviso_unico",
            ),
        ),
    ]
