# Generated by Django 5.0.9 on 2026-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_appmax_inbox_supervisionada"),
    ]

    operations = [
        migrations.AddField(
            model_name="appmaxwebhookinbox",
            name="redeliveries",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
