# Generated by Django 5.0.9 on 2026-10-03 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mercadopagowebhookinbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoDoProvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_site_id', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('appmax', 'appmax'), ('mercadopago', 'mercadopago')], max_length=20)),
                ('origem', models.CharField(max_length=40)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('detalhe', models.CharField(blank=True, default='', max_length=120)),
                ('referencia', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observacoes', to='core.paymentattempt')),
            ],
            options={
                'indexes': [models.Index(fields=['platform_site_id', 'provider', 'origem'], name='core_observ_platfor_5085b4_idx')],
            },
        ),
    ]
