# Generated by Django 5.1.4 on 2026-08-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0003_verbos_de_poder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="acao",
            field=models.CharField(
                choices=[
                    ("liberar", "liberar"),
                    ("recusar", "recusar"),
                    ("editar", "editar"),
                    ("promover", "promover a administrador"),
                    ("despromover", "remover de administrador"),
                    ("apagar", "apagar de vez"),
                    ("mover_ideia", "mover a ideia de fase"),
                    ("avaliar_ideia", "escrever a avaliacao da ideia"),
                    ("assinar_obra", "assinar a obra de uma ideia"),
                ],
                max_length=20,
            ),
        ),
    ]
