"""Os dois verbos das conquistas: ligar e desligar uma medalha ou um marco.

Acompanha a segunda metade de `/admin/economia/` (01/09/2026). Sao verbos
PROPRIOS, e nao os de regra com outro alvo, porque a pergunta que se faz ao
historico e diferente: "desde quando esta regra paga?" se responde lendo os
LIGAR_REGRA; "quando a escola passou a reconhecer isto?" se responde lendo
estes. Um verbo so obrigaria quem audita a adivinhar pelo slug.

Mexe so nas ESCOLHAS do campo, nao nos dados: nenhuma linha existente muda.
"""

# Generated by Django 5.1.4 on 2026-09-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0014_alter_registro_acao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="acao",
            field=models.CharField(
                choices=[
                    ("liberar", "liberar"),
                    ("recusar", "recusar"),
                    ("editar", "editar"),
                    ("promover", "promover a administrador"),
                    ("despromover", "remover de administrador"),
                    ("apagar", "apagar de vez"),
                    ("cadastrar", "cadastrar alguem a mao"),
                    ("mover_ideia", "mover a ideia de fase"),
                    ("avaliar_ideia", "escrever a avaliacao da ideia"),
                    ("assinar_obra", "assinar a obra de uma ideia"),
                    ("arquivar_ideia", "arquivar a ideia"),
                    ("desarquivar_ideia", "desarquivar a ideia"),
                    ("apagar_ideia", "apagar a ideia definitivamente"),
                    ("corrigir_ideia", "corrigir o texto da ideia"),
                    ("editar_menu", "mudar o menu do topo do site"),
                    ("criar_documento", "criar um documento do site"),
                    ("editar_documento", "editar um documento do site"),
                    (
                        "restaurar_documento",
                        "voltar um documento a uma versao anterior",
                    ),
                    (
                        "arquivar_documento",
                        "tirar um documento do ar, guardando o texto",
                    ),
                    ("desarquivar_documento", "devolver um documento arquivado"),
                    ("apagar_documento", "apagar um documento definitivamente"),
                    ("ligar_regra", "ligar uma regra de pontuacao da escola"),
                    ("desligar_regra", "desligar uma regra de pontuacao da escola"),
                    ("ligar_conquista", "ligar uma medalha ou marco da escola"),
                    ("desligar_conquista", "desligar uma medalha ou marco da escola"),
                    ("resetar_senha", "resetar a senha de um aluno"),
                ],
                max_length=32,
            ),
        ),
    ]
