"""O verbo do aviso de teste: a pessoa mandou um aviso para o proprio aparelho,
para saber se os avisos na tela do celular estao chegando.

Nasceu do caso de 02/09/2026: o botao de ligar os avisos falhava no navegador
do mantenedor com o servidor verde, e nao havia como distinguir "nao foi
enviado" de "foi enviado e nao chegou" sem entrar na VPS. Verbo PROPRIO, e nao
um `editar` reaproveitado, porque a pergunta que se faz a estas linhas ("quantas
vezes o mantenedor precisou confirmar o canal, e quando") nao se responde
lendo nenhum outro verbo — e porque esta acao nao muda estado de aluno nenhum,
ao contrario de todos os outros.

Mexe so nas ESCOLHAS do campo, nao nos dados nem no tipo da coluna: nenhuma
linha existente muda, e o Django nao reconstroi a tabela (mesmo caso da
`0017`).
"""

# Generated by Django 5.1.4 on 2026-09-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0017_verbo_de_reconsiderar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="acao",
            field=models.CharField(
                choices=[
                    ("liberar", "liberar"),
                    ("recusar", "recusar"),
                    ("editar", "editar"),
                    ("promover", "promover a administrador"),
                    ("despromover", "remover de administrador"),
                    ("apagar", "apagar de vez"),
                    ("cadastrar", "cadastrar alguem a mao"),
                    ("reconsiderar", "aceitar quem tinha sido recusado"),
                    ("mover_ideia", "mover a ideia de fase"),
                    ("avaliar_ideia", "escrever a avaliacao da ideia"),
                    ("assinar_obra", "assinar a obra de uma ideia"),
                    ("arquivar_ideia", "arquivar a ideia"),
                    ("desarquivar_ideia", "desarquivar a ideia"),
                    ("apagar_ideia", "apagar a ideia definitivamente"),
                    ("corrigir_ideia", "corrigir o texto da ideia"),
                    ("editar_menu", "mudar o menu do topo do site"),
                    ("criar_documento", "criar um documento do site"),
                    ("editar_documento", "editar um documento do site"),
                    (
                        "restaurar_documento",
                        "voltar um documento a uma versao anterior",
                    ),
                    (
                        "arquivar_documento",
                        "tirar um documento do ar, guardando o texto",
                    ),
                    ("desarquivar_documento", "devolver um documento arquivado"),
                    ("apagar_documento", "apagar um documento definitivamente"),
                    ("ligar_regra", "ligar uma regra de pontuacao da escola"),
                    ("desligar_regra", "desligar uma regra de pontuacao da escola"),
                    ("ligar_conquista", "ligar uma medalha ou marco da escola"),
                    ("desligar_conquista", "desligar uma medalha ou marco da escola"),
                    ("ligar_degrau", "ligar um degrau da escada de niveis"),
                    ("desligar_degrau", "desligar um degrau da escada de niveis"),
                    ("resetar_senha", "resetar a senha de um aluno"),
                    (
                        "testar_aviso",
                        "mandar um aviso de teste para o proprio aparelho",
                    ),
                ],
                max_length=32,
            ),
        ),
    ]
