"""Os tres verbos da tela das sequencias de mensagens
(`/admin/escola/jornadas/`, degrau 7 do PLANO-SEQUENCIAS-DE-MENSAGENS.md).

Tres, e nao um so, porque sao tres perguntas diferentes ao historico: "desde
quando a escola manda esta sequencia?" (ligar), "desde quando ela parou de
pegar gente nova?" (desligar) e "quem trocou aquela frase, e quando?"
(publicar). Um verbo unico com o estado no `detalhe` faria a leitura do
historico depender de ler o texto livre de cada linha.

`publicar_texto` e o mais pesado desta tabela, e vale dizer por que: do outro
lado, publicar nao EDITA nada — cria uma versao nova, imutavel por gatilho no
Postgres. A versao antiga continua legivel para sempre, mas ela nao sabe QUEM
escreveu a nova, e esta linha e a unica resposta possivel para essa pergunta.

Mexe so nas ESCOLHAS do campo, nao nos dados nem no tipo da coluna: nenhuma
linha existente muda, e o Django nao reconstroi a tabela (mesmo caso da `0018`,
e e isso que mantem de pe os tres gatilhos de append-only — `armadilhas/246`).

# Generated by Django 5.1.4 on 2026-09-04 16:16
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0019_verbo_de_apagar_recusado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="acao",
            field=models.CharField(
                choices=[
                    ("liberar", "liberar"),
                    ("recusar", "recusar"),
                    ("editar", "editar"),
                    ("promover", "promover a administrador"),
                    ("despromover", "remover de administrador"),
                    ("apagar", "apagar de vez"),
                    ("cadastrar", "cadastrar alguem a mao"),
                    ("reconsiderar", "aceitar quem tinha sido recusado"),
                    ("mover_ideia", "mover a ideia de fase"),
                    ("avaliar_ideia", "escrever a avaliacao da ideia"),
                    ("assinar_obra", "assinar a obra de uma ideia"),
                    ("arquivar_ideia", "arquivar a ideia"),
                    ("desarquivar_ideia", "desarquivar a ideia"),
                    ("apagar_ideia", "apagar a ideia definitivamente"),
                    ("corrigir_ideia", "corrigir o texto da ideia"),
                    ("editar_menu", "mudar o menu do topo do site"),
                    ("criar_documento", "criar um documento do site"),
                    ("editar_documento", "editar um documento do site"),
                    (
                        "restaurar_documento",
                        "voltar um documento a uma versao anterior",
                    ),
                    (
                        "arquivar_documento",
                        "tirar um documento do ar, guardando o texto",
                    ),
                    ("desarquivar_documento", "devolver um documento arquivado"),
                    ("apagar_documento", "apagar um documento definitivamente"),
                    ("ligar_regra", "ligar uma regra de pontuacao da escola"),
                    ("desligar_regra", "desligar uma regra de pontuacao da escola"),
                    ("ligar_conquista", "ligar uma medalha ou marco da escola"),
                    ("desligar_conquista", "desligar uma medalha ou marco da escola"),
                    ("ligar_degrau", "ligar um degrau da escada de niveis"),
                    ("desligar_degrau", "desligar um degrau da escada de niveis"),
                    ("resetar_senha", "resetar a senha de um aluno"),
                    (
                        "testar_aviso",
                        "mandar um aviso de teste para o proprio aparelho",
                    ),
                    ("apagar_recusado", "apagar de vez um pedido recusado"),
                    ("ligar_sequencia", "ligar uma sequencia de mensagens"),
                    ("desligar_sequencia", "desligar uma sequencia de mensagens"),
                    ("publicar_texto", "trocar o texto de uma mensagem automatica"),
                ],
                max_length=32,
            ),
        ),
    ]
