# Generated by Django 5.1.4 on 2026-08-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventoProcessado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("event", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnvioRegistrado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=100)),
                ("site_id", models.CharField(max_length=100)),
                ("order_id", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=40)),
                (
                    "canal",
                    models.CharField(
                        choices=[("email", "email"), ("whatsapp", "whatsapp")],
                        max_length=20,
                    ),
                ),
                ("destinatario", models.CharField(max_length=255)),
                ("assunto", models.CharField(blank=True, default="", max_length=255)),
                ("corpo", models.TextField()),
                ("template_versao", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "pendente"),
                            ("enviado", "enviado"),
                            ("falhou", "falhou"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("tentativas", models.PositiveSmallIntegerField(default=0)),
                ("resultado", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order_id", "tipo", "canal"),
                        name="uniq_envio_por_order_tipo_canal",
                    )
                ],
            },
        ),
    ]
