# Generated by Django 5.1 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnderecoDeEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("devolucao", "devolução"),
                            ("reclamacao", "reclamação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bloqueado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="JanelaDeCapacidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(default="email", max_length=32, unique=True),
                ),
                ("minuto_em", models.DateTimeField()),
                ("envios_no_minuto", models.PositiveIntegerField(default=0)),
                ("hora_em", models.DateTimeField()),
                ("envios_na_hora", models.PositiveIntegerField(default=0)),
                ("disjuntor_ate", models.DateTimeField(blank=True, null=True)),
                ("falhas_consecutivas", models.PositiveSmallIntegerField(default=0)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
