# Generated by Django 5.1 on 2026-09-20
# TAR-549: dedup entre versões do mesmo fato de pagamento (x-ponte-do-v1).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_reputacao_e_capacidade"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatoDeProvedorVisto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=100)),
                ("chave", models.CharField(max_length=255)),
                ("event_id", models.UUIDField()),
                ("visto_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="fatodeprovedorvisto",
            constraint=models.UniqueConstraint(
                fields=("evento", "chave"), name="uniq_fato_por_evento_e_chave"
            ),
        ),
    ]
