# Generated by Django 5.1.4 on 2026-10-04 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentes', '0005_mapa_de_conhecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('site_id', models.CharField(blank=True, default='', max_length=80)),
                ('oportunidade_ref', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('pedido_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='EstrategiaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('analista', 'Analista do lead'), ('abordagem', 'Abordagem'), ('atendimento', 'Atendimento e negociação'), ('resultados', 'Análise de resultados')], max_length=20)),
                ('versao', models.PositiveIntegerField()),
                ('instrucoes', models.TextField()),
                ('ativa', models.BooleanField(default=False)),
                ('situacao', models.CharField(choices=[('proposta', 'Proposta'), ('ativa', 'Ativa'), ('arquivada', 'Arquivada')], default='proposta', max_length=20)),
                ('criada_por', models.CharField(blank=True, default='', max_length=200)),
                ('motivo', models.TextField(blank=True, default='')),
                ('origem', models.CharField(blank=True, default='', max_length=20)),
                ('evidencias', models.JSONField(blank=True, default=dict)),
                ('historico', models.JSONField(blank=True, default=list)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ativada_em', models.DateTimeField(blank=True, null=True)),
                ('desativada_em', models.DateTimeField(blank=True, null=True)),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguintes', to='comercial.estrategiacomercial')),
            ],
            options={
                'ordering': ['papel', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='TrabalhoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('analisar_lead', 'Analisar o lead'), ('abordar', 'Abordar o lead'), ('atender_mensagem', 'Atender mensagem'), ('acompanhar_pagamento', 'Acompanhar pagamento'), ('analisar_resultados', 'Analisar resultados')], max_length=30)),
                ('papel', models.CharField(blank=True, default='', max_length=20)),
                ('origem', models.CharField(blank=True, default='', max_length=30)),
                ('evento_id', models.CharField(blank=True, default='', max_length=120)),
                ('site_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('contato_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('oportunidade_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('conversa_id', models.CharField(blank=True, default='', max_length=120)),
                ('pedido_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('chave_da_conversa', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('chave_idempotencia', models.CharField(max_length=200, unique=True)),
                ('estado', models.CharField(choices=[('na_fila', 'Na fila'), ('executando', 'Executando'), ('aguardando_dependencia', 'Aguardando serviço'), ('aguardando_autorizacao', 'Aguardando teto de gasto'), ('envio_incerto', 'Envio sem confirmação'), ('concluido', 'Concluído'), ('encerrado', 'Encerrado sem precisar agir'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='na_fila', max_length=30)),
                ('motivo', models.TextField(blank=True, default='')),
                ('entrada', models.JSONField(blank=True, default=dict)),
                ('retomada', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('resumo', models.TextField(blank=True, default='')),
                ('teste', models.BooleanField(default=False)),
                ('modelo', models.CharField(blank=True, default='', max_length=60)),
                ('custo_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('trabalhador', models.CharField(blank=True, default='', max_length=120)),
                ('ocupado_ate', models.DateTimeField(blank=True, null=True)),
                ('batimento_em', models.DateTimeField(blank=True, null=True)),
                ('nao_antes_de', models.DateTimeField(blank=True, null=True)),
                ('encerrar_pedido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('terminado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguintes', to='comercial.trabalhocomercial')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DecisaoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(blank=True, default='', max_length=20)),
                ('versao_estrategia', models.PositiveIntegerField(blank=True, null=True)),
                ('call_id', models.CharField(max_length=120)),
                ('acao', models.CharField(blank=True, default='', max_length=60)),
                ('ferramenta', models.CharField(blank=True, default='', max_length=80)),
                ('contexto_usado', models.JSONField(blank=True, default=dict)),
                ('entrada', models.JSONField(blank=True, default=dict)),
                ('saida', models.JSONField(blank=True, default=dict)),
                ('resultado', models.CharField(choices=[('pendente', 'Saindo'), ('feito', 'Feito'), ('recusado', 'Recusado'), ('indisponivel', 'Capacidade indisponível'), ('incerto', 'Sem confirmação'), ('decidido', 'Decidido')], max_length=20)),
                ('chave_idempotencia', models.CharField(blank=True, default='', max_length=80)),
                ('custo_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('terminada_em', models.DateTimeField(blank=True, null=True)),
                ('consumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agentes.consumo')),
                ('estrategia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisoes', to='comercial.estrategiacomercial')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes', to='comercial.trabalhocomercial')),
            ],
            options={
                'ordering': ['criada_em', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='estrategiacomercial',
            constraint=models.UniqueConstraint(fields=('papel', 'versao'), name='estrategia_versao_unica'),
        ),
        migrations.AddConstraint(
            model_name='estrategiacomercial',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('papel',), name='uma_estrategia_ativa_por_papel'),
        ),
        migrations.AddIndex(
            model_name='trabalhocomercial',
            index=models.Index(fields=['estado', 'criado_em'], name='comercial_trabalho_fila_idx'),
        ),
        migrations.AddConstraint(
            model_name='trabalhocomercial',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['executando', 'envio_incerto']), models.Q(('chave_da_conversa', ''), _negated=True)), fields=('chave_da_conversa',), name='uma_resposta_por_conversa'),
        ),
        migrations.AddConstraint(
            model_name='decisaocomercial',
            constraint=models.UniqueConstraint(fields=('trabalho', 'call_id'), name='uma_decisao_por_chamada'),
        ),
    ]
