# Generated by Django 5.1.4 on 2026-10-04 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentoEstrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('analista', 'Analista do lead'), ('abordagem', 'Abordagem'), ('atendimento', 'Atendimento e negociação'), ('resultados', 'Análise de resultados')], max_length=20)),
                ('percentual', models.PositiveSmallIntegerField(default=20)),
                ('estado', models.CharField(choices=[('em_teste', 'Em teste'), ('promovida', 'Candidata promovida'), ('revertida', 'Voltou à anterior'), ('encerrada', 'Encerrado sem conclusão')], default='em_teste', max_length=20)),
                ('motivo', models.TextField(blank=True, default='')),
                ('conclusao', models.TextField(blank=True, default='')),
                ('comparativo', models.JSONField(blank=True, default=dict)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comercial.estrategiacomercial')),
                ('candidata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comercial.estrategiacomercial')),
            ],
            options={
                'ordering': ['-iniciado_em', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'em_teste')), fields=('papel',), name='um_teste_por_papel')],
            },
        ),
    ]
