# Generated by Django 5.1.4 on 2026-10-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_tabela_do_experimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoDaComparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.PositiveSmallIntegerField(default=0)),
                ('atualizado_por', models.CharField(blank=True, default='', max_length=200)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comercial_configuracaodacomparacao',
            },
        ),
        migrations.CreateModel(
            name='MarcaDeComparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=80)),
                ('chave', models.CharField(max_length=64)),
                ('sessao', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('contato_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('grupo', models.CharField(max_length=20)),
                ('percentual', models.PositiveSmallIntegerField(default=0)),
                ('teste', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comercial_marcadecomparacao',
                'constraints': [models.UniqueConstraint(fields=('site_id', 'chave'), name='uma_marca_por_lead_e_site')],
            },
        ),
    ]
