# Generated by Django 5.1.4 on 2026-10-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_tabela_do_experimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhocomercial',
            name='tipo',
            field=models.CharField(choices=[('analisar_lead', 'Analisar o lead'), ('abordar', 'Abordar o lead'), ('atender_mensagem', 'Atender mensagem'), ('acompanhar_pagamento', 'Acompanhar pagamento'), ('analisar_resultados', 'Analisar resultados'), ('reanalisar_perfil', 'Atualizar o perfil')], max_length=30),
        ),
    ]
