# Generated by Django 5.1.4 on 2026-10-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_tipo_atualizar_o_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhocomercial',
            name='tipo',
            field=models.CharField(choices=[('analisar_lead', 'Analisar o lead'), ('abordar', 'Abordar o lead'), ('atender_mensagem', 'Atender mensagem'), ('acompanhar_pagamento', 'Acompanhar pagamento'), ('analisar_resultados', 'Analisar resultados'), ('reanalisar_perfil', 'Atualizar o perfil'), ('recuperar_compra', 'Recuperar compra'), ('registrar_estorno', 'Registrar estorno')], max_length=30),
        ),
    ]
