# Generated by Django 5.1.4 on 2026-10-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_tipos_de_recuperacao_e_estorno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligada', models.BooleanField(blank=True, default=None, null=True)),
                ('quizzes', models.JSONField(blank=True, default=list)),
                ('ligada_por', models.CharField(blank=True, default='', max_length=200)),
                ('ligada_em', models.DateTimeField(blank=True, null=True)),
                ('escopo_por', models.CharField(blank=True, default='', max_length=200)),
                ('escopo_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comercial_configuracaocomercial',
            },
        ),
    ]
