# Generated by Django 5.1.4 on 2026-10-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_grupo_de_comparacao'),
        ('comercial', '0004_interruptor_da_equipe'),
        ('comercial', '0005_tipos_de_recuperacao_e_estorno'),
    ]

    operations = [
    ]
