# Generated by Django 5.1.4 on 2026-08-25 10:17

import apps.identidade.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Identidade",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.identidade.models.cunhar_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("provedor", models.CharField(default="google", max_length=20)),
                ("nome_exibido", models.CharField(blank=True, max_length=120)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
