# Generated by Django 5.1.4 on 2026-08-31 19:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identidade", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("event", models.CharField(max_length=100)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("payload", models.JSONField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("envelope_extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["published_at", "id"], name="idt_outbox_pendentes"
                    )
                ],
            },
        ),
    ]
