# Generated by Django 5.1.4 on 2026-08-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identidade", "0002_outbox_de_eventos"),
    ]

    operations = [
        migrations.AddField(
            model_name="identidade",
            name="senha_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
