# Generated by Django 5.1.4 on 2026-09-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identidade", "0003_identidade_senha_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="identidade",
            name="idioma",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
    ]
