# Generated by Django 5.0.9 on 2026-09-18 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oportunidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("etapa", models.CharField(max_length=20)),
                ("titular_id", models.CharField(max_length=100)),
                ("fonte_tipo", models.CharField(max_length=20)),
                ("fonte_referencia_id", models.CharField(max_length=200)),
                ("passo_descricao", models.TextField()),
                ("passo_executar_ate", models.DateTimeField()),
                ("passo_evidencia_esperada", models.TextField()),
                (
                    "desfecho_resultado",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("desfecho_motivo", models.TextField(blank=True, default="")),
                ("desfecho_evidencia", models.TextField(blank=True, default="")),
                ("desfecho_encerrada_em", models.DateTimeField(blank=True, null=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oportunidades",
                        to="core.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroHistoricoOportunidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                ("autor_id", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=30)),
                ("descricao", models.TextField()),
                ("evidencia", models.TextField(blank=True, default="")),
                (
                    "oportunidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico",
                        to="core.oportunidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferenciaResponsabilidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("de_titular_id", models.CharField(max_length=100)),
                ("para_titular_id", models.CharField(max_length=100)),
                ("motivo", models.TextField()),
                ("estado", models.CharField(default="pendente", max_length=10)),
                ("solicitada_em", models.DateTimeField(auto_now_add=True)),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_recusa", models.TextField(blank=True, default="")),
                (
                    "oportunidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias",
                        to="core.oportunidade",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="oportunidade",
            index=models.Index(
                fields=["titular_id", "-criada_em"],
                name="core_oportu_titular_1ed042_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="oportunidade",
            index=models.Index(
                fields=["lead", "-criada_em"], name="core_oportu_lead_id_4efe6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrohistoricooportunidade",
            index=models.Index(
                fields=["oportunidade", "registrado_em"],
                name="core_regist_oportun_400595_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transferenciaresponsabilidade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "pendente")),
                fields=("oportunidade",),
                name="uniq_transferencia_pendente_por_oportunidade",
            ),
        ),
    ]
