# Generated by Django 5.0.9 on 2026-09-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_oportunidades"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatoDePagamentoProcessado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=40)),
                ("chave", models.CharField(max_length=200)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="fatodepagamentoprocessado",
            constraint=models.UniqueConstraint(
                fields=("evento", "chave"), name="uniq_fato_pagamento_por_evento"
            ),
        ),
    ]
