# Generated by Django 5.0.9 on 2026-10-03 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


def quizzes_ja_respondidos(apps, schema_editor):
    """Quem respondeu antes desta versão também aparece com o quiz na ficha."""
    from ..quiz_do_lead import respostas_legiveis

    TimelineEvent = apps.get_model("core", "TimelineEvent")
    QuizDoLead = apps.get_model("core", "QuizDoLead")
    eventos = TimelineEvent.objects.filter(event="quiz.completado").order_by("occurred_at", "id")
    for evento in eventos.iterator():
        dados = evento.payload if isinstance(evento.payload, dict) else {}
        utm = dados.get("utm") if isinstance(dados.get("utm"), dict) else {}
        score = dados.get("score")
        QuizDoLead.objects.create(
            lead_id=evento.lead_id,
            quiz_slug=str(dados.get("quiz_slug") or "quiz")[:100],
            versao=str(dados.get("version_key") or "")[:100],
            situacao="completo",
            respostas=respostas_legiveis(dados.get("respostas")),
            resultado=str(dados.get("result_key") or "")[:100],
            pontuacao=score if isinstance(score, int) and not isinstance(score, bool) else None,
            utm=utm,
            campanha=str(utm.get("utm_campaign") or "")[:200],
            ultimo_event_id=evento.event_id,
            completado_em=evento.occurred_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reversaodepagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='aguardando_resposta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='atendido_por_nome',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='atendido_por_tipo',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='objecao_principal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='ultimo_contato_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuizDoLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quiz_slug', models.CharField(max_length=100)),
                ('sessao', models.CharField(blank=True, default='', max_length=100)),
                ('submissao_id', models.CharField(blank=True, default='', max_length=100)),
                ('versao', models.CharField(blank=True, default='', max_length=100)),
                ('situacao', models.CharField(default='parcial', max_length=10)),
                ('respostas', models.JSONField(blank=True, default=list)),
                ('resultado', models.CharField(blank=True, default='', max_length=100)),
                ('pontuacao', models.IntegerField(blank=True, null=True)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('campanha', models.CharField(blank=True, default='', max_length=200)),
                ('ultimo_event_id', models.UUIDField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('completado_em', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.lead')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDoLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versao', models.PositiveIntegerField()),
                ('resumo', models.TextField(blank=True, default='')),
                ('conteudo', models.JSONField(blank=True, default=dict)),
                ('prioridade', models.CharField(blank=True, default='', max_length=10)),
                ('prioridade_explicacao', models.TextField(blank=True, default='')),
                ('oferta_indicada', models.JSONField(blank=True, null=True)),
                ('analisado_em', models.DateTimeField()),
                ('analisado_por', models.CharField(blank=True, default='', max_length=200)),
                ('versao_estrategia', models.CharField(blank=True, default='', max_length=100)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='core.lead')),
            ],
            options={
                'indexes': [models.Index(fields=['lead', '-versao'], name='core_perfil_lead_id_a4fec6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='perfildolead',
            constraint=models.UniqueConstraint(fields=('lead', 'versao'), name='uniq_perfil_do_lead_versao'),
        ),
        migrations.AddIndex(
            model_name='quizdolead',
            index=models.Index(fields=['lead', '-atualizado_em'], name='core_quizdo_lead_id_eb5911_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizdolead',
            constraint=models.UniqueConstraint(condition=models.Q(('sessao', ''), _negated=True), fields=('lead', 'quiz_slug', 'sessao'), name='uniq_quiz_do_lead_por_sessao'),
        ),
        migrations.RunPython(quizzes_ja_respondidos, migrations.RunPython.noop),
    ]
