# Generated by Django 5.0.9 on 2026-10-03 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reversaodepagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDaOportunidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=100)),
                ('pedido_id', models.CharField(max_length=200)),
                ('oportunidade_ref', models.CharField(blank=True, default='', max_length=200)),
                ('oferta_ref', models.CharField(blank=True, default='', max_length=200)),
                ('produtos', models.JSONField(blank=True, default=list)),
                ('valor_pedido_centavos', models.BigIntegerField(blank=True, null=True)),
                ('falhas', models.JSONField(blank=True, default=list)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('valor_aprovado_centavos', models.BigIntegerField(blank=True, null=True)),
                ('aprovacao_evidencia', models.CharField(blank=True, default='', max_length=200)),
                ('revertida_em', models.DateTimeField(blank=True, null=True)),
                ('valor_revertido_centavos', models.BigIntegerField(default=0)),
                ('motivo_reversao', models.CharField(blank=True, default='', max_length=40)),
                ('sandbox', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.lead')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.oportunidade')),
            ],
            options={
                'indexes': [models.Index(fields=['lead', 'aprovado_em'], name='core_compra_lead_id_f3e131_idx'), models.Index(fields=['oportunidade'], name='core_compra_oportun_b3fc29_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='compradaoportunidade',
            constraint=models.UniqueConstraint(fields=('site_id', 'pedido_id'), name='uniq_compra_site_pedido'),
        ),
    ]
