# Generated by Django 5.0.9 on 2026-10-04 00:27

from pathlib import Path

import django.db.models.deletion
from django.db import migrations, models

# A frente da compra (ramo crm-agentes/leads-compra) também criou uma 0006 a
# partir da 0005. Quando as duas estiverem juntas, esta migração depende das
# duas e vira a única ponta: o migrate não acusa migrações em conflito.
_DA_COMPRA = "0006_compra_da_oportunidade"
_DEPENDENCIAS = [('core', '0006_perfil_respostas_e_acompanhamento')]
if (Path(__file__).resolve().parent / f"{_DA_COMPRA}.py").exists():
    _DEPENDENCIAS.append(('core', _DA_COMPRA))


class Migration(migrations.Migration):

    dependencies = _DEPENDENCIAS

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200)),
                ('aplicado_em', models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='lead',
            name='uniq_lead_site_email',
        ),
        migrations.AddField(
            model_name='quizdolead',
            name='captura_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quizdolead',
            name='oportunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.oportunidade'),
        ),
        migrations.AddIndex(
            model_name='quizdolead',
            index=models.Index(fields=['quiz_slug', 'sessao'], name='core_quizdo_quiz_sl_5bb975_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('site_id', 'email'), name='uniq_lead_site_email'),
        ),
        migrations.AddField(
            model_name='acompanhamentoaplicado',
            name='oportunidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.oportunidade'),
        ),
        migrations.AddConstraint(
            model_name='acompanhamentoaplicado',
            constraint=models.UniqueConstraint(fields=('oportunidade', 'chave'), name='uniq_acompanhamento_aplicado'),
        ),
    ]
