# Generated by Django 5.0.9 on 2026-10-04 00:27

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [('core', '0007_juncao_perfil_e_compra')]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200)),
                ('aplicado_em', models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='lead',
            name='uniq_lead_site_email',
        ),
        migrations.AddField(
            model_name='quizdolead',
            name='captura_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quizdolead',
            name='oportunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.oportunidade'),
        ),
        migrations.AddIndex(
            model_name='quizdolead',
            index=models.Index(fields=['quiz_slug', 'sessao'], name='core_quizdo_quiz_sl_5bb975_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('site_id', 'email'), name='uniq_lead_site_email'),
        ),
        migrations.AddField(
            model_name='acompanhamentoaplicado',
            name='oportunidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.oportunidade'),
        ),
        migrations.AddConstraint(
            model_name='acompanhamentoaplicado',
            constraint=models.UniqueConstraint(fields=('oportunidade', 'chave'), name='uniq_acompanhamento_aplicado'),
        ),
    ]
