# Generated by Django 5.1.4 on 2026-10-09 17:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=100)),
                ('nome', models.CharField(max_length=200)),
                ('origem', models.CharField(choices=[('manual', 'manual'), ('automatico', 'automatico')], max_length=20)),
                ('arquivado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkIndividual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=10, unique=True)),
                ('site_id', models.CharField(db_index=True, max_length=100)),
                ('url_original', models.TextField()),
                ('origem', models.CharField(choices=[('conversa', 'conversa'), ('jornada', 'jornada'), ('manual', 'manual')], max_length=20)),
                ('referencia', models.CharField(max_length=200)),
                ('conversa_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('mensagem_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('jornada_slug', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('inscricao_id', models.UUIDField(blank=True, null=True)),
                ('passo_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='links.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocorrido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(max_length=8)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('classificacao', models.CharField(choices=[('automatico', 'automatico'), ('provavel', 'provavel'), ('indeterminado', 'indeterminado')], max_length=16)),
                ('motivo', models.CharField(max_length=120)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='links.linkindividual')),
            ],
        ),
        migrations.CreateModel(
            name='VersaoDoDestino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('url', models.URLField(max_length=2000)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.CharField(blank=True, default='', max_length=100)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='links.destino')),
            ],
        ),
        migrations.AddField(
            model_name='linkindividual',
            name='versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='links.versaododestino'),
        ),
        migrations.AddConstraint(
            model_name='versaododestino',
            constraint=models.UniqueConstraint(fields=('destino', 'numero'), name='versao_unica_por_destino'),
        ),
        migrations.AddConstraint(
            model_name='linkindividual',
            constraint=models.UniqueConstraint(fields=('site_id', 'origem', 'referencia', 'url_original'), name='link_unico_por_envio'),
        ),
    ]
