# Generated by Django 5.0.14 on 2026-08-19 00:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("event", models.CharField(max_length=100)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("payload", models.JSONField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["published_at"], name="pedidos_out_publish_6883d0_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                ("offer_slug", models.CharField(max_length=200)),
                ("offer", models.JSONField()),
                ("lead_id", models.CharField(blank=True, default="", max_length=64)),
                ("utm", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site_id", "offer_slug"],
                        name="pedidos_ses_site_id_56a203_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando_pagamento", "aguardando_pagamento"),
                            ("pago", "pago"),
                            ("recusado", "recusado"),
                            ("expirado", "expirado"),
                            ("reembolsado", "reembolsado"),
                        ],
                        default="aguardando_pagamento",
                        max_length=32,
                    ),
                ),
                ("items", models.JSONField()),
                ("total_cents", models.PositiveIntegerField()),
                ("customer", models.JSONField()),
                ("method", models.CharField(max_length=8)),
                ("intent_id", models.CharField(max_length=64)),
                ("pix", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="pedidos.session",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("total_cents__gte", 1)), name="order_total_cents_min_1"
            ),
        ),
    ]
