# Generated by Django 5.0.9 on 2026-09-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatoAplicado",
            fields=[
                (
                    "chave",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("aplicado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
