# Generated by Django 5.0.9 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_fatoaplicado"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="visitor_id",
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
