# Generated by Django 5.0.9 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_session_visitor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cartao_em_analise",
            field=models.BooleanField(default=False),
        ),
    ]
