# Generated by Django 5.0.9 on 2026-10-04 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_link_de_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='em_teste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='link_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_reabertas', to='pedidos.linkdecompra'),
        ),
    ]
