# Generated by Django 5.1.4 on 2026-10-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('instancia', models.CharField(max_length=100)),
                ('provider_id', models.CharField(max_length=160)),
                ('telefone', models.CharField(max_length=20)),
                ('conversa_ref', models.CharField(blank=True, default='', max_length=160)),
                ('mensagem_ref', models.CharField(blank=True, default='', max_length=64)),
                ('mime', models.CharField(blank=True, default='', max_length=80)),
                ('segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('tamanho_bytes', models.PositiveIntegerField(default=0)),
                ('conteudo', models.BinaryField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('recebido', 'Recebido, esperando transcrição'), ('transcrito', 'Transcrito'), ('falhou', 'Não foi possível transcrever')], default='recebido', max_length=20)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('erro', models.CharField(blank=True, default='', max_length=300)),
                ('transcricao', models.TextField(blank=True, default='')),
                ('idioma', models.CharField(blank=True, default='', max_length=20)),
                ('modelo', models.CharField(blank=True, default='', max_length=60)),
                ('ambiguidades', models.JSONField(blank=True, default=list)),
                ('pedir_esclarecimento', models.BooleanField(default=False)),
                ('pergunta_de_esclarecimento', models.TextField(blank=True, default='')),
                ('custo_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('transcrito_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'telefone'], name='audio_site_telefone')],
                'constraints': [models.UniqueConstraint(fields=('instancia', 'provider_id'), name='uniq_audio_instancia_provider')],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaDeResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('modo', models.CharField(choices=[('texto', 'Sempre em texto'), ('audio', 'Em áudio quando o canal aceitar'), ('espelhar', 'Em áudio quando o lead mandou áudio')], default='espelhar', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'telefone'), name='uniq_preferencia_site_telefone')],
            },
        ),
        migrations.CreateModel(
            name='RespostaEmVoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('conversa_ref', models.CharField(blank=True, default='', max_length=160)),
                ('chave_idempotencia', models.CharField(max_length=160)),
                ('texto', models.TextField()),
                ('mime', models.CharField(blank=True, default='', max_length=80)),
                ('tamanho_bytes', models.PositiveIntegerField(default=0)),
                ('conteudo', models.BinaryField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, default='', max_length=60)),
                ('voz', models.CharField(blank=True, default='', max_length=40)),
                ('mensagem_ref', models.CharField(blank=True, default='', max_length=64)),
                ('custo_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('instancia', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('desconhecido', 'desconhecido'), ('aceito', 'aceito'), ('enviado', 'enviado'), ('entregue', 'entregue'), ('lido', 'lido'), ('falhou', 'falhou')], default='desconhecido', max_length=20)),
                ('provider_id', models.CharField(blank=True, default='', max_length=160)),
                ('erro', models.CharField(blank=True, default='', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'telefone'], name='voz_site_telefone')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'chave_idempotencia'), name='uniq_voz_site_chave')],
            },
        ),
    ]
