# Generated by Django 5.1.4 on 2026-10-03 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=100)),
                ('canal', models.CharField(choices=[('whatsapp', 'whatsapp'), ('email', 'email')], max_length=20)),
                ('endereco', models.CharField(max_length=254)),
                ('caixa', models.CharField(blank=True, default='', max_length=254)),
                ('lead_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ligacao', models.CharField(choices=[('ligada', 'ligada'), ('ambigua', 'ambigua'), ('desconhecida', 'desconhecida'), ('pendente', 'pendente')], default='pendente', max_length=20)),
                ('estado', models.CharField(choices=[('agente', 'agente'), ('pessoa', 'pessoa'), ('encerrada', 'encerrada')], default='agente', max_length=20)),
                ('assumida_por', models.CharField(blank=True, default='', max_length=100)),
                ('assumida_em', models.DateTimeField(blank=True, null=True)),
                ('janela_aberta_ate', models.DateTimeField(blank=True, null=True)),
                ('ultima_entrada_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'estado', 'ultima_mensagem_em'], name='conv_site_estado_ultima')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'canal', 'endereco'), name='uniq_conversa_site_canal_endereco'), models.CheckConstraint(condition=models.Q(('canal__in', ('whatsapp', 'email'))), name='conversa_canal_conhecido'), models.CheckConstraint(condition=models.Q(('estado__in', ('agente', 'pessoa', 'encerrada'))), name='conversa_estado_conhecido'), models.CheckConstraint(condition=models.Q(('ligacao__in', ('ligada', 'ambigua', 'desconhecida', 'pendente'))), name='conversa_ligacao_conhecida')],
            },
        ),
        migrations.CreateModel(
            name='Descadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('canal', models.CharField(choices=[('whatsapp', 'whatsapp'), ('email', 'email')], max_length=20)),
                ('endereco', models.CharField(max_length=254)),
                ('registrado_em', models.DateTimeField()),
                ('preferencia_registrada', models.BooleanField(default=False)),
                ('preferencia_motivo', models.CharField(blank=True, default='', max_length=200)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conversas.conversa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'canal', 'endereco'), name='uniq_descadastro_site_canal_endereco')],
            },
        ),
        migrations.CreateModel(
            name='MensagemDaConversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direcao', models.CharField(choices=[('entrada', 'entrada'), ('saida', 'saida')], max_length=10)),
                ('autor', models.CharField(choices=[('lead', 'lead'), ('agente', 'agente'), ('pessoa', 'pessoa'), ('sistema', 'sistema')], max_length=10)),
                ('autor_id', models.CharField(blank=True, default='', max_length=100)),
                ('texto', models.TextField(blank=True, default='')),
                ('assunto', models.CharField(blank=True, default='', max_length=300)),
                ('midia_tipo', models.CharField(blank=True, default='', max_length=20)),
                ('midia_referencia', models.CharField(blank=True, default='', max_length=300)),
                ('midia_mime', models.CharField(blank=True, default='', max_length=120)),
                ('transcricao', models.TextField(blank=True, default='')),
                ('estado_envio', models.CharField(choices=[('recebida', 'recebida'), ('pendente', 'pendente'), ('desconhecido', 'desconhecido'), ('aceito', 'aceito'), ('enviado', 'enviado'), ('entregue', 'entregue'), ('lido', 'lido'), ('falhou', 'falhou')], max_length=20)),
                ('erro', models.CharField(blank=True, default='', max_length=300)),
                ('id_externo', models.CharField(blank=True, default='', max_length=300)),
                ('em_resposta_a', models.CharField(blank=True, default='', max_length=300)),
                ('chave_idempotencia', models.CharField(blank=True, default='', max_length=100)),
                ('descadastro', models.BooleanField(default=False)),
                ('ocorrida_em', models.DateTimeField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='conversas.conversa')),
                ('mensagem_whatsapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='whatsapp.mensagemwhatsapp')),
            ],
            options={
                'indexes': [models.Index(fields=['conversa', 'ocorrida_em'], name='msg_conversa_ocorrida')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('id_externo', ''), _negated=True), fields=('conversa', 'direcao', 'id_externo'), name='uniq_msg_conversa_direcao_externo'), models.UniqueConstraint(condition=models.Q(('chave_idempotencia', ''), _negated=True), fields=('conversa', 'chave_idempotencia'), name='uniq_msg_conversa_chave'), models.CheckConstraint(condition=models.Q(('direcao__in', ('entrada', 'saida'))), name='msg_direcao_conhecida'), models.CheckConstraint(condition=models.Q(('estado_envio__in', ('recebida', 'pendente', 'desconhecido', 'aceito', 'enviado', 'entregue', 'lido', 'falhou'))), name='msg_estado_conhecido')],
            },
        ),
    ]
