# Generated by Django 5.1.4 on 2026-10-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversas', '0001_caixa_de_conversas'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrientacaoDoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100, unique=True)),
                ('endereco_quiz', models.CharField(blank=True, default='', max_length=300)),
                ('atendimento_geral', models.CharField(blank=True, default='', max_length=300)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversa',
            name='equipe_confirma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversa',
            name='orientacao_enviada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversa',
            name='orientacao_tipo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
