# Generated by Django 5.1.4 on 2026-08-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_administradores"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.SlugField(max_length=80, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("publico", models.BooleanField(default=False)),
                ("ordem", models.IntegerField(default=1000)),
                ("corpo", models.TextField(blank=True, default="")),
                ("arquivado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["publico", "arquivado", "ordem"],
                        name="core_docume_publico_c696b9_idx",
                    )
                ],
            },
        ),
    ]
