# Generated by Django 5.1.4 on 2026-08-31 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_semear_os_documentos_da_pasta"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersaoDoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("publico", models.BooleanField(default=False)),
                ("ordem", models.IntegerField(default=1000)),
                ("corpo", models.TextField(blank=True, default="")),
                ("salvo_em", models.DateTimeField(auto_now_add=True)),
                (
                    "salvo_por",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("gesto", models.CharField(blank=True, default="", max_length=120)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes",
                        to="core.documento",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["documento", "-salvo_em"],
                        name="core_versao_documen_2f6216_idx",
                    )
                ],
            },
        ),
    ]
