"""As duas tabelas da Biblioteca do Livro (`/admin/livro/`, 04/09/2026).

Pedido do mantenedor: uma pagina onde ele guarda os textos do livro que
escreve, com a formatacao intacta, para o projeto online do livro depois.

NAO HA SEMEADURA AQUI, e a ausencia e a decisao. A migracao `0003` desta mesma
app le a pasta `documentos/` e despeja os textos na tabela, porque aqueles
textos ja existiam no repositorio. Os do livro nunca vao existir la: este
repositorio e PUBLICO de proposito e o livro nao esta lancado, entao o unico
caminho do texto para dentro do sistema e a tela, colado por ele. A tabela
nasce vazia, e a tela sabe dizer isso em portugues.

As duas tabelas na mesma migracao porque o historico nao e opcional: sem
`VersaoDoTexto` desde a primeira gravacao, uma edicao apagaria para sempre o
que estava escrito antes — e aqui nao existe `git log` para socorrer ninguem.

# Generated by Django 5.1.4 on 2026-09-04 19:45
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_o_reembolso_no_texto_que_ja_esta_no_banco"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextoDoLivro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.SlugField(max_length=80, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("ordem", models.IntegerField(default=1000)),
                ("corpo", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ordem", "nome"], name="core_textod_ordem_2bf486_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VersaoDoTexto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("corpo", models.TextField(blank=True, default="")),
                ("salvo_em", models.DateTimeField(auto_now_add=True)),
                (
                    "salvo_por",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("gesto", models.CharField(blank=True, default="", max_length=120)),
                (
                    "texto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes",
                        to="core.textodolivro",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["texto", "-salvo_em"],
                        name="core_versao_texto_i_6d36b5_idx",
                    )
                ],
            },
        ),
    ]
