"""O `Livro` por trás dos capítulos (`/admin/livro/`, 05/09/2026).

Pedido do mantenedor: uma tela de LEITURA, "parecido com o leitor da Amazon
Kindle". Perguntado se era para publicar só o livro que já está salvo ou já
preparar o modelo para vários, ele respondeu **"os dois: publicar o meu agora,
já preparando para vários depois"** — daí o `Livro` nascer aqui, mesmo só
existindo um por enquanto.

TRÊS PASSOS, NA ORDEM, E A ORDEM É O QUE FAZ FUNCIONAR
-------------------------------------------------------
1. Cria a tabela `Livro` e acrescenta `TextoDoLivro.livro` como **nullable**:
   uma coluna `NOT NULL` sem valor não entra numa tabela que já tem linhas.
2. `RunPython`: se existir ao menos um `TextoDoLivro`, cria UM `Livro`
   (`slug="meu-livro"`) e associa todos os capítulos órfãos a ele. Banco vazio
   (teste, ou instalação nova) não cria nada — sem `Livro` órfão.
3. Fecha a coluna em `null=False`: todo capítulo NOVO nasce sempre dentro de
   um `Livro`, e a essa altura nenhum capítulo existente ficou de fora do
   passo 2.

O RETROCESSO É HONESTO, E NÃO FINGE DESFAZER NADA
--------------------------------------------------
Descer esta migração não apaga o `Livro` criado nem desfaz o vínculo à mão: as
duas operações seguintes do reverso (reabrir a coluna para `null=True` e depois
tirá-la de vez) resolvem sozinhas o que sobra — sem coluna, não há vínculo para
inconsistir. Tentar aqui adivinhar se aquele `Livro` ainda é "o automático"
arriscaria apagar um título que o mantenedor já editou pela tela — o mesmo
raciocínio de `0005_o_reembolso_no_texto_que_ja_esta_no_banco`.

# Generated by Django 5.1.4 on 2026-09-05
"""

import django.db.models.deletion
from django.db import migrations, models


def associar_capitulos_a_um_livro(apps, schema_editor):
    Livro = apps.get_model("core", "Livro")
    TextoDoLivro = apps.get_model("core", "TextoDoLivro")

    if not TextoDoLivro.objects.exists():
        # Banco novo (ou banco de teste, que nasce vazio): nada para associar,
        # e criar um `Livro` sem capítulo nenhum seria um `Livro` órfão.
        return

    livro, _ = Livro.objects.get_or_create(
        slug="meu-livro", defaults={"titulo": "Meu livro (edite o título)"}
    )
    TextoDoLivro.objects.filter(livro__isnull=True).update(livro=livro)


def nao_desfaz_a_mao(apps, schema_editor):
    """Ver "O RETROCESSO É HONESTO" no cabeçalho deste arquivo."""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_semear_o_guia_do_portfolio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("ordem", models.IntegerField(default=1000)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ordem", "slug"], name="core_livro_ordem_9a7b7e_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="textodolivro",
            name="livro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capitulos",
                to="core.livro",
            ),
        ),
        migrations.RunPython(associar_capitulos_a_um_livro, nao_desfaz_a_mao),
        migrations.AlterField(
            model_name="textodolivro",
            name="livro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capitulos",
                to="core.livro",
            ),
        ),
    ]
