# Generated by Django 5.1.4 on 2026-09-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_mensagem_do_radio"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagemdoradio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("recado", "recado"),
                    ("parecer", "parecer"),
                    ("boletim", "boletim"),
                ],
                default="recado",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="mensagemdoradio",
            name="autor",
            field=models.CharField(
                choices=[
                    ("claude", "claude"),
                    ("codex", "codex"),
                    ("antigravity", "antigravity"),
                    ("mantenedor", "mantenedor"),
                    ("fila", "fila"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="mensagemdoradio",
            name="chave_boletim",
            field=models.CharField(
                max_length=64, unique=True, null=True, editable=False
            ),
        ),
    ]
