# Generated by Django 5.1.4 on 2026-09-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_tipos_de_mensagem_do_radio"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeituraDoRadio",
            fields=[
                (
                    "sessao",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("autor", models.CharField(max_length=12)),
                ("ultima_sequencia", models.PositiveBigIntegerField(default=0)),
                ("quando", models.DateTimeField(null=True)),
            ],
        ),
    ]
