"""A tabela das imagens e dos videos dos documentos (TAR-597, 21/09/2026).

O arquivo mora no disco da VPS, num volume proprio; esta tabela e o catalogo
dele. Ver `apps/core/midia.py` e `apps/core/models.py::Midia`.
"""

# Generated by Django 5.1.4 on 2026-09-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_semear_o_crivo_explicado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sorteio", models.CharField(max_length=32, unique=True)),
                ("nome", models.CharField(max_length=80)),
                ("tipo", models.CharField(max_length=32)),
                ("tamanho", models.PositiveIntegerField()),
                (
                    "enviado_por",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midias",
                        to="core.documento",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["documento", "-enviado_em"],
                        name="core_midia_documen_aec51d_idx",
                    )
                ],
            },
        ),
    ]
