# Generated by Django 5.1.4 on 2026-10-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_objetivos_compromissos_e_comentarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="autor_membro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comentarios",
                to="core.membrodaequipe",
            ),
        ),
        migrations.AddField(
            model_name="membrodaequipe",
            name="email_a_conferir",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membrodaequipe",
            name="erros_de_senha",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="membrodaequipe",
            name="senha",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="membrodaequipe",
            name="senha_travada_ate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AparelhoDaEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chave_hash", models.CharField(max_length=64, unique=True)),
                ("como_entrou", models.CharField(max_length=10)),
                ("tipo", models.CharField(blank=True, default="", max_length=20)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("ultimo_uso_em", models.DateTimeField()),
                ("desconectado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aparelhos",
                        to="core.membrodaequipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-ultimo_uso_em"],
            },
        ),
        migrations.CreateModel(
            name="LinkDeAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("mantenedor", "Gerado na ficha da pessoa"),
                            ("proprio", "Conectar meu celular"),
                        ],
                        max_length=12,
                    ),
                ),
                ("codigo_hash", models.CharField(max_length=64, unique=True)),
                (
                    "criado_por",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("expira_em", models.DateTimeField()),
                ("usado_em", models.DateTimeField(blank=True, null=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.membrodaequipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
