# Generated by Django 5.1.4 on 2026-09-02 13:41

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

# ===========================================================================
# O QUE O DJANGO 5.1 NÃO SABE ESCREVER, E QUE O PLANO EXIGE
# ===========================================================================
# Duas promessas do `PLANO-SEQUENCIAS-DE-MENSAGENS.md` não cabem no vocabulário
# do ORM. Elas não viram comentário nem disciplina: viram Postgres, pela Lei 1
# do projeto (empurrar a regra escada acima até a impossibilidade física).
#
# `RunSQL` recebe uma LISTA de propósito, e não uma string única: string única
# passa por `prepare_sql_script`, que fatia o SQL em `;` com o `sqlparse` — e o
# corpo dollar-quoted (`$$ ... ; ... $$`) de uma função depende de o `sqlparse`
# acertar esse fatiamento, que é comportamento de dependência transitiva e não
# contrato do Django. Com lista, cada elemento vai direto ao cursor.
# (Mesma escolha, e mesmo motivo, de `services/sugestoes/.../0001_initial.py`.)

# ---------------------------------------------------------------------------
# 1. A CHAVE ESTRANGEIRA COMPOSTA — a versão da inscrição é DAQUELA jornada
# ---------------------------------------------------------------------------
# A trava parcial de `Inscricao` compara por JORNADA (a mesma pessoa andando na
# v1 e na v2 ao mesmo tempo é a mensagem em dobro que ela existe para impedir),
# e `UniqueConstraint` não atravessa chave estrangeira — daí a coluna `jornada`
# ao lado de `jornada_versao`. Coluna denormalizada é coluna que mente no dia em
# que alguém a escreve errado, então quem garante que as duas concordam é o
# banco: o par `(jornada_versao_id, jornada_id)` só existe se existir na
# `JornadaVersao` — é o `uniq_versao_id_com_jornada` que torna o par
# referenciável, e apagá-lo derruba esta guarda sem que nada pareça errado.
#
# SEM `DEFERRABLE`, de propósito: as chaves estrangeiras que o Django cria são
# `DEFERRABLE INITIALLY DEFERRED`, e a recusa só apareceria no `COMMIT`, longe
# da linha que a causou. Imediata, o erro nasce no `INSERT`/`UPDATE` errado — e
# é assim que a guarda sobrevive, de forma legível, a um `queryset.update()`
# (`armadilhas/023`).
FK_COMPOSTA = """
ALTER TABLE jornadas_inscricao
    ADD CONSTRAINT inscricao_versao_pertence_a_jornada
    FOREIGN KEY (jornada_versao_id, jornada_id)
    REFERENCES jornadas_jornadaversao (id, jornada_id);
"""

APAGAR_FK_COMPOSTA = (
    "ALTER TABLE jornadas_inscricao "
    "DROP CONSTRAINT IF EXISTS inscricao_versao_pertence_a_jornada;"
)

# ---------------------------------------------------------------------------
# 2. VERSÃO PUBLICADA É PEDRA — nela, nos passos dela e nos textos deles
# ---------------------------------------------------------------------------
# O plano promete duas coisas ao mesmo tempo: o mantenedor troca a frase quando
# quiser, e ninguém que já está no meio da sequência vê a frase mudar embaixo de
# si. As duas só são compatíveis se a versão for imutável DEPOIS de publicada —
# e "imutável por construção" era, sem isto, promessa: nada impedia um `UPDATE`
# no `TextoDoPasso` de uma versão publicada, e a tela do degrau 7 existe
# justamente para o mantenedor reescrever frases.
#
# Rascunho (`publicada_em` NULL) continua livre: é onde essa tela mexe. Publicar
# é o último `UPDATE` que a linha aceita.
VERSAO_E_PEDRA = """
CREATE OR REPLACE FUNCTION jornadas_versao_publicada_e_pedra()
RETURNS trigger AS $$
BEGIN
    IF OLD.publicada_em IS NOT NULL THEN
        RAISE EXCEPTION
            'jornadas: versao publicada e imutavel (id=%). Publique uma versao NOVA.',
            OLD.id;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

PASSO_E_PEDRA = """
CREATE OR REPLACE FUNCTION jornadas_passo_publicado_e_pedra()
RETURNS trigger AS $$
DECLARE
    publicada timestamptz;
BEGIN
    SELECT jv.publicada_em INTO publicada
      FROM jornadas_jornadaversao jv
     WHERE jv.id = OLD.jornada_versao_id;
    IF publicada IS NOT NULL THEN
        RAISE EXCEPTION
            'jornadas: versao publicada e imutavel; o passo % pertence a ela. Publique uma versao NOVA.',
            OLD.id;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

TEXTO_E_PEDRA = """
CREATE OR REPLACE FUNCTION jornadas_texto_publicado_e_pedra()
RETURNS trigger AS $$
DECLARE
    publicada timestamptz;
BEGIN
    SELECT jv.publicada_em INTO publicada
      FROM jornadas_passo p
      JOIN jornadas_jornadaversao jv ON jv.id = p.jornada_versao_id
     WHERE p.id = OLD.passo_id;
    IF publicada IS NOT NULL THEN
        RAISE EXCEPTION
            'jornadas: versao publicada e imutavel; o texto % pertence a ela. Publique uma versao NOVA.',
            OLD.id;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

GATILHO_VERSAO = """
CREATE TRIGGER jornadas_versao_publicada_e_pedra
BEFORE UPDATE OR DELETE ON jornadas_jornadaversao
FOR EACH ROW EXECUTE FUNCTION jornadas_versao_publicada_e_pedra();
"""

GATILHO_PASSO = """
CREATE TRIGGER jornadas_passo_publicado_e_pedra
BEFORE UPDATE OR DELETE ON jornadas_passo
FOR EACH ROW EXECUTE FUNCTION jornadas_passo_publicado_e_pedra();
"""

GATILHO_TEXTO = """
CREATE TRIGGER jornadas_texto_publicado_e_pedra
BEFORE UPDATE OR DELETE ON jornadas_textodopasso
FOR EACH ROW EXECUTE FUNCTION jornadas_texto_publicado_e_pedra();
"""

APAGAR_PEDRAS = [
    "DROP TRIGGER IF EXISTS jornadas_texto_publicado_e_pedra ON jornadas_textodopasso;",
    "DROP TRIGGER IF EXISTS jornadas_passo_publicado_e_pedra ON jornadas_passo;",
    "DROP TRIGGER IF EXISTS jornadas_versao_publicada_e_pedra ON jornadas_jornadaversao;",
    "DROP FUNCTION IF EXISTS jornadas_texto_publicado_e_pedra();",
    "DROP FUNCTION IF EXISTS jornadas_passo_publicado_e_pedra();",
    "DROP FUNCTION IF EXISTS jornadas_versao_publicada_e_pedra();",
]


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EstadoDoAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinatario_id", models.CharField(db_index=True, max_length=64)),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("ultima_atividade_em", models.DateTimeField(blank=True, null=True)),
                ("ultima_aula_em", models.DateTimeField(blank=True, null=True)),
                ("ultimo_post_em", models.DateTimeField(blank=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("destinatario_id", "site_id"),
                        name="uniq_estado_do_aluno_por_pessoa_e_site",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Jornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("slug", models.SlugField(max_length=80)),
                ("gatilho", models.CharField(max_length=100)),
                ("ativa", models.BooleanField(default=False)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_id", "slug"), name="uniq_jornada_por_site_e_slug"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("gatilho", ""), _negated=True),
                        name="jornada_tem_gatilho",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JornadaVersao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("publicada_em", models.DateTimeField(blank=True, null=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "jornada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versoes",
                        to="jornadas.jornada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("destinatario_id", models.CharField(db_index=True, max_length=64)),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("passo_atual", models.PositiveIntegerField(default=0)),
                ("ancora_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("proximo_em", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("andando", "andando"),
                            ("concluida", "concluida"),
                            ("saiu", "saiu"),
                            ("cancelada", "cancelada"),
                        ],
                        default="andando",
                        max_length=32,
                    ),
                ),
                (
                    "motivo_de_saida",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("origem_event_id", models.UUIDField(blank=True, null=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "jornada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to="jornadas.jornada",
                    ),
                ),
                (
                    "jornada_versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to="jornadas.jornadaversao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                ("atraso", models.DurationField(default=datetime.timedelta(0))),
                ("janela", models.DurationField(blank=True, null=True)),
                (
                    "assunto",
                    models.CharField(
                        choices=[
                            ("sugestao.status-alterado", "sugestao.status-alterado"),
                            (
                                "matricula.situacao-alterada",
                                "matricula.situacao-alterada",
                            ),
                            (
                                "gamificacao.nivel-alcancado",
                                "gamificacao.nivel-alcancado",
                            ),
                            (
                                "gamificacao.conquista-concedida",
                                "gamificacao.conquista-concedida",
                            ),
                            (
                                "gamificacao.marco-validado",
                                "gamificacao.marco-validado",
                            ),
                            (
                                "gamificacao.destaque-da-semana",
                                "gamificacao.destaque-da-semana",
                            ),
                            ("jornada.passo", "jornada.passo"),
                        ],
                        default="jornada.passo",
                        max_length=80,
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("critica", "critica"),
                            ("transacional", "transacional"),
                            ("relacional", "relacional"),
                            ("engajamento", "engajamento"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "canais",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("sino", "sino"),
                                ("email", "email"),
                                ("whatsapp", "whatsapp"),
                            ],
                            max_length=32,
                        ),
                        size=None,
                    ),
                ),
                (
                    "condicao_slug",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "jornada_versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passos",
                        to="jornadas.jornadaversao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("sino", "sino"),
                            ("email", "email"),
                            ("whatsapp", "whatsapp"),
                        ],
                        max_length=32,
                    ),
                ),
                ("decidida_em", models.DateTimeField(auto_now_add=True)),
                ("previsto_para", models.DateTimeField()),
                ("reagendado_para", models.DateTimeField(blank=True, null=True)),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("enviada", "enviada"),
                            ("pulada", "pulada"),
                            ("barrada_pela_regua", "barrada_pela_regua"),
                            ("barrada_por_preferencia", "barrada_por_preferencia"),
                        ],
                        max_length=48,
                    ),
                ),
                ("motivo", models.CharField(blank=True, default="", max_length=200)),
                ("event_id", models.UUIDField(blank=True, null=True)),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entregas",
                        to="jornadas.inscricao",
                    ),
                ),
                (
                    "passo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entregas",
                        to="jornadas.passo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinatario_id", models.CharField(db_index=True, max_length=64)),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("sino", "sino"),
                            ("email", "email"),
                            ("whatsapp", "whatsapp"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("critica", "critica"),
                            ("transacional", "transacional"),
                            ("relacional", "relacional"),
                            ("engajamento", "engajamento"),
                        ],
                        max_length=32,
                    ),
                ),
                ("aceita", models.BooleanField(default=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("destinatario_id", "site_id", "canal", "classe"),
                        name="uniq_preferencia_por_pessoa_canal_classe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("canal__in", ("sino", "email", "whatsapp"))
                        ),
                        name="preferencia_com_canal_conhecido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "classe__in",
                                (
                                    "critica",
                                    "transacional",
                                    "relacional",
                                    "engajamento",
                                ),
                            )
                        ),
                        name="preferencia_com_classe_conhecida",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TextoDoPasso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idioma", models.CharField(max_length=16)),
                ("assunto_visivel", models.CharField(max_length=200)),
                ("corpo", models.TextField()),
                (
                    "passo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="textos",
                        to="jornadas.passo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Efeito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voltou_em", models.DateTimeField(blank=True, null=True)),
                ("abriu_aula_em", models.DateTimeField(blank=True, null=True)),
                ("concluiu_aula_em", models.DateTimeField(blank=True, null=True)),
                ("postou_em", models.DateTimeField(blank=True, null=True)),
                ("apurado_em", models.DateTimeField(auto_now=True)),
                (
                    "entrega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="efeitos",
                        to="jornadas.entrega",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entrega",), name="uniq_efeito_por_entrega"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="jornadaversao",
            constraint=models.UniqueConstraint(
                fields=("jornada", "numero"), name="uniq_versao_por_jornada_e_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadaversao",
            constraint=models.CheckConstraint(
                condition=models.Q(("numero__gte", 1)), name="versao_comeca_no_um"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadaversao",
            constraint=models.UniqueConstraint(
                fields=("id", "jornada"), name="uniq_versao_id_com_jornada"
            ),
        ),
        migrations.AddIndex(
            model_name="inscricao",
            index=models.Index(
                fields=["estado", "proximo_em"], name="idx_inscricao_a_vencer"
            ),
        ),
        migrations.AddConstraint(
            model_name="inscricao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "andando")),
                fields=("jornada", "destinatario_id", "site_id"),
                name="uniq_inscricao_andando_por_jornada",
            ),
        ),
        migrations.AddConstraint(
            model_name="inscricao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estado__in", ("andando", "concluida", "saiu", "cancelada"))
                ),
                name="inscricao_com_estado_conhecido",
            ),
        ),
        migrations.AddConstraint(
            model_name="passo",
            constraint=models.UniqueConstraint(
                fields=("jornada_versao", "ordem"), name="uniq_passo_por_versao_e_ordem"
            ),
        ),
        migrations.AddConstraint(
            model_name="passo",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordem__gte", 1)), name="passo_comeca_no_um"
            ),
        ),
        migrations.AddConstraint(
            model_name="passo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "assunto__in",
                        (
                            "sugestao.status-alterado",
                            "matricula.situacao-alterada",
                            "gamificacao.nivel-alcancado",
                            "gamificacao.conquista-concedida",
                            "gamificacao.marco-validado",
                            "gamificacao.destaque-da-semana",
                            "jornada.passo",
                        ),
                    )
                ),
                name="passo_com_assunto_do_contrato",
            ),
        ),
        migrations.AddConstraint(
            model_name="passo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "classe__in",
                        ("critica", "transacional", "relacional", "engajamento"),
                    )
                ),
                name="passo_com_classe_conhecida",
            ),
        ),
        migrations.AddConstraint(
            model_name="passo",
            constraint=models.CheckConstraint(
                condition=models.Q(("atraso__gte", datetime.timedelta(0))),
                name="passo_nao_espera_para_tras",
            ),
        ),
        migrations.AddConstraint(
            model_name="passo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("canais__contained_by", ["sino", "email", "whatsapp"])
                ),
                name="passo_so_usa_canais_conhecidos",
            ),
        ),
        migrations.AddConstraint(
            model_name="passo",
            constraint=models.CheckConstraint(
                condition=models.Q(("canais", []), _negated=True),
                name="passo_sai_por_algum_canal",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrega",
            constraint=models.UniqueConstraint(
                fields=("inscricao", "passo", "canal"),
                name="uniq_entrega_por_inscricao_passo_canal",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrega",
            constraint=models.CheckConstraint(
                condition=models.Q(("canal__in", ("sino", "email", "whatsapp"))),
                name="entrega_com_canal_conhecido",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrega",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "resultado__in",
                        (
                            "enviada",
                            "pulada",
                            "barrada_pela_regua",
                            "barrada_por_preferencia",
                        ),
                    )
                ),
                name="entrega_com_resultado_conhecido",
            ),
        ),
        migrations.AddConstraint(
            model_name="textodopasso",
            constraint=models.UniqueConstraint(
                fields=("passo", "idioma"), name="uniq_texto_por_passo_e_idioma"
            ),
        ),
        migrations.AddConstraint(
            model_name="textodopasso",
            constraint=models.CheckConstraint(
                condition=models.Q(("idioma", ""), _negated=True),
                name="texto_declara_o_idioma",
            ),
        ),
        migrations.AddConstraint(
            model_name="textodopasso",
            constraint=models.CheckConstraint(
                condition=models.Q(("corpo", ""), _negated=True), name="texto_tem_corpo"
            ),
        ),
        migrations.RunSQL(
            sql=[FK_COMPOSTA],
            reverse_sql=[APAGAR_FK_COMPOSTA],
        ),
        migrations.RunSQL(
            sql=[
                VERSAO_E_PEDRA,
                PASSO_E_PEDRA,
                TEXTO_E_PEDRA,
                GATILHO_VERSAO,
                GATILHO_PASSO,
                GATILHO_TEXTO,
            ],
            reverse_sql=APAGAR_PEDRAS,
        ),
    ]
