# Generated by Django 5.1.4 on 2026-09-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jornadas", "0002_outbox_de_cartas"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvioDeCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("envio_id", models.CharField(max_length=64)),
                ("aula_id", models.CharField(max_length=64)),
                ("aluno_id", models.CharField(db_index=True, max_length=64)),
                ("recebido_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="inscricao",
            name="uniq_inscricao_andando_por_jornada",
        ),
        migrations.AddField(
            model_name="inscricao",
            name="contexto_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="inscricao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "andando")),
                fields=("jornada", "destinatario_id", "site_id", "contexto_id"),
                name="uniq_inscricao_andando_por_jornada",
            ),
        ),
        migrations.AddConstraint(
            model_name="enviodecheckpoint",
            constraint=models.UniqueConstraint(
                fields=("site_id", "envio_id"), name="uniq_envio_de_checkpoint_por_site"
            ),
        ),
    ]
