# Generated by Django 5.1.4 on 2026-10-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimentoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=32)),
                ('chave', models.CharField(max_length=32)),
                ('aceito', models.BooleanField()),
                ('origem', models.CharField(choices=[('quiz.completado', 'quiz.completado'), ('quiz.captura_parcial', 'quiz.captura_parcial'), ('quiz.consentimento', 'quiz.consentimento'), ('equipe', 'equipe')], max_length=40)),
                ('sessao', models.CharField(blank=True, default='', max_length=64)),
                ('referencia', models.CharField(blank=True, default='', max_length=64)),
                ('texto', models.TextField(blank=True, default='')),
                ('versao_texto', models.CharField(blank=True, default='', max_length=32)),
                ('event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('pessoa_id', models.CharField(blank=True, default='', max_length=64)),
                ('preferencia_motivo', models.CharField(blank=True, default='', max_length=200)),
                ('registrado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'chave', 'registrado_em'], name='consent_site_chave_em')],
                'constraints': [models.CheckConstraint(condition=models.Q(('origem__in', ('quiz.completado', 'quiz.captura_parcial', 'quiz.consentimento', 'equipe'))), name='consentimento_origem_conhecida')],
            },
        ),
    ]
